-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE POLICY "Enable read access for all users"
    ON public.user_api_keys
    AS PERMISSIVE
    FOR UPDATE
    TO public
    USING (((auth.uid() = user_id) AND ((auth.jwt() ->> 'email'::text) <> 'valyrdemo@gmail.com'::text)));
