create table "public"."prompt" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "prompt" text not null
);


alter table "public"."prompt" enable row level security;

alter table "public"."request" add column "formatted_prompt_id" bigint;

alter table "public"."request" add column "prompt_values" jsonb;

CREATE UNIQUE INDEX prompts_pkey ON public.prompt USING btree (id);

alter table "public"."prompt" add constraint "prompts_pkey" PRIMARY KEY using index "prompts_pkey";

alter table "public"."request" add constraint "request_formatted_prompt_id_fkey" FOREIGN KEY (formatted_prompt_id) REFERENCES prompt(id) not valid;

alter table "public"."request" validate constraint "request_formatted_prompt_id_fkey";


