// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ack } from "./Ack";
import type { ControlPlaneError } from "./ControlPlaneError";
import type { Update } from "./Update";

export type MessageTypeRX =
  | ({ _type: "Ack" } & Ack)
  | ({ _type: "Update" } & Update)
  | ({ _type: "Error" } & ControlPlaneError);
