create table "public"."contact_submissions" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "first_name" text,
    "last_name" text,
    "email_address" text,
    "company_name" text,
    "company_description" text,
    "tag" text
);


alter table "public"."contact_submissions" enable row level security;

CREATE UNIQUE INDEX contact_submissions_pkey ON public.contact_submissions USING btree (id);

alter table "public"."contact_submissions" add constraint "contact_submissions_pkey" PRIMARY KEY using index "contact_submissions_pkey";

create policy "Enable write access for all users"
on "public"."contact_submissions"
as permissive
for insert
to public
with check (true);



