/**
 *
 * DO NOT EDIT THIS FILE UNLESS IT IS IN /costs
 */

import { ModelRow } from "../../interfaces/Cost";

export const costs: ModelRow[] = [
  {
    model: {
      operator: "equals",
      value: "llama2-70b-4096",
    },
    cost: {
      prompt_token: 0.0000007,
      completion_token: 0.0000008,
    },
    max_window_size: 4096,
  },
  {
    model: {
      operator: "equals",
      value: "mixtral-8x7b-32768",
    },
    cost: {
      prompt_token: 0.00000024,
      completion_token: 0.00000024,
    },
    max_window_size: 32768,
  },
  {
    model: {
      operator: "equals",
      value: "gemma-7b-it",
    },
    cost: {
      prompt_token: 0.00000007,
      completion_token: 0.00000007,
    },
    max_window_size: 32768,
  },
  {
    model: {
      operator: "equals",
      value: "gemma2-9b-it",
    },
    cost: {
      prompt_token: 0.0000002,
      completion_token: 0.0000002,
    },
    max_window_size: 32768,
  },
  {
    model: {
      operator: "equals",
      value: "llama3-70b-8192",
    },
    cost: {
      prompt_token: 0.00000059,
      completion_token: 0.00000079,
    },
    max_window_size: 8192,
  },
  {
    model: {
      operator: "equals",
      value: "llama3-8b-8192",
    },
    cost: {
      prompt_token: 0.00000005,
      completion_token: 0.00000008,
    },
    max_window_size: 8192,
  },
  {
    model: {
      operator: "equals",
      value: "llama3-groq-70b-8192-tool-use-preview",
    },
    cost: {
      prompt_token: 0.00000089,
      completion_token: 0.00000089,
    },
    max_window_size: 8192,
  },
  {
    model: {
      operator: "equals",
      value: "llama3-groq-8b-8192-tool-use-preview",
    },
    cost: {
      prompt_token: 0.00000019,
      completion_token: 0.00000019,
    },
    max_window_size: 8192,
  },
];
