/**
 *
 * DO NOT EDIT THIS FILE UNLESS IT IS IN /costs
 */
import { ModelRow } from "../../../interfaces/Cost";

export const costs: ModelRow[] = [
  {
    model: {
      operator: "equals",
      value: "aws%20eu.amazon.nova-micro-v1%3A0",
    },
    cost: {
      prompt_token: 0.000046,
      completion_token: 0.000184,
    },
  },
  {
    model: {
      operator: "equals",
      value: "aws%20eu.amazon.nova-lite-v1%3A0",
    },
    cost: {
      prompt_token: 0.000078,
      completion_token: 0.000312,
    },
  },
  {
    model: {
      operator: "equals",
      value: "aws%20eu.amazon.nova-pro-v1%3A0",
    },
    cost: {
      prompt_token: 0.00105,
      completion_token: 0.0042,
    },
  },
];
