/**
 *
 * DO NOT EDIT THIS FILE UNLESS IT IS IN /costs
 */
import { ModelRow } from "../../../interfaces/Cost";

export const costs: ModelRow[] = [
  {
    model: {
      operator: "equals",
      value: "amazon.nova-micro-v1:0",
    },
    cost: {
      prompt_token: 0.000035,
      completion_token: 0.00014,
    },
  },
  {
    model: {
      operator: "equals",
      value: "amazon.nova-lite-v1:0",
    },
    cost: {
      prompt_token: 0.00006,
      completion_token: 0.00024,
    },
  },
  {
    model: {
      operator: "equals",
      value: "amazon.nova-pro-v1:0",
    },
    cost: {
      prompt_token: 0.0008,
      completion_token: 0.0032,
    },
  },

  //bit above was not working, added eu for Europe
  {
    model: {
      operator: "equals",
      value: "eu.amazon.nova-micro-v1:0",
    },
    cost: {
      prompt_token: 0.000046,
      completion_token: 0.000184,
    },
  },
  {
    model: {
      operator: "equals",
      value: "eu.amazon.nova-lite-v1:0",
    },
    cost: {
      prompt_token: 0.000078,
      completion_token: 0.000312,
    },
  },
  {
    model: {
      operator: "equals",
      value: "eu.amazon.nova-pro-v1:0",
    },
    cost: {
      prompt_token: 0.00105,
      completion_token: 0.0042,
    },
  },
];
