/**
 *
 * DO NOT EDIT THIS FILE UNLESS IT IS IN /costs
 */

interface TextOperator {
  operator: "equals" | "startsWith" | "includes";
  value: string;
}

export interface ModelDetails {
  contextWindow: number;
  features: {
    vision: boolean;
    json: boolean;
    functionCalling: boolean;
    parallelFunctions: boolean;
    reproduction: boolean;
  };
  status: "preview" | "stable" | "deprecated";
  releaseDate: string; // ISO date string
  maxOutputTokens: number;
  trainingCutoff: string; // Knowledge cutoff date
  description: string; // Official OpenAI description
}

export interface ModelRow {
  model: TextOperator;
  cost: {
    prompt_token: number;
    completion_token: number;
  };
  showInPlayground?: boolean;
  targetUrl?: string;
  dateRange?: {
    start: string;
    end: string;
  };
  details?: ModelDetails;
}
