repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: no-commit-to-branch
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-json
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.4.2
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.4.2
          - prettier-plugin-tailwindcss@0.6.13
        exclude: |
          (?x)(
            ^(
              .*\.lock$|
              .*\.log$|
              node_modules/|
              .*/node_modules/|
              dist/|
              build/|
              .next/|
              examples/|
              supabase/migrations/|
              clickhouse/migrations/|
              web/lib/clients/jawnTypes/.*\.ts$|
              .*\.proto$
            )
          )
