version: '3.8'
services:
  web:
    build: ./web
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL
      - NEXT_PUBLIC_SUPABASE_ANON_KEY
      - NEXT_PUBLIC_SUPABASE_URL
      - SUPABASE_SERVICE_KEY
      - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
      - STRIPE_SECRET_KEY
      - NEXT_PUBLIC_HELICONE_BILLING_PORTAL_LINK
      - NEXT_PUBLIC_HELICONE_CONTACT_LINK
      - STRIPE_PRICE_ID
      - STRIPE_STARTER_PRICE_ID
      - STRIPE_ENTERPRISE_PRODUCT_ID
      - STRIPE_STARTER_PRODUCT_ID
    depends_on:
      - supabase
  worker:
    build: ./worker
  supabase:
    image: bitnami/supabase-studio:latest
    ports:
      - '5435:5435/tcp'
    environment:
      - SUPABASE_PASSWORD
      - SUPABASE_ACCESS_KEY
    restart: always
    networks:
      - my_network
    command: start
    stop_signal: SIGINT
    labels:
      - 'com.example.description=Supabase'
networks:
  my_network:
    driver: bridge
