name: helicone-local-testing
version: "3.8"

services:
  helicone-all:
    build:
      context: .
    container_name: helicone-all-in-one
    environment:      
      POSTGRES_DB: helicone_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testpassword
      
      FLYWAY_URL: jdbc:postgresql://localhost:5432/helicone_test
      FLYWAY_USER: postgres
      FLYWAY_PASSWORD: testpassword

      CLICKHOUSE_DEFAULT_USER: default
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - clickhouse_data:/var/lib/clickhouse
    ports:
      - "5432:5432"
      - "18123:8123" # HTTP interface (Clickhouse)
      - "19000:9000" # Native interface (Clickhouse)
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
  clickhouse_data:
    driver: local