name: helicone-all-in-one
version: "3.8"

services:
  helicone-all:
    build:
      context: .
    container_name: helicone-all-in-one
    environment:      
      POSTGRES_DB: helicone_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      CLICKHOUSE_DEFAULT_USER: default

      CLICKHOUSE_HOST: http://localhost:8123

      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - clickhouse_data:/var/lib/clickhouse
      - minio_data:/data
    ports:
      - "5432:5432"
      - "18123:8123" # HTTP interface (Clickhouse)
      - "19000:9000" # Native interface (Clickhouse)
      - "9009:9009" # (Clickhouse)
      - "8585:8585" # Jawn API
      - "3000:3000" # Web
      - "9080:9080" # MinIO API (different from default 9000, which is used by Clickhouse)
      - "9001:9001" # MinIO Console
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
  clickhouse_data:
    driver: local
  minio_data:
    driver: local