/**
 *
 * DO NOT EDIT THIS FILE UNLESS IT IS IN /costs
 */

import { ModelRow } from "../../interfaces/Cost";

export const costs: ModelRow[] = [
  {
    model: {
      operator: "equals",
      value: "featherless-ai/Qwerky-72B",
    },
    cost: {
      prompt_token: 0,
      completion_token: 0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "featherless-ai/Qwerky-QwQ-32B",
    },
    cost: {
      prompt_token: 0,
      completion_token: 0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "Qwen/Qwen2.5-72B-Instruct",
    },
    cost: {
      prompt_token: 0,
      completion_token: 0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "all-hands/openhands-lm-32b-v0.1",
    },
    cost: {
      prompt_token: 0,
      completion_token: 0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "Qwen/Qwen2.5-Coder-32B-Instruct",
    },
    cost: {
      prompt_token: 0,
      completion_token: 0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "deepseek-ai/DeepSeek-V3-0324",
    },
    cost: {
      prompt_token: 0,
      completion_token: 0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/Mistral-Small-24B-Instruct-2501",
    },
    cost: {
      prompt_token: 0,
      completion_token: 0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/Mistral-Nemo-Instruct-2407",
    },
    cost: {
      prompt_token: 0,
      completion_token: 0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "ProdeusUnity/Stellar-Odyssey-12b-v0.0",
    },
    cost: {
      prompt_token: 0,
      completion_token: 0,
    },
  },
];
