/**
 *
 * DO NOT EDIT THIS FILE UNLESS IT IS IN /costs
 */

import { ModelRow } from "../../interfaces/Cost";

export const costs: ModelRow[] = [
  // Open Models (deprecated but kept for backward compatibility)
  {
    model: {
      operator: "equals",
      value: "open-mistral-7b",
    },
    cost: {
      prompt_token: 0.00000025,
      completion_token: 0.00000025,
    },
  },
  {
    model: {
      operator: "equals",
      value: "open-mixtral-8x7b",
    },
    cost: {
      prompt_token: 0.0000007,
      completion_token: 0.0000007,
    },
  },
  // Current Mistral Chat Models
  {
    model: {
      operator: "equals",
      value: "mistral-tiny",
    },
    cost: {
      prompt_token: 0.00000014,
      completion_token: 0.00000042,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistral-small",
    },
    cost: {
      prompt_token: 0.00000014,
      completion_token: 0.00000042,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistral-small-latest",
    },
    cost: {
      prompt_token: 0.00000014,
      completion_token: 0.00000042,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistral-medium",
    },
    cost: {
      prompt_token: 0.00000239,
      completion_token: 0.00000717,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistral-medium-latest",
    },
    cost: {
      prompt_token: 0.00000239,
      completion_token: 0.00000717,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistral-large",
    },
    cost: {
      prompt_token: 0.002,
      completion_token: 0.006,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistral-large-latest",
    },
    cost: {
      prompt_token: 0.002,
      completion_token: 0.006,
    },
  },
  // Embedding Models
  {
    model: {
      operator: "equals",
      value: "mistral-embed",
    },
    cost: {
      prompt_token: 0.0000001,
      completion_token: 0.0000001,
    },
  },
  // Additional Mistral models that might be used
  {
    model: {
      operator: "equals",
      value: "mistral-7b-instruct",
    },
    cost: {
      prompt_token: 0.00000014,
      completion_token: 0.00000042,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistral-7b-instruct-v0.1",
    },
    cost: {
      prompt_token: 0.00000014,
      completion_token: 0.00000042,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistral-7b-instruct-v0.2",
    },
    cost: {
      prompt_token: 0.00000014,
      completion_token: 0.00000042,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistral-7b-instruct-v0.3",
    },
    cost: {
      prompt_token: 0.00000014,
      completion_token: 0.00000042,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mixtral-8x7b-instruct",
    },
    cost: {
      prompt_token: 0.00000014,
      completion_token: 0.00000042,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mixtral-8x22b-instruct",
    },
    cost: {
      prompt_token: 0.002,
      completion_token: 0.006,
    },
  },

  {
    model: {
      operator: "equals",
      value: "mistral-medium-3",
    },
    cost: {
      prompt_token: 0.0004,
      completion_token: 0.002,
    },
  },

  {
    model: {
      operator: "equals",
      value: "magistral-medium",
    },
    cost: {
      prompt_token: 0.002,
      completion_token: 0.005,
    },
  },

  {
    model: {
      operator: "equals",
      value: "codestral",
    },
    cost: {
      prompt_token: 0.0003,
      completion_token: 0.0009,
    },
  },

  {
    model: {
      operator: "equals",
      value: "devstral-medium",
    },
    cost: {
      prompt_token: 0.0004,
      completion_token: 0.002,
    },
  },

  {
    model: {
      operator: "equals",
      value: "mistral-saba",
    },
    cost: {
      prompt_token: 0.0002,
      completion_token: 0.0006,
    },
  },

  {
    model: {
      operator: "equals",
      value: "pixtral-large",
    },
    cost: {
      prompt_token: 0.002,
      completion_token: 0.006,
    },
  },

  {
    model: {
      operator: "equals",
      value: "mistral-small-3.2",
    },
    cost: {
      prompt_token: 0.0001,
      completion_token: 0.0003,
    },
  },

  {
    model: {
      operator: "equals",
      value: "mixtral-8x22b",
    },
    cost: {
      prompt_token: 0.002,
      completion_token: 0.006,
    },
  },
];
