/**
 *
 * DO NOT EDIT THIS FILE UNLESS IT IS IN /costs
 */

import { ModelRow } from "../../interfaces/Cost";

export const costs: ModelRow[] = [
  {
    model: {
      operator: "includes",
      value: "gemini-pro",
    },
    cost: {
      prompt_token: 0.000000125,
      completion_token: 0.000000375,
    },
  },
  {
    model: {
      operator: "equals",
      value: "gemini-1.0-pro-vision-001",
    },
    cost: {
      prompt_token: 0.000000125,
      completion_token: 0.000000375,
    },
  },
  {
    model: {
      operator: "equals",
      value: "gemini-1.0-pro",
    },
    cost: {
      prompt_token: 0.000000125,
      completion_token: 0.000000375,
    },
  },
  {
    model: {
      operator: "includes",
      value: "gemini-1.5-flash",
    },
    cost: {
      prompt_token: 0.00000035,
      completion_token: 0.00000105,
    },
  },
  {
    model: {
      operator: "equals",
      value: "gemini-flash-1.5-8b",
    },
    cost: {
      prompt_token: 3.75e-8,
      completion_token: 1.5e-7,
    },
  },
  {
    model: {
      operator: "includes",
      value: "gemini-1.5-pro",
    },
    cost: {
      prompt_token: 0.0000035,
      completion_token: 0.0000105,
    },
  },
  {
    model: {
      operator: "includes",
      value: "gemini-2.0-flash",
    },
    cost: {
      prompt_token: 0.0000001,
      completion_token: 0.0000004,
    },
  },
  {
    model: {
      operator: "includes",
      value: "claude-3-opus",
    },
    cost: {
      prompt_token: 0.000015,
      completion_token: 0.000075,
    },
  },
  {
    model: {
      operator: "includes",
      value: "claude-3-5-haiku",
    },
    cost: {
      prompt_token: 0.0000008,
      completion_token: 0.000004,
    },
  },
  {
    model: {
      operator: "includes",
      value: "claude-3-5-sonnet",
    },
    cost: {
      prompt_token: 0.000003,
      completion_token: 0.000015,
    },
  },
  {
    model: {
      operator: "includes",
      value: "claude-3-7-sonnet",
    },
    cost: {
      prompt_token: 0.000003,
      completion_token: 0.000015,
    },
  },
];
