/**
 *
 * DO NOT EDIT THIS FILE UNLESS IT IS IN /costs
 */

import { ModelDetailsMap, ModelRow } from "../../interfaces/Cost";

export const costs: ModelRow[] = [
  {
    model: {
      operator: "equals",
      value: "claude-instant-1",
    },
    cost: {
      prompt_token: 0.00000163,
      completion_token: 0.0000551,
    },
  },
  {
    model: {
      operator: "equals",
      value: "claude-v1",
    },
    cost: {
      prompt_token: 0.000008,
      completion_token: 0.000024,
    },
  },

  {
    model: {
      operator: "equals",
      value: "claude-2",
    },
    cost: {
      prompt_token: 0.000008,
      completion_token: 0.000024,
    },
  },

  {
    model: {
      operator: "equals",
      value: "claude-instant-1.2",
    },
    cost: {
      prompt_token: 0.00000163,
      completion_token: 0.00000551,
    },
  },
  {
    model: {
      operator: "equals",
      value: "claude-2.0",
    },
    cost: {
      prompt_token: 0.00001102,
      completion_token: 0.00003268,
    },
  },
  {
    model: {
      operator: "equals",
      value: "claude-3-opus-20240229",
    },
    cost: {
      prompt_token: 0.000015,
      completion_token: 0.000075,
    },
    showInPlayground: true,
  },
  {
    model: {
      operator: "equals",
      value: "claude-3-sonnet-20240229",
    },
    cost: {
      prompt_token: 0.000003,
      completion_token: 0.000015,
    },
    showInPlayground: true,
  },
  {
    model: {
      operator: "equals",
      value: "claude-3-5-sonnet-20240620",
    },
    cost: {
      prompt_token: 0.000003,
      completion_token: 0.000015,
    },
    showInPlayground: true,
  },
  {
    model: {
      operator: "equals",
      value: "claude-3-5-sonnet-20241022",
    },
    cost: {
      prompt_token: 0.000003,
      completion_token: 0.000015,
    },
    showInPlayground: true,
  },
  {
    model: {
      operator: "equals",
      value: "claude-3-haiku-20240307",
    },
    cost: {
      prompt_token: 0.00000025,
      completion_token: 0.00000125,
    },
    showInPlayground: true,
  },
  {
    model: {
      operator: "equals",
      value: "claude-3-5-haiku-20241022",
    },
    cost: {
      prompt_token: 0.000001,
      completion_token: 0.000005,
    },
    showInPlayground: true,
  },
];

export const modelDetails: ModelDetailsMap = {
  "claude-3-opus": {
    matches: ["claude-3-opus-20240229"],
    searchTerms: ["claude 3 opus", "claude-3-opus", "opus"],
    info: {
      description:
        "Claude 3 Opus is Anthropic's most capable model, offering state-of-the-art performance across tasks.",
      tradeOffs: [
        "Highest cost among Claude models",
        "May be more than needed for simple tasks",
      ],
      benchmarks: {
        average: 0.00001,
        ifeval: 0.00002,
        bhh: 0.00003,
        hellaswag: 0.00004,
        mmlu: 0.00005,
      },
      capabilities: [],
      strengths: [],
      weaknesses: [],
      recommendations: [],
    },
  },
  "claude-3-sonnet": {
    matches: [
      "claude-3-sonnet-20240229",
      "claude-3-5-sonnet-20240620",
      "claude-3-5-sonnet-20241022",
    ],
    searchTerms: [
      "claude 3 sonnet",
      "claude-3-sonnet",
      "sonnet",
      "claude 3.5 sonnet",
    ],
    info: {
      description:
        "Claude 3 Sonnet offers a strong balance of intelligence and speed, suitable for most use cases.",
      tradeOffs: [
        "Lower cost than Opus",
        "Slightly reduced capabilities compared to Opus",
      ],
      benchmarks: {
        average: 0.00001,
        ifeval: 0.00002,
        bhh: 0.00003,
        hellaswag: 0.00004,
        mmlu: 0.00005,
      },
      capabilities: [],
      strengths: [],
      weaknesses: [],
      recommendations: [],
    },
  },
  "claude-3-haiku": {
    matches: ["claude-3-haiku-20240307", "claude-3-5-haiku-20241022"],
    searchTerms: [
      "claude 3 haiku",
      "claude-3-haiku",
      "haiku",
      "claude 3.5 haiku",
    ],
    info: {
      description:
        "Claude 3 Haiku is Anthropic's fastest and most cost-effective model.",
      tradeOffs: [
        "Fastest response times",
        "Most affordable",
        "Reduced capabilities compared to Opus and Sonnet",
      ],
      benchmarks: {
        average: 0.00001,
        ifeval: 0.00002,
        bhh: 0.00003,
        hellaswag: 0.00004,
        mmlu: 0.00005,
      },
      capabilities: [],
      strengths: [],
      weaknesses: [],
      recommendations: [],
    },
  },
  "claude-2": {
    matches: ["claude-2", "claude-2.0"],
    searchTerms: ["claude 2", "claude-2"],
    info: {
      description:
        "Claude 2 is Anthropic's previous generation model, offering reliable performance for various tasks.",
      tradeOffs: [
        "More affordable than Claude 3",
        "Less capable than newer models",
      ],
      benchmarks: {
        average: 0.00001,
        ifeval: 0.00002,
        bhh: 0.00003,
        hellaswag: 0.00004,
        mmlu: 0.00005,
      },
      capabilities: [],
      strengths: [],
      weaknesses: [],
      recommendations: [],
    },
  },
  "claude-instant": {
    matches: ["claude-instant-1", "claude-instant-1.2"],
    searchTerms: ["claude instant", "claude-instant"],
    info: {
      description:
        "Claude Instant is Anthropic's faster, lighter previous generation model.",
      tradeOffs: [
        "Fastest response times in Claude 2 series",
        "Most affordable",
        "Reduced capabilities",
      ],
      benchmarks: {
        average: 0.00001,
        ifeval: 0.00002,
        bhh: 0.00003,
        hellaswag: 0.00004,
        mmlu: 0.00005,
      },
      capabilities: [],
      strengths: [],
      weaknesses: [],
      recommendations: [],
    },
  },
  "claude-3.5-sonnet": {
    matches: ["claude-3-5-sonnet-20240620", "claude-3-5-sonnet-20241022"],
    searchTerms: ["claude 3.5 sonnet", "claude-3-5-sonnet"],
    info: {
      description:
        "Claude 3.5 Sonnet is Anthropic's latest model, offering a balance of speed and cost.",
      tradeOffs: ["More expensive than Haiku", "Slightly faster than Sonnet"],
      benchmarks: {
        average: 0.00001,
        ifeval: 0.00002,
        bhh: 0.00003,
        hellaswag: 0.00004,
        mmlu: 0.00005,
      },
      capabilities: [],
      strengths: [],
      weaknesses: [],
      recommendations: [],
    },
  },
  "claude-3.5-haiku": {
    matches: ["claude-3-5-haiku-20241022"],
    searchTerms: ["claude 3.5 haiku", "claude-3-5-haiku"],
    info: {
      description:
        "Claude 3.5 Haiku is Anthropic's fastest and most cost-effective model.",
      tradeOffs: [
        "Fastest response times",
        "Most affordable",
        "Reduced capabilities compared to Opus and Sonnet",
      ],
      benchmarks: {
        average: 0.00001,
        ifeval: 0.00002,
        bhh: 0.00003,
        hellaswag: 0.00004,
        mmlu: 0.00005,
      },
      capabilities: [],
      strengths: [],
      weaknesses: [],
      recommendations: [],
    },
  },
};

const reverseModelMap: { [key: string]: string } = {};

for (const parentModel in modelDetails) {
  const details = modelDetails[parentModel];
  details.matches.forEach((modelName) => {
    reverseModelMap[modelName] = parentModel;
  });
}

export const anthropicProvider = {
  costs,
  modelDetails,
  reverseModelMap,
};
