name = "token-calc"
main = "src/index.ts"
compatibility_date = "2023-04-14"
usage_model = "unbound"


[env.production]
name = "helicone-token-calc-prod"
routes = [
	{ pattern = "token_calc.hconeai.com", custom_domain = true, zone_name = "hconeai.com" }
]



