FROM node:18.11.0

WORKDIR /worker

RUN apt-get update && apt-get install -y clang libc++-dev libc++abi-dev

COPY ./package.json /worker/package.json
COPY ./yarn.lock /worker/yarn.lock

WORKDIR /worker
RUN yarn

COPY . /worker

RUN rm -rf ./.wrangler

CMD env > .dev.vars && echo "n" | npx wrangler dev --local --var WORKER_TYPE:${WORKER_TYPE} --ip 0.0.0.0 --port ${WORKER_PORT}
