FROM --platform=linux/amd64 node:20.19

WORKDIR /app
RUN apt update -y
RUN apt install curl git -y
# Install gcc
RUN apt install build-essential -y

COPY . /app/supabase
RUN find /app/supabase -name ".env.*" -exec rm {} \;

WORKDIR /app

CMD ["sh", "-c", "yes | npx supabase db push --db-url ${DATABASE_URL}"]
