FROM node:18.11.0

WORKDIR /worker

RUN apt-get update && apt-get install -y clang libc++-dev libc++abi-dev

RUN npm install -g wrangler

COPY . /app/helicone

WORKDIR /worker/helicone/worker
RUN yarn

CMD env > .dev.vars && echo "n" | wrangler dev --local --var WORKER_TYPE:HELICONE_API --port ${HELICONE_API_PORT}
