FROM node:20

WORKDIR /app/web

# We'll mount the local directory at runtime,
# but install dependencies in the container initially
COPY ./package.json ./yarn.lock ./
RUN yarn install

# Set environment for development
ENV NODE_ENV=development

EXPOSE 3000

# Command will be overridden in docker-compose.yml
CMD ["yarn", "dev:local", "-p", "3000"]