FROM ubuntu:20.04

RUN apt update -y
RUN apt install curl git -y
RUN apt install python3 python3-pip -y


WORKDIR /app
# TODO Make sure the docker build and push commands are still working

COPY ./clickhouse/ /app


CMD python3 ch_hcone.py --upgrade --host ${CLICKHOUSE_HOST} --port ${CLICKHOUSE_PORT}
