FROM node:20

COPY ./package.json /app/web/package.json
COPY ./yarn.lock /app/web/yarn.lock

WORKDIR /app/web

RUN yarn


COPY . /app/web
RUN find /app/web -name ".env.*" -exec rm {} \;

RUN rm .env.* || true

EXPOSE 3000

CMD ["yarn", "dev:local"]