FROM node:18.18.0

RUN apt update -y
RUN apt install curl git -y
RUN apt install python3 python3-pip -y
RUN apt install build-essential -y

COPY . /app/web

WORKDIR /app/web

RUN yarn

ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG NEXT_PUBLIC_BASE_PATH
ARG NEXT_PUBLIC_HELICONE_JAWN_SERVICE

RUN rm .env.* || true

RUN echo NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL} >> .env
RUN echo NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY} >> .env
RUN echo NEXT_PUBLIC_BASE_PATH=${NEXT_PUBLIC_BASE_PATH} >> .env
RUN echo NEXT_PUBLIC_HELICONE_JAWN_SERVICE=${NEXT_PUBLIC_HELICONE_JAWN_SERVICE} >> .env

RUN yarn build

EXPOSE 3000

CMD sh -c "npx supabase db push --db-url ${DATABASE_URL} && python3 clickhouse/ch_hcone.py --upgrade --host ${CLICKHOUSE_HOST_INTERNAL} --port ${CLICKHOUSE_PORT} && yarn start"