FROM debian:stable-slim

RUN apt-get update && apt-get install -y \
    curl ca-certificates \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN curl -sSf https://atlasgo.sh | sh
ENV PATH="/root/bin:/usr/local/bin:${PATH}"

WORKDIR /app

COPY ./clickhouse/migrations /app/clickhouse/migrations

ENTRYPOINT ["/bin/sh", "-lc"]
CMD ["atlas version"]
