/**
 *
 * DO NOT EDIT THIS FILE UNLESS IT IS IN /costs
 */

import { ModelRow } from "../../interfaces/Cost";

export const costs: ModelRow[] = [
  {
    model: {
      operator: "equals",
      value: "qwen3-7-max",
    },
    cost: {
      prompt_token: 0.0000025,
      completion_token: 0.0000075,
    },
  },
  {
    model: {
      operator: "equals",
      value: "deepseek-v4-flash",
    },
    cost: {
      prompt_token: 0.00000014,
      completion_token: 0.00000028,
    },
  },
  {
    model: {
      operator: "equals",
      value: "kimi-k2-7-code",
    },
    cost: {
      prompt_token: 0.00000095,
      completion_token: 0.000004,
    },
  },
  {
    model: {
      operator: "equals",
      value: "glm-5-1",
    },
    cost: {
      prompt_token: 0.0000011,
      completion_token: 0.0000044,
    },
  },
  {
    model: {
      operator: "equals",
      value: "minimax-m3",
    },
    cost: {
      prompt_token: 0.0000003,
      completion_token: 0.0000012,
    },
  },
];
