/**
 *
 * DO NOT EDIT THIS FILE UNLESS IT IS IN /costs
 *
 * Generated by tools/sync_integration_catalogs.py from the public
 * EmpirioLabs /v1/models catalog. Re-run the generator to refresh.
 */

import { ModelRow } from "../../interfaces/Cost";

export const costs: ModelRow[] = [
  {
    model: {
      operator: "equals",
      value: "deepreasoning",
    },
    cost: {
      prompt_token: 0,
      completion_token: 0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "deepseek-prover-v2",
    },
    cost: {
      prompt_token: 0,
      completion_token: 0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "deepseek-v3-2",
    },
    cost: {
      prompt_token: 0.00000057,
      completion_token: 0.00000171,
    },
  },
  {
    model: {
      operator: "equals",
      value: "deepseek-v4-flash",
    },
    cost: {
      prompt_token: 0.00000014,
      completion_token: 0.00000028,
    },
  },
  {
    model: {
      operator: "equals",
      value: "deepseek-v4-pro",
    },
    cost: {
      prompt_token: 0.00000165,
      completion_token: 0.0000033,
    },
  },
  {
    model: {
      operator: "equals",
      value: "fugu-ultra-v1-0",
    },
    cost: {
      prompt_token: 0.0000075,
      completion_token: 0.000045,
    },
  },
  {
    model: {
      operator: "equals",
      value: "fugu-ultra-v1-1",
    },
    cost: {
      prompt_token: 0.000005,
      completion_token: 0.00003,
    },
  },
  {
    model: {
      operator: "equals",
      value: "gemma-3-27b",
    },
    cost: {
      prompt_token: 0,
      completion_token: 0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "gemma-4-26b-a4b",
    },
    cost: {
      prompt_token: 0.00000005,
      completion_token: 0.00000029,
    },
  },
  {
    model: {
      operator: "equals",
      value: "glm-4-5-flash",
    },
    cost: {
      prompt_token: 0,
      completion_token: 0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "glm-4-6v-flash",
    },
    cost: {
      prompt_token: 0,
      completion_token: 0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "glm-4-7-flash",
    },
    cost: {
      prompt_token: 0,
      completion_token: 0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "glm-5-1",
    },
    cost: {
      prompt_token: 0.000000825,
      completion_token: 0.000003301,
    },
  },
  {
    model: {
      operator: "equals",
      value: "glm-5-2",
    },
    cost: {
      prompt_token: 0.0000014,
      completion_token: 0.0000044,
    },
  },
  {
    model: {
      operator: "equals",
      value: "kimi-k2-6",
    },
    cost: {
      prompt_token: 0.0000008939,
      completion_token: 0.0000037131,
    },
  },
  {
    model: {
      operator: "equals",
      value: "kimi-k2-7-code",
    },
    cost: {
      prompt_token: 0.00000095,
      completion_token: 0.000004,
    },
  },
  {
    model: {
      operator: "equals",
      value: "kimi-k2-7-code-highspeed",
    },
    cost: {
      prompt_token: 0.0000019,
      completion_token: 0.000008,
    },
  },
  {
    model: {
      operator: "equals",
      value: "kimi-k3",
    },
    cost: {
      prompt_token: 0.000003,
      completion_token: 0.000015,
    },
  },
  {
    model: {
      operator: "equals",
      value: "magistral-medium-2509-thinking",
    },
    cost: {
      prompt_token: 0.0000026,
      completion_token: 0.0000065,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mimo-v2-5",
    },
    cost: {
      prompt_token: 0.0000007,
      completion_token: 0.0000014,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mimo-v2-5-pro",
    },
    cost: {
      prompt_token: 0.000002175,
      completion_token: 0.00000435,
    },
  },
  {
    model: {
      operator: "equals",
      value: "minimax-m2-7",
    },
    cost: {
      prompt_token: 0.00000015,
      completion_token: 0.0000006,
    },
  },
  {
    model: {
      operator: "equals",
      value: "minimax-m2-7-highspeed",
    },
    cost: {
      prompt_token: 0.0000003,
      completion_token: 0.0000012,
    },
  },
  {
    model: {
      operator: "equals",
      value: "minimax-m3",
    },
    cost: {
      prompt_token: 0.000000225,
      completion_token: 0.0000009,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistral-medium-3",
    },
    cost: {
      prompt_token: 0,
      completion_token: 0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistral-medium-3-1",
    },
    cost: {
      prompt_token: 0.00000052,
      completion_token: 0.0000026,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistral-small-3-1",
    },
    cost: {
      prompt_token: 0,
      completion_token: 0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistral-small-4",
    },
    cost: {
      prompt_token: 0.00000015,
      completion_token: 0.0000006,
    },
  },
  {
    model: {
      operator: "equals",
      value: "muse-spark-1-1",
    },
    cost: {
      prompt_token: 0.00000125,
      completion_token: 0.00000425,
    },
  },
  {
    model: {
      operator: "equals",
      value: "nova-lite-1-0",
    },
    cost: {
      prompt_token: 0.000000069,
      completion_token: 0.00000028,
    },
  },
  {
    model: {
      operator: "equals",
      value: "nova-lite-2",
    },
    cost: {
      prompt_token: 0.00000038,
      completion_token: 0.00000316,
    },
  },
  {
    model: {
      operator: "equals",
      value: "nova-micro-1-0",
    },
    cost: {
      prompt_token: 0.00000004,
      completion_token: 0.00000016,
    },
  },
  {
    model: {
      operator: "equals",
      value: "nova-premier-1-0",
    },
    cost: {
      prompt_token: 0.000003,
      completion_token: 0.000015,
    },
  },
  {
    model: {
      operator: "equals",
      value: "nova-pro-1-0",
    },
    cost: {
      prompt_token: 0.0000024,
      completion_token: 0.0000096,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen3-5-122b-a10b",
    },
    cost: {
      prompt_token: 0.000000115,
      completion_token: 0.000000917,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen3-5-27b",
    },
    cost: {
      prompt_token: 0.000000086,
      completion_token: 0.000000688,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen3-5-35b-a3b",
    },
    cost: {
      prompt_token: 0.000000057,
      completion_token: 0.000000459,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen3-5-397b-a17b",
    },
    cost: {
      prompt_token: 0.000000172,
      completion_token: 0.000001032,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen3-5-4b",
    },
    cost: {
      prompt_token: 0.00000004,
      completion_token: 0.00000007,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen3-5-9b",
    },
    cost: {
      prompt_token: 0.00000009,
      completion_token: 0.00000013,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen3-5-flash",
    },
    cost: {
      prompt_token: 0.00000009,
      completion_token: 0.000000368,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen3-5-omni-flash",
    },
    cost: {
      prompt_token: 0.0000004,
      completion_token: 0.0000022,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen3-5-omni-plus",
    },
    cost: {
      prompt_token: 0.0000014,
      completion_token: 0.0000083,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen3-5-plus",
    },
    cost: {
      prompt_token: 0.00000036,
      completion_token: 0.00000221,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen3-6-27b",
    },
    cost: {
      prompt_token: 0.000000412564,
      completion_token: 0.000002475384,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen3-6-flash",
    },
    cost: {
      prompt_token: 0.00000025,
      completion_token: 0.0000015,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen3-6-max-preview",
    },
    cost: {
      prompt_token: 0.00000131,
      completion_token: 0.00000788,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen3-6-plus",
    },
    cost: {
      prompt_token: 0.0000005,
      completion_token: 0.000003,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen3-7-max",
    },
    cost: {
      prompt_token: 0.0000025,
      completion_token: 0.0000075,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen3-7-plus",
    },
    cost: {
      prompt_token: 0.0000004,
      completion_token: 0.0000016,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen3-max",
    },
    cost: {
      prompt_token: 0.00000108,
      completion_token: 0.00000552,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen3-max-preview",
    },
    cost: {
      prompt_token: 0.00000108,
      completion_token: 0.0000048,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen3-max-thinking",
    },
    cost: {
      prompt_token: 0.00000108,
      completion_token: 0.00000552,
    },
  },
  {
    model: {
      operator: "equals",
      value: "seed-2-0-code",
    },
    cost: {
      prompt_token: 0.0000004,
      completion_token: 0.0000024,
    },
  },
  {
    model: {
      operator: "equals",
      value: "seed-2-0-lite",
    },
    cost: {
      prompt_token: 0.00000031,
      completion_token: 0.0000025,
    },
  },
  {
    model: {
      operator: "equals",
      value: "seed-2-0-mini",
    },
    cost: {
      prompt_token: 0.00000012,
      completion_token: 0.0000005,
    },
  },
  {
    model: {
      operator: "equals",
      value: "seed-2-0-pro",
    },
    cost: {
      prompt_token: 0.00000063,
      completion_token: 0.00000379,
    },
  },
  {
    model: {
      operator: "equals",
      value: "seed-2-1-turbo",
    },
    cost: {
      prompt_token: 0.00000063,
      completion_token: 0.00000313,
    },
  },
  {
    model: {
      operator: "equals",
      value: "step-3-5-flash",
    },
    cost: {
      prompt_token: 0.0000001,
      completion_token: 0.0000003,
    },
  },
  {
    model: {
      operator: "equals",
      value: "step-3-5-flash-2603",
    },
    cost: {
      prompt_token: 0.0000001,
      completion_token: 0.0000003,
    },
  },
  {
    model: {
      operator: "equals",
      value: "step-3-7-flash",
    },
    cost: {
      prompt_token: 0.0000002,
      completion_token: 0.00000115,
    },
  },
  {
    model: {
      operator: "equals",
      value: "stepaudio-2-5-chat",
    },
    cost: {
      prompt_token: 0.00000143,
      completion_token: 0.00000357,
    },
  },
  // Image generation models (per image)
  {
    model: {
      operator: "equals",
      value: "amazon-nova-canvas",
    },
    cost: {
      prompt_token: 0,
      completion_token: 0,
      per_image: 0.12,
    },
  },
  {
    model: {
      operator: "equals",
      value: "flux-2-klein-4b",
    },
    cost: {
      prompt_token: 0,
      completion_token: 0,
      per_image: 0.0085,
    },
  },
  {
    model: {
      operator: "equals",
      value: "hunyuan-image-3",
    },
    cost: {
      prompt_token: 0,
      completion_token: 0,
      per_image: 0.13,
    },
  },
  {
    model: {
      operator: "equals",
      value: "janus-pro-deepseek",
    },
    cost: {
      prompt_token: 0,
      completion_token: 0,
      per_image: 0.03,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen-image-2-0",
    },
    cost: {
      prompt_token: 0,
      completion_token: 0,
      per_image: 0.0322,
    },
  },
  {
    model: {
      operator: "equals",
      value: "seedream-5-0-lite",
    },
    cost: {
      prompt_token: 0,
      completion_token: 0,
      per_image: 0.035,
    },
  },
  {
    model: {
      operator: "equals",
      value: "seedream-5-0-pro",
    },
    cost: {
      prompt_token: 0,
      completion_token: 0,
      per_image: 0.075,
    },
  },
  {
    model: {
      operator: "equals",
      value: "step-image-edit-2",
    },
    cost: {
      prompt_token: 0,
      completion_token: 0,
      per_image: 0.003,
    },
  },
  {
    model: {
      operator: "equals",
      value: "wan2-7-image",
    },
    cost: {
      prompt_token: 0,
      completion_token: 0,
      per_image: 0.03,
    },
  },
];
