/**
 *
 * DO NOT EDIT THIS FILE UNLESS IT IS IN /costs
 */

import { ModelRow } from "../../interfaces/Cost";

export const costs: ModelRow[] = [
  {
    model: {
      operator: "equals",
      value: "sonar-reasoning",
    },
    cost: {
      prompt_token: 0.00001,
      completion_token: 0.00005,
      per_call: 0.00005 / 1000,
    },
  },
  {
    model: {
      operator: "equals",
      value: "sonar",
    },
    cost: {
      prompt_token: 0.00001,
      completion_token: 0.00001,
      per_call: 0.00005 / 1000,
    },
  },
  {
    model: {
      operator: "equals",
      value: "sonar-pro",
    },
    cost: {
      prompt_token: 0.00003,
      completion_token: 0.00015,
      per_call: 0.00005 / 1000,
    },
  },
];
