/**
 * Google endpoint configurations
 */

import type { ModelEndpointMap } from "../../types";
import type { GoogleModelName } from "./models";

export const googleEndpoints = {
  "gemini-2.5-flash-lite": {
    vertex: {
      name: "Google | google/gemini-2.5-flash-lite",
      pricing: {
        prompt: 0.09999999999999999,
        completion: 0.39999999999999997,
        cacheRead: 0.024999999999999998,
        cacheWrite: 0.18330000000000002,
      },
      contextLength: 1048576,
      maxCompletionTokens: 65535,
      supportedParameters: [
        "tools",
        "tool_choice",
        "reasoning",
        "include_reasoning",
        "response_format",
        "max_tokens",
        "temperature",
        "top_p",
        "seed",
      ],
    },
    "google-ai-studio": {
      name: "Google AI Studio | google/gemini-2.5-flash-lite",
      pricing: {
        prompt: 0.09999999999999999,
        completion: 0.39999999999999997,
        cacheRead: 0.024999999999999998,
        cacheWrite: 0.18330000000000002,
      },
      contextLength: 1048576,
      maxCompletionTokens: 65535,
      supportedParameters: [
        "tools",
        "tool_choice",
        "reasoning",
        "include_reasoning",
        "response_format",
        "max_tokens",
        "temperature",
        "top_p",
        "seed",
      ],
    },
  },

  "gemini-2.5-flash-lite-preview-06-17": {
    vertex: {
      name: "Google | google/gemini-2.5-flash-lite-preview-06-17",
      pricing: {
        prompt: 0.09999999999999999,
        completion: 0.39999999999999997,
        cacheRead: 0.024999999999999998,
        cacheWrite: 0.18330000000000002,
      },
      contextLength: 1048576,
      maxCompletionTokens: 65535,
      supportedParameters: [
        "tools",
        "tool_choice",
        "reasoning",
        "include_reasoning",
        "response_format",
        "max_tokens",
        "temperature",
        "top_p",
        "seed",
        "stop",
      ],
    },
    "google-ai-studio": {
      name: "Google AI Studio | google/gemini-2.5-flash-lite-preview-06-17",
      pricing: {
        prompt: 0.09999999999999999,
        completion: 0.39999999999999997,
        cacheRead: 0.024999999999999998,
        cacheWrite: 0.18330000000000002,
      },
      contextLength: 1048576,
      maxCompletionTokens: 65535,
      supportedParameters: [
        "tools",
        "tool_choice",
        "reasoning",
        "include_reasoning",
        "response_format",
        "max_tokens",
        "temperature",
        "top_p",
        "seed",
        "stop",
      ],
    },
  },

  "gemini-2.5-flash": {
    vertex: {
      name: "Google | google/gemini-2.5-flash",
      pricing: {
        prompt: 0.3,
        completion: 2.5,
        image: 0.001238,
        cacheRead: 0.075,
        cacheWrite: 0.3833,
      },
      contextLength: 1048576,
      maxCompletionTokens: 65535,
      supportedParameters: [
        "tools",
        "tool_choice",
        "reasoning",
        "include_reasoning",
        "response_format",
        "max_tokens",
        "temperature",
        "top_p",
        "seed",
        "stop",
      ],
    },
    "google-ai-studio": {
      name: "Google AI Studio | google/gemini-2.5-flash",
      pricing: {
        prompt: 0.3,
        completion: 2.5,
        image: 0.0012384,
        cacheRead: 0.075,
        cacheWrite: 0.3833,
      },
      contextLength: 1048576,
      maxCompletionTokens: 65535,
      supportedParameters: [
        "tools",
        "tool_choice",
        "reasoning",
        "include_reasoning",
        "response_format",
        "max_tokens",
        "temperature",
        "top_p",
        "seed",
        "stop",
      ],
    },
  },

  "gemini-2.5-pro": {
    vertex: {
      name: "Google | google/gemini-2.5-pro",
      pricing: {
        prompt: 1.25,
        completion: 10,
        image: 0.00516,
        cacheRead: 0.31,
        cacheWrite: 1.625,
      },
      contextLength: 1048576,
      maxCompletionTokens: 65536,
      supportedParameters: [
        "tools",
        "tool_choice",
        "reasoning",
        "include_reasoning",
        "response_format",
        "max_tokens",
        "temperature",
        "top_p",
        "seed",
        "stop",
      ],
    },
    "google-ai-studio": {
      name: "Google AI Studio | google/gemini-2.5-pro",
      pricing: {
        prompt: 1.25,
        completion: 10,
        image: 0.00516,
        cacheRead: 0.31,
        cacheWrite: 1.625,
      },
      contextLength: 1048576,
      maxCompletionTokens: 65536,
      supportedParameters: [
        "tools",
        "tool_choice",
        "reasoning",
        "include_reasoning",
        "response_format",
        "max_tokens",
        "temperature",
        "top_p",
        "seed",
        "stop",
      ],
    },
  },

  "gemini-2.5-pro-preview": {
    vertex: {
      name: "Google | google/gemini-2.5-pro",
      pricing: {
        prompt: 1.25,
        completion: 10,
        image: 0.00516,
        cacheRead: 0.31,
        cacheWrite: 1.625,
      },
      contextLength: 1048576,
      maxCompletionTokens: 65536,
      supportedParameters: [
        "tools",
        "tool_choice",
        "reasoning",
        "include_reasoning",
        "response_format",
        "max_tokens",
        "temperature",
        "top_p",
        "seed",
        "stop",
      ],
    },
    "google-ai-studio": {
      name: "Google AI Studio | google/gemini-2.5-pro",
      pricing: {
        prompt: 1.25,
        completion: 10,
        image: 0.00516,
        cacheRead: 0.31,
        cacheWrite: 1.625,
      },
      contextLength: 1048576,
      maxCompletionTokens: 65536,
      supportedParameters: [
        "tools",
        "tool_choice",
        "reasoning",
        "include_reasoning",
        "response_format",
        "max_tokens",
        "temperature",
        "top_p",
        "seed",
        "stop",
      ],
    },
  },

  "gemini-2.5-pro-preview-05-06": {
    vertex: {
      name: "Google | google/gemini-2.5-pro",
      pricing: {
        prompt: 1.25,
        completion: 10,
        image: 0.00516,
        cacheRead: 0.31,
        cacheWrite: 1.625,
      },
      contextLength: 1048576,
      maxCompletionTokens: 65536,
      supportedParameters: [
        "tools",
        "tool_choice",
        "reasoning",
        "include_reasoning",
        "response_format",
        "max_tokens",
        "temperature",
        "top_p",
        "seed",
        "stop",
      ],
    },
    "google-ai-studio": {
      name: "Google AI Studio | google/gemini-2.5-pro",
      pricing: {
        prompt: 1.25,
        completion: 10,
        image: 0.00516,
        cacheRead: 0.31,
        cacheWrite: 1.625,
      },
      contextLength: 1048576,
      maxCompletionTokens: 65536,
      supportedParameters: [
        "tools",
        "tool_choice",
        "reasoning",
        "include_reasoning",
        "response_format",
        "max_tokens",
        "temperature",
        "top_p",
        "seed",
        "stop",
      ],
    },
  },

  "gemini-2.5-pro-exp-03-25": {
    vertex: {
      name: "Google | google/gemini-2.5-pro-exp-03-25",
      pricing: {
        prompt: 0,
        completion: 0,
        cacheRead: null,
        cacheWrite: null,
      },
      contextLength: 1048576,
      maxCompletionTokens: 65535,
      supportedParameters: [
        "tools",
        "tool_choice",
        "max_tokens",
        "temperature",
        "top_p",
        "seed",
        "response_format",
        "stop",
      ],
    },
  },
} satisfies Record<GoogleModelName, ModelEndpointMap>;

export default googleEndpoints;
