/**
 * Google endpoint configurations
 */

import type { ModelEndpoint } from "../../types";

export const googleEndpoints: Record<string, ModelEndpoint[]> = {
  "gemini-2.5-flash-lite": [
    {
      name: "Google | google/gemini-2.5-flash-lite",
      provider: "vertex",
      tag: "google-vertex",
      status: 0,
      pricing: {
        prompt: 0.09999999999999999,
        completion: 0.39999999999999997,
        cacheRead: 0.024999999999999998,
        cacheWrite: 0.18330000000000002,
      },
      contextLength: 1048576,
      maxCompletionTokens: 65535,
      supportedParameters: [
        "tools",
        "tool_choice",
        "reasoning",
        "include_reasoning",
        "response_format",
        "max_tokens",
        "temperature",
        "top_p",
        "seed",
      ],
    },
    {
      name: "Google AI Studio | google/gemini-2.5-flash-lite",
      provider: "google-ai-studio",
      tag: "google-ai-studio",
      status: 0,
      pricing: {
        prompt: 0.09999999999999999,
        completion: 0.39999999999999997,
        cacheRead: 0.024999999999999998,
        cacheWrite: 0.18330000000000002,
      },
      contextLength: 1048576,
      maxCompletionTokens: 65535,
      supportedParameters: [
        "tools",
        "tool_choice",
        "reasoning",
        "include_reasoning",
        "response_format",
        "max_tokens",
        "temperature",
        "top_p",
        "seed",
      ],
    },
  ],

  "gemma-3n-e2b-it:free": [
    {
      name: "Google AI Studio | google/gemma-3n-e2b-it:free",
      provider: "google-ai-studio",
      tag: "google-ai-studio",
      status: 0,
      pricing: {
        prompt: 0,
        completion: 0,
        cacheRead: null,
        cacheWrite: null,
      },
      contextLength: 8192,
      maxCompletionTokens: 2048,
      supportedParameters: [
        "max_tokens",
        "temperature",
        "top_p",
        "seed",
        "response_format",
        "stop",
        "frequency_penalty",
        "presence_penalty",
      ],
    },
  ],

  "gemini-2.5-flash-lite-preview-06-17": [
    {
      name: "Google | google/gemini-2.5-flash-lite-preview-06-17",
      provider: "vertex",
      tag: "google-vertex",
      status: 0,
      pricing: {
        prompt: 0.09999999999999999,
        completion: 0.39999999999999997,
        cacheRead: 0.024999999999999998,
        cacheWrite: 0.18330000000000002,
      },
      contextLength: 1048576,
      maxCompletionTokens: 65535,
      supportedParameters: [
        "tools",
        "tool_choice",
        "reasoning",
        "include_reasoning",
        "response_format",
        "max_tokens",
        "temperature",
        "top_p",
        "seed",
        "stop",
      ],
    },
    {
      name: "Google AI Studio | google/gemini-2.5-flash-lite-preview-06-17",
      provider: "google-ai-studio",
      tag: "google-ai-studio",
      status: 0,
      pricing: {
        prompt: 0.09999999999999999,
        completion: 0.39999999999999997,
        cacheRead: 0.024999999999999998,
        cacheWrite: 0.18330000000000002,
      },
      contextLength: 1048576,
      maxCompletionTokens: 65535,
      supportedParameters: [
        "tools",
        "tool_choice",
        "reasoning",
        "include_reasoning",
        "response_format",
        "max_tokens",
        "temperature",
        "top_p",
        "seed",
        "stop",
      ],
    },
  ],

  "gemini-2.5-flash": [
    {
      name: "Google | google/gemini-2.5-flash",
      provider: "vertex",
      tag: "google-vertex/global",
      status: 0,
      pricing: {
        prompt: 0.3,
        completion: 2.5,
        image: 0.001238,
        cacheRead: 0.075,
        cacheWrite: 0.3833,
      },
      contextLength: 1048576,
      maxCompletionTokens: 65535,
      supportedParameters: [
        "tools",
        "tool_choice",
        "reasoning",
        "include_reasoning",
        "response_format",
        "max_tokens",
        "temperature",
        "top_p",
        "seed",
        "stop",
      ],
    },
    {
      name: "Google AI Studio | google/gemini-2.5-flash",
      provider: "google-ai-studio",
      tag: "google-ai-studio",
      status: 0,
      pricing: {
        prompt: 0.3,
        completion: 2.5,
        image: 0.0012384,
        cacheRead: 0.075,
        cacheWrite: 0.3833,
      },
      contextLength: 1048576,
      maxCompletionTokens: 65535,
      supportedParameters: [
        "tools",
        "tool_choice",
        "reasoning",
        "include_reasoning",
        "response_format",
        "max_tokens",
        "temperature",
        "top_p",
        "seed",
        "stop",
      ],
    },
    {
      name: "Google | google/gemini-2.5-flash",
      provider: "vertex",
      tag: "google-vertex",
      status: 0,
      pricing: {
        prompt: 0.3,
        completion: 2.5,
        image: 0.001238,
        cacheRead: 0.075,
        cacheWrite: 0.3833,
      },
      contextLength: 1048576,
      maxCompletionTokens: 65535,
      supportedParameters: [
        "tools",
        "tool_choice",
        "reasoning",
        "include_reasoning",
        "response_format",
        "max_tokens",
        "temperature",
        "top_p",
        "seed",
        "stop",
      ],
    },
  ],

  "gemini-2.5-pro": [
    {
      name: "Google | google/gemini-2.5-pro",
      provider: "vertex",
      tag: "google-vertex/global",
      status: 0,
      pricing: {
        prompt: 1.25,
        completion: 10,
        image: 0.00516,
        cacheRead: 0.31,
        cacheWrite: 1.625,
      },
      contextLength: 1048576,
      maxCompletionTokens: 65536,
      supportedParameters: [
        "tools",
        "tool_choice",
        "reasoning",
        "include_reasoning",
        "response_format",
        "max_tokens",
        "temperature",
        "top_p",
        "seed",
        "stop",
      ],
    },
    {
      name: "Google AI Studio | google/gemini-2.5-pro",
      provider: "google-ai-studio",
      tag: "google-ai-studio",
      pricing: {
        prompt: 1.25,
        completion: 10,
        image: 0.00516,
        cacheRead: 0.31,
        cacheWrite: 1.625,
      },
      contextLength: 1048576,
      maxCompletionTokens: 65536,
      supportedParameters: [
        "tools",
        "tool_choice",
        "reasoning",
        "include_reasoning",
        "response_format",
        "max_tokens",
        "temperature",
        "top_p",
        "seed",
        "stop",
      ],
    },
    {
      name: "Google | google/gemini-2.5-pro",
      provider: "vertex",
      tag: "google-vertex/us",
      status: 0,
      pricing: {
        prompt: 1.25,
        completion: 10,
        image: 0.00516,
        cacheRead: 0.31,
        cacheWrite: 1.625,
      },
      contextLength: 1048576,
      maxCompletionTokens: 65536,
      supportedParameters: [
        "tools",
        "tool_choice",
        "reasoning",
        "include_reasoning",
        "response_format",
        "max_tokens",
        "temperature",
        "top_p",
        "seed",
        "stop",
      ],
    },
  ],

  "gemini-2.5-pro-preview": [
    {
      name: "Google | google/gemini-2.5-pro",
      provider: "vertex",
      tag: "google-vertex/global",
      status: 0,
      pricing: {
        prompt: 1.25,
        completion: 10,
        image: 0.00516,
        cacheRead: 0.31,
        cacheWrite: 1.625,
      },
      contextLength: 1048576,
      maxCompletionTokens: 65536,
      supportedParameters: [
        "tools",
        "tool_choice",
        "reasoning",
        "include_reasoning",
        "response_format",
        "max_tokens",
        "temperature",
        "top_p",
        "seed",
        "stop",
      ],
    },
    {
      name: "Google AI Studio | google/gemini-2.5-pro",
      provider: "google-ai-studio",
      tag: "google-ai-studio",
      pricing: {
        prompt: 1.25,
        completion: 10,
        image: 0.00516,
        cacheRead: 0.31,
        cacheWrite: 1.625,
      },
      contextLength: 1048576,
      maxCompletionTokens: 65536,
      supportedParameters: [
        "tools",
        "tool_choice",
        "reasoning",
        "include_reasoning",
        "response_format",
        "max_tokens",
        "temperature",
        "top_p",
        "seed",
        "stop",
      ],
    },
    {
      name: "Google | google/gemini-2.5-pro",
      provider: "vertex",
      tag: "google-vertex/us",
      status: 0,
      pricing: {
        prompt: 1.25,
        completion: 10,
        image: 0.00516,
        cacheRead: 0.31,
        cacheWrite: 1.625,
      },
      contextLength: 1048576,
      maxCompletionTokens: 65536,
      supportedParameters: [
        "tools",
        "tool_choice",
        "reasoning",
        "include_reasoning",
        "response_format",
        "max_tokens",
        "temperature",
        "top_p",
        "seed",
        "stop",
      ],
    },
  ],

  "gemma-3n-e4b-it:free": [
    {
      name: "Google AI Studio | google/gemma-3n-e4b-it:free",
      provider: "google-ai-studio",
      tag: "google-ai-studio",
      status: 0,
      pricing: {
        prompt: 0,
        completion: 0,
        cacheRead: null,
        cacheWrite: null,
      },
      contextLength: 8192,
      maxCompletionTokens: 2048,
      supportedParameters: [
        "max_tokens",
        "temperature",
        "top_p",
        "seed",
        "response_format",
        "stop",
        "frequency_penalty",
        "presence_penalty",
      ],
    },
  ],

  "gemma-3n-e4b-it": [
    {
      name: "Together | google/gemma-3n-e4b-it",
      provider: "together",
      tag: "together",
      status: 0,
      pricing: {
        prompt: 0.02,
        completion: 0.04,
        cacheRead: null,
        cacheWrite: null,
      },
      contextLength: 32768,
      maxCompletionTokens: null,
      supportedParameters: [
        "max_tokens",
        "temperature",
        "top_p",
        "stop",
        "frequency_penalty",
        "presence_penalty",
        "top_k",
        "repetition_penalty",
      ],
    },
  ],

  "gemini-2.5-pro-preview-05-06": [
    {
      name: "Google | google/gemini-2.5-pro",
      provider: "vertex",
      tag: "google-vertex/global",
      status: 0,
      pricing: {
        prompt: 1.25,
        completion: 10,
        image: 0.00516,
        cacheRead: 0.31,
        cacheWrite: 1.625,
      },
      contextLength: 1048576,
      maxCompletionTokens: 65536,
      supportedParameters: [
        "tools",
        "tool_choice",
        "reasoning",
        "include_reasoning",
        "response_format",
        "max_tokens",
        "temperature",
        "top_p",
        "seed",
        "stop",
      ],
    },
    {
      name: "Google AI Studio | google/gemini-2.5-pro",
      provider: "google-ai-studio",
      tag: "google-ai-studio",
      pricing: {
        prompt: 1.25,
        completion: 10,
        image: 0.00516,
        cacheRead: 0.31,
        cacheWrite: 1.625,
      },
      contextLength: 1048576,
      maxCompletionTokens: 65536,
      supportedParameters: [
        "tools",
        "tool_choice",
        "reasoning",
        "include_reasoning",
        "response_format",
        "max_tokens",
        "temperature",
        "top_p",
        "seed",
        "stop",
      ],
    },
    {
      name: "Google | google/gemini-2.5-pro",
      provider: "vertex",
      tag: "google-vertex/us",
      status: 0,
      pricing: {
        prompt: 1.25,
        completion: 10,
        image: 0.00516,
        cacheRead: 0.31,
        cacheWrite: 1.625,
      },
      contextLength: 1048576,
      maxCompletionTokens: 65536,
      supportedParameters: [
        "tools",
        "tool_choice",
        "reasoning",
        "include_reasoning",
        "response_format",
        "max_tokens",
        "temperature",
        "top_p",
        "seed",
        "stop",
      ],
    },
  ],

  "gemini-2.5-pro-exp-03-25": [
    {
      name: "Google | google/gemini-2.5-pro-exp-03-25",
      provider: "vertex",
      tag: "google-vertex",
      status: 0,
      pricing: {
        prompt: 0,
        completion: 0,
        cacheRead: null,
        cacheWrite: null,
      },
      contextLength: 1048576,
      maxCompletionTokens: 65535,
      supportedParameters: [
        "tools",
        "tool_choice",
        "max_tokens",
        "temperature",
        "top_p",
        "seed",
        "response_format",
        "stop",
      ],
    },
  ],

  "gemma-3-4b-it:free": [
    {
      name: "Google AI Studio | google/gemma-3-4b-it:free",
      provider: "google-ai-studio",
      tag: "google-ai-studio",
      status: 0,
      pricing: {
        prompt: 0,
        completion: 0,
        cacheRead: null,
        cacheWrite: null,
      },
      contextLength: 32768,
      maxCompletionTokens: 8192,
      supportedParameters: [
        "max_tokens",
        "temperature",
        "top_p",
        "seed",
        "response_format",
      ],
    },
  ],

  "gemma-3-4b-it": [
    {
      name: "NextBit | google/gemma-3-4b-it",
      provider: "nextbit",
      tag: "nextbit/fp8",
      pricing: {
        prompt: 0.02,
        completion: 0.04,
        cacheRead: null,
        cacheWrite: null,
      },
      contextLength: 131072,
      maxCompletionTokens: null,
      supportedParameters: [
        "max_tokens",
        "temperature",
        "top_p",
        "stop",
        "frequency_penalty",
        "presence_penalty",
        "response_format",
      ],
    },
    {
      name: "DeepInfra | google/gemma-3-4b-it",
      provider: "deepinfra",
      tag: "deepinfra/bf16",
      status: 0,
      pricing: {
        prompt: 0.02,
        completion: 0.04,
        cacheRead: null,
        cacheWrite: null,
      },
      contextLength: 131072,
      maxCompletionTokens: null,
      supportedParameters: [
        "max_tokens",
        "temperature",
        "top_p",
        "stop",
        "frequency_penalty",
        "presence_penalty",
        "repetition_penalty",
        "top_k",
        "seed",
        "response_format",
      ],
    },
  ],

  "gemma-3-12b-it:free": [
    {
      name: "Chutes | google/gemma-3-12b-it:free",
      provider: "chutes",
      tag: "chutes/bf16",
      pricing: {
        prompt: 0,
        completion: 0,
        cacheRead: null,
        cacheWrite: null,
      },
      contextLength: 96000,
      maxCompletionTokens: 8192,
      supportedParameters: [
        "max_tokens",
        "temperature",
        "top_p",
        "stop",
        "frequency_penalty",
        "presence_penalty",
        "seed",
        "top_k",
        "repetition_penalty",
      ],
    },
    {
      name: "Google AI Studio | google/gemma-3-12b-it:free",
      provider: "google-ai-studio",
      tag: "google-ai-studio",
      status: 0,
      pricing: {
        prompt: 0,
        completion: 0,
        cacheRead: null,
        cacheWrite: null,
      },
      contextLength: 32768,
      maxCompletionTokens: 8192,
      supportedParameters: [
        "max_tokens",
        "temperature",
        "top_p",
        "seed",
        "response_format",
      ],
    },
  ],

  "gemma-3-12b-it": [
    {
      name: "Chutes | google/gemma-3-12b-it",
      provider: "chutes",
      tag: "chutes/bf16",
      status: 0,
      pricing: {
        prompt: 0.0481286,
        completion: 0.192608,
        cacheRead: null,
        cacheWrite: null,
      },
      contextLength: 96000,
      maxCompletionTokens: 8192,
      supportedParameters: [
        "max_tokens",
        "temperature",
        "top_p",
        "stop",
        "frequency_penalty",
        "presence_penalty",
        "seed",
        "top_k",
        "repetition_penalty",
      ],
    },
    {
      name: "DeepInfra | google/gemma-3-12b-it",
      provider: "deepinfra",
      tag: "deepinfra/bf16",
      status: 0,
      pricing: {
        prompt: 0.049999999999999996,
        completion: 0.09999999999999999,
        cacheRead: null,
        cacheWrite: null,
      },
      contextLength: 131072,
      maxCompletionTokens: null,
      supportedParameters: [
        "max_tokens",
        "temperature",
        "top_p",
        "stop",
        "frequency_penalty",
        "presence_penalty",
        "repetition_penalty",
        "top_k",
        "seed",
        "response_format",
      ],
    },
    {
      name: "Cloudflare | google/gemma-3-12b-it",
      provider: "cloudflare",
      tag: "cloudflare",
      status: 0,
      pricing: {
        prompt: 0.35,
        completion: 0.56,
        cacheRead: null,
        cacheWrite: null,
      },
      contextLength: 80000,
      maxCompletionTokens: null,
      supportedParameters: [
        "max_tokens",
        "temperature",
        "top_p",
        "top_k",
        "seed",
        "repetition_penalty",
        "frequency_penalty",
        "presence_penalty",
      ],
    },
  ],

  "gemma-3-27b-it:free": [
    {
      name: "Chutes | google/gemma-3-27b-it:free",
      provider: "chutes",
      tag: "chutes/bf16",
      status: 0,
      pricing: {
        prompt: 0,
        completion: 0,
        cacheRead: null,
        cacheWrite: null,
      },
      contextLength: 96000,
      maxCompletionTokens: 8192,
      supportedParameters: [
        "max_tokens",
        "temperature",
        "top_p",
        "stop",
        "frequency_penalty",
        "presence_penalty",
        "seed",
        "top_k",
        "repetition_penalty",
      ],
    },
    {
      name: "Google AI Studio | google/gemma-3-27b-it:free",
      provider: "google-ai-studio",
      tag: "google-ai-studio",
      status: 0,
      pricing: {
        prompt: 0,
        completion: 0,
        cacheRead: null,
        cacheWrite: null,
      },
      contextLength: 131072,
      maxCompletionTokens: 8192,
      supportedParameters: [
        "max_tokens",
        "temperature",
        "top_p",
        "seed",
        "response_format",
      ],
    },
  ],

  "gemma-3-27b-it": [
    {
      name: "Chutes | google/gemma-3-27b-it",
      provider: "chutes",
      tag: "chutes/bf16",
      status: 0,
      pricing: {
        prompt: 0.0666396,
        completion: 0.26668800000000004,
        cacheRead: null,
        cacheWrite: null,
      },
      contextLength: 96000,
      maxCompletionTokens: 8192,
      supportedParameters: [
        "max_tokens",
        "temperature",
        "top_p",
        "stop",
        "frequency_penalty",
        "presence_penalty",
        "seed",
        "top_k",
        "repetition_penalty",
      ],
    },
    {
      name: "DeepInfra | google/gemma-3-27b-it",
      provider: "deepinfra",
      tag: "deepinfra/bf16",
      status: 0,
      pricing: {
        prompt: 0.09,
        completion: 0.16999999999999998,
        image: 2.56e-5,
        cacheRead: null,
        cacheWrite: null,
      },
      contextLength: 131072,
      maxCompletionTokens: 16384,
      supportedParameters: [
        "max_tokens",
        "temperature",
        "top_p",
        "stop",
        "frequency_penalty",
        "presence_penalty",
        "repetition_penalty",
        "top_k",
        "seed",
        "response_format",
      ],
    },
    {
      name: "Nebius | google/gemma-3-27b-it",
      provider: "nebius",
      tag: "nebius/fp8",
      status: 0,
      pricing: {
        prompt: 0.09999999999999999,
        completion: 0.3,
        cacheRead: null,
        cacheWrite: null,
      },
      contextLength: 110000,
      maxCompletionTokens: null,
      supportedParameters: [
        "max_tokens",
        "temperature",
        "top_p",
        "stop",
        "frequency_penalty",
        "presence_penalty",
        "seed",
        "top_k",
      ],
    },
    {
      name: "Parasail | google/gemma-3-27b-it",
      provider: "parasail",
      tag: "parasail/fp8",
      status: 0,
      pricing: {
        prompt: 0.09999999999999999,
        completion: 0.39999999999999997,
        cacheRead: null,
        cacheWrite: null,
      },
      contextLength: 131072,
      maxCompletionTokens: 131072,
      supportedParameters: [
        "max_tokens",
        "temperature",
        "top_p",
        "frequency_penalty",
        "presence_penalty",
        "repetition_penalty",
        "seed",
        "stop",
        "top_k",
      ],
    },
    {
      name: "Novita | google/gemma-3-27b-it",
      provider: "novita",
      tag: "novita",
      status: 0,
      pricing: {
        prompt: 0.119,
        completion: 0.19999999999999998,
        cacheRead: null,
        cacheWrite: null,
      },
      contextLength: 32000,
      maxCompletionTokens: 32000,
      supportedParameters: [
        "max_tokens",
        "temperature",
        "top_p",
        "stop",
        "frequency_penalty",
        "presence_penalty",
        "seed",
        "top_k",
        "repetition_penalty",
      ],
    },
  ],

  "gemini-2.0-flash-lite-001": [
    {
      name: "Google | google/gemini-2.0-flash-lite-001",
      provider: "vertex",
      tag: "google-vertex",
      status: 0,
      pricing: {
        prompt: 0.075,
        completion: 0.3,
        cacheRead: null,
        cacheWrite: null,
      },
      contextLength: 1048576,
      maxCompletionTokens: 8192,
      supportedParameters: [
        "tools",
        "tool_choice",
        "max_tokens",
        "temperature",
        "top_p",
        "seed",
        "response_format",
        "stop",
      ],
    },
    {
      name: "Google AI Studio | google/gemini-2.0-flash-lite-001",
      provider: "google-ai-studio",
      tag: "google-ai-studio",
      status: 0,
      pricing: {
        prompt: 0.075,
        completion: 0.3,
        cacheRead: null,
        cacheWrite: null,
      },
      contextLength: 1048576,
      maxCompletionTokens: 8192,
      supportedParameters: [
        "tools",
        "tool_choice",
        "max_tokens",
        "temperature",
        "top_p",
        "seed",
        "response_format",
        "stop",
      ],
    },
  ],

  "gemini-2.0-flash-001": [
    {
      name: "Google AI Studio | google/gemini-2.0-flash-001",
      provider: "google-ai-studio",
      tag: "google-ai-studio",
      status: 0,
      pricing: {
        prompt: 0.09999999999999999,
        completion: 0.39999999999999997,
        image: 2.58e-5,
        cacheRead: 0.024999999999999998,
        cacheWrite: 0.18330000000000002,
      },
      contextLength: 1048576,
      maxCompletionTokens: 8192,
      supportedParameters: [
        "tools",
        "tool_choice",
        "max_tokens",
        "temperature",
        "top_p",
        "seed",
        "response_format",
        "stop",
      ],
    },
    {
      name: "Google | google/gemini-2.0-flash-001",
      provider: "vertex",
      tag: "google-vertex",
      status: 0,
      pricing: {
        prompt: 0.15,
        completion: 0.6,
        image: 3.87e-5,
        cacheRead: 0.0375,
        cacheWrite: 0.2333,
      },
      contextLength: 1000000,
      maxCompletionTokens: 8192,
      supportedParameters: [
        "tools",
        "tool_choice",
        "max_tokens",
        "temperature",
        "top_p",
        "seed",
        "response_format",
        "stop",
      ],
    },
  ],

  "gemini-2.0-flash-exp:free": [
    {
      name: "Google | google/gemini-2.0-flash-exp:free",
      provider: "vertex",
      tag: "google-vertex",
      status: 0,
      pricing: {
        prompt: 0,
        completion: 0,
        cacheRead: null,
        cacheWrite: null,
      },
      contextLength: 1048576,
      maxCompletionTokens: 8192,
      supportedParameters: [
        "tools",
        "tool_choice",
        "max_tokens",
        "temperature",
        "top_p",
        "seed",
        "response_format",
        "stop",
      ],
    },
    {
      name: "Google AI Studio | google/gemini-2.0-flash-exp:free",
      provider: "google-ai-studio",
      tag: "google-ai-studio",
      status: 0,
      pricing: {
        prompt: 0,
        completion: 0,
        cacheRead: null,
        cacheWrite: null,
      },
      contextLength: 1048576,
      maxCompletionTokens: 8192,
      supportedParameters: [
        "tools",
        "tool_choice",
        "max_tokens",
        "temperature",
        "top_p",
        "seed",
        "response_format",
        "stop",
      ],
    },
  ],

  "gemini-flash-1.5-8b": [
    {
      name: "Google AI Studio | google/gemini-flash-1.5-8b",
      provider: "google-ai-studio",
      tag: "google-ai-studio",
      status: 0,
      pricing: {
        prompt: 0.0375,
        completion: 0.15,
        cacheRead: 0.01,
        cacheWrite: 0.0583,
      },
      contextLength: 1000000,
      maxCompletionTokens: 8192,
      supportedParameters: [
        "tools",
        "tool_choice",
        "max_tokens",
        "temperature",
        "top_p",
        "seed",
        "response_format",
        "stop",
        "frequency_penalty",
        "presence_penalty",
      ],
    },
  ],

  "gemma-2-27b-it": [
    {
      name: "NextBit | google/gemma-2-27b-it",
      provider: "nextbit",
      tag: "nextbit/int4",
      status: 0,
      pricing: {
        prompt: 0.65,
        completion: 0.65,
        cacheRead: null,
        cacheWrite: null,
      },
      contextLength: 8192,
      maxCompletionTokens: null,
      supportedParameters: [
        "max_tokens",
        "temperature",
        "top_p",
        "stop",
        "frequency_penalty",
        "presence_penalty",
        "response_format",
      ],
    },
    {
      name: "Together | google/gemma-2-27b-it",
      provider: "together",
      tag: "together",
      status: 0,
      pricing: {
        prompt: 0.7999999999999999,
        completion: 0.7999999999999999,
        cacheRead: null,
        cacheWrite: null,
      },
      contextLength: 8192,
      maxCompletionTokens: 2048,
      supportedParameters: [
        "max_tokens",
        "temperature",
        "top_p",
        "stop",
        "frequency_penalty",
        "presence_penalty",
        "top_k",
        "repetition_penalty",
      ],
    },
  ],

  "gemma-2-9b-it:free": [
    {
      name: "Chutes | google/gemma-2-9b-it:free",
      provider: "chutes",
      tag: "chutes",
      status: 0,
      pricing: {
        prompt: 0,
        completion: 0,
        cacheRead: null,
        cacheWrite: null,
      },
      contextLength: 8192,
      maxCompletionTokens: 8192,
      supportedParameters: [
        "max_tokens",
        "temperature",
        "top_p",
        "stop",
        "frequency_penalty",
        "presence_penalty",
        "seed",
        "top_k",
        "repetition_penalty",
      ],
    },
  ],

  "gemma-2-9b-it": [
    {
      name: "Chutes | google/gemma-2-9b-it",
      provider: "chutes",
      tag: "chutes",
      status: 0,
      pricing: {
        prompt: 0.01,
        completion: 0.0100008,
        cacheRead: null,
        cacheWrite: null,
      },
      contextLength: 8192,
      maxCompletionTokens: 8192,
      supportedParameters: [
        "max_tokens",
        "temperature",
        "top_p",
        "stop",
        "frequency_penalty",
        "presence_penalty",
        "seed",
        "top_k",
        "repetition_penalty",
      ],
    },
    {
      name: "Groq | google/gemma-2-9b-it",
      provider: "groq",
      tag: "groq",
      status: 0,
      pricing: {
        prompt: 0.19999999999999998,
        completion: 0.19999999999999998,
        cacheRead: null,
        cacheWrite: null,
      },
      contextLength: 8192,
      maxCompletionTokens: 8192,
      supportedParameters: [
        "max_tokens",
        "temperature",
        "top_p",
        "stop",
        "frequency_penalty",
        "presence_penalty",
        "seed",
        "response_format",
      ],
    },
  ],

  "gemini-flash-1.5": [
    {
      name: "Google | google/gemini-flash-1.5",
      provider: "vertex",
      tag: "google-vertex",
      status: 0,
      pricing: {
        prompt: 0.075,
        completion: 0.3,
        image: 4e-5,
        cacheRead: 0.01875,
        cacheWrite: 0.1583,
      },
      contextLength: 1000000,
      maxCompletionTokens: 8192,
      supportedParameters: [
        "tools",
        "tool_choice",
        "max_tokens",
        "temperature",
        "top_p",
        "seed",
        "response_format",
        "stop",
        "frequency_penalty",
        "presence_penalty",
      ],
    },
    {
      name: "Google AI Studio | google/gemini-flash-1.5",
      provider: "google-ai-studio",
      tag: "google-ai-studio",
      status: 0,
      pricing: {
        prompt: 0.075,
        completion: 0.3,
        cacheRead: 0.01875,
        cacheWrite: 0.1583,
      },
      contextLength: 1000000,
      maxCompletionTokens: 8192,
      supportedParameters: [
        "tools",
        "tool_choice",
        "max_tokens",
        "temperature",
        "top_p",
        "seed",
        "response_format",
        "stop",
        "frequency_penalty",
        "presence_penalty",
      ],
    },
  ],

  "gemini-pro-1.5": [
    {
      name: "Google | google/gemini-pro-1.5",
      provider: "vertex",
      tag: "google-vertex",
      status: 0,
      pricing: {
        prompt: 1.25,
        completion: 5,
        image: 0.0006575,
        cacheRead: null,
        cacheWrite: null,
      },
      contextLength: 2000000,
      maxCompletionTokens: 8192,
      supportedParameters: [
        "tools",
        "tool_choice",
        "max_tokens",
        "temperature",
        "top_p",
        "seed",
        "response_format",
        "stop",
        "frequency_penalty",
        "presence_penalty",
      ],
    },
    {
      name: "Google AI Studio | google/gemini-pro-1.5",
      provider: "google-ai-studio",
      tag: "google-ai-studio",
      status: 0,
      pricing: {
        prompt: 1.25,
        completion: 5,
        cacheRead: 0.625,
        cacheWrite: 2.875,
      },
      contextLength: 2000000,
      maxCompletionTokens: 8192,
      supportedParameters: [
        "tools",
        "tool_choice",
        "max_tokens",
        "temperature",
        "top_p",
        "seed",
        "response_format",
        "stop",
        "frequency_penalty",
        "presence_penalty",
      ],
    },
  ],
};

export default googleEndpoints;
