/**
 * HQL Vocabulary Whitelist
 *
 * Comprehensive whitelist of allowed ClickHouse SQL constructs.
 * All function/operator names are stored in lowercase for case-insensitive matching.
 *
 * Source: https://clickhouse.com/docs/sql-reference/functions
 */

// ============================================================
// AGGREGATE FUNCTIONS (from ClickHouse docs)
// ============================================================
export const ALLOWED_AGGREGATE_FUNCTIONS = new Set([
  // Basic aggregates
  "count",
  "sum",
  "avg",
  "min",
  "max",
  "any",
  "anyheavy",
  "anylast",
  // Weighted/statistical
  "avgweighted",
  "median",
  "stddevpop",
  "stddevpopstable",
  "stddevsamp",
  "stddevsampstable",
  "varpop",
  "varpopstable",
  "varsamp",
  "varsampstable",
  "covarpop",
  "covarpopmstable",
  "covarsamp",
  "covarsampstable",
  "corr",
  "corrmatrix",
  "corrstable",
  // Quantiles
  "quantile",
  "quantiles",
  "quantilebfloat16",
  "quantiledd",
  "quantiledeterministic",
  "quantileexact",
  "quantileexactweighted",
  "quantileexactweightedinterpolated",
  "quantilegk",
  "quantileinterpolatedweighted",
  "quantiletdigest",
  "quantiletdigestweighted",
  "quantiletiming",
  "quantiletimingweighted",
  "quantileprometheushistogram",
  // Unique counting
  "uniq",
  "uniqcombined",
  "uniqcombined64",
  "uniqexact",
  "uniqhll12",
  "uniqtheta",
  // Group arrays
  "grouparray",
  "grouparrayarray",
  "grouparrayinsertat",
  "grouparrayintersect",
  "grouparraylast",
  "grouparraymovingavg",
  "grouparraymovingsum",
  "grouparraysample",
  "grouparraysorted",
  "groupuniqarray",
  "groupconcat",
  // ArgMin/Max
  "argmin",
  "argmax",
  "argandmin",
  "argandmax",
  // Bit operations
  "groupbitand",
  "groupbitor",
  "groupbitxor",
  "groupbitmap",
  "groupbitmapand",
  "groupbitmapor",
  "groupbitmapxor",
  // Statistical tests
  "kolmogorovsmirnovtest",
  "mannwhitneyutest",
  "studentttest",
  "studentttestonesample",
  "welchttest",
  "meanztest",
  "analysisofvariance",
  // Maps
  "summap",
  "minmap",
  "maxmap",
  "summapwithoverflow",
  "summapfiltered",
  // Time series
  "deltasum",
  "deltasumtimestamp",
  "exponentialmovingaverage",
  "exponentialtimedecayedavg",
  "exponentialtimedecayedcount",
  "exponentialtimedecayedmax",
  "exponentialtimedecayedsum",
  "timeseriesgrouparray",
  "timeseriesdeltatogrid",
  "timeseriesinstantdeltatogrid",
  "timeseriesinstantratetogrid",
  "timeserieslasttwosamples",
  "timeseriesratetogrid",
  "timeseriesresampletogridwithstaleness",
  "timeseriesderivtogrid",
  "timeseriespredictlineartogrid",
  "timeserieschangestogrid",
  "timeseriesresetstogrid",
  // Other
  "first_value",
  "last_value",
  "topk",
  "topkweighted",
  "approx_top_k",
  "approx_top_sum",
  "entropy",
  "kurtpop",
  "kurtsamp",
  "skewpop",
  "skewsamp",
  "sparkbar",
  "simplelinearregression",
  "stochasticlinearregression",
  "stochasticlogisticregression",
  "sumcount",
  "sumkahan",
  "sumwithoverflow",
  "boundingratio",
  "intervallengthsum",
  "rankcorr",
  "singlevalueornull",
  "categoricalinformationvalue",
  "contingency",
  "cramersv",
  "cramersvbiascorrected",
  "theilsu",
  "maxintersections",
  "maxintersectionsposition",
  "largesttriangularthreebuckets",
  "flamegraph",
  "estimatecompressionratio",
  "distinctdynamictypes",
  "distinctjsonpaths",
]);

// ============================================================
// DATE/TIME FUNCTIONS
// ============================================================
export const ALLOWED_DATE_FUNCTIONS = new Set([
  // Current time
  "now",
  "now64",
  "today",
  "yesterday",
  "utctimestamp",
  "utc_timestamp",
  "current_timestamp",
  "nowinblock",
  "nowinblock64",
  // Conversions
  "todate",
  "todate32",
  "todatetime",
  "todatetime64",
  "makedate",
  "makedate32",
  "makedatetime",
  "makedatetime64",
  "yyyymmddtodate",
  "yyyymmddtodate32",
  "yyyymmddhhmmsstodatetime",
  "yyyymmddhhmmsstodatetime64",
  // Extraction
  "toyear",
  "tomonth",
  "todayofmonth",
  "todayofweek",
  "todayofyear",
  "tohour",
  "tominute",
  "tosecond",
  "tomillisecond",
  "tomicrosecond",
  "tonanosecond",
  "toquarter",
  "toweek",
  "toyearweek",
  "toiso8601week",
  "torelativeyearnum",
  "torelativemonthnum",
  "torelativeweeknum",
  "torelativedaynum",
  "torelativehournum",
  "torelativeminutenum",
  "torelativesecondnum",
  "datename",
  "monthname",
  // Start of periods
  "tostartofday",
  "tostartofweek",
  "tostartofmonth",
  "tostartofquarter",
  "tostartofyear",
  "tostartofhour",
  "tostartofminute",
  "tostartofsecond",
  "tostartofmillisecond",
  "tostartofmicrosecond",
  "tostartofnanosecond",
  "tostartofinterval",
  "tostartoffiveminutes",
  "tostartoffifteenminutes",
  "tostartoftenminutes",
  "tomonday",
  "tolastdayofmonth",
  "tolastdayofweek",
  "totime",
  "totimezone",
  "totimezonewithoffset",
  // Arithmetic
  "addyears",
  "addmonths",
  "addweeks",
  "adddays",
  "addhours",
  "addminutes",
  "addseconds",
  "addmilliseconds",
  "addmicroseconds",
  "addnanoseconds",
  "addquarters",
  "addinterval",
  "addtupleofintervals",
  "subtractyears",
  "subtractmonths",
  "subtractweeks",
  "subtractdays",
  "subtracthours",
  "subtractminutes",
  "subtractseconds",
  "subtractmilliseconds",
  "subtractmicroseconds",
  "subtractnanoseconds",
  "subtractquarters",
  "subtractinterval",
  "dateadd",
  "datesub",
  "date_add",
  "date_sub",
  "adddate",
  "subdate",
  // Change functions
  "changeyear",
  "changemonth",
  "changeday",
  "changehour",
  "changeminute",
  "changesecond",
  // Diff/comparison
  "datediff",
  "date_diff",
  "timestampdiff",
  "timestamp_diff",
  "age",
  // Formatting
  "formatdatetime",
  "date_format",
  "formatdatetimeinjodasyntax",
  "parsedatetime",
  "parsedatetime32besteffert",
  "parsedatetime32besteffertornull",
  "parsedatetime32besteffertorzero",
  "parsedatetimebesteffert",
  "parsedatetimebesteffertornull",
  "parsedatetimebesteffertorzero",
  "parsedatetimebesteffort",
  "parsedatetimebesteffortornull",
  "parsedatetimebesteffortorzero",
  "parsedatetime64besteffert",
  "parsedatetime64besteffertornull",
  "parsedatetime64besteffertorzero",
  "parsedatetime64besteffort",
  "parsedatetime64besteffortornull",
  "parsedatetime64besteffortorzero",
  // Unix timestamps
  "tounixtimestamp",
  "tounixtimestamp64milliseconds",
  "tounixtimestamp64microseconds",
  "tounixtimestamp64nanoseconds",
  "fromunixtimestamp",
  "fromunixtimestamp64milliseconds",
  "fromunixtimestamp64microseconds",
  "fromunixtimestamp64nanoseconds",
  "from_unixtime",
  "fromunixtimestampinjodasyntax",
  // Truncation
  "datetrunc",
  "date_trunc",
  "timestamptrunc",
  // Modified Julian Day
  "frommodifiedjulianday",
  "frommodifiedjuliandayornull",
  "tomodifiedjulianday",
  "tomodifiedjuliandayornull",
  // Days since year zero
  "fromdayssinceyearzero",
  "fromdayssinceyearzero32",
  "from_days",
  "todayssinceyearzero",
  "todayssinceyearzero32",
  "to_days",
  // UTC conversion
  "fromutctimestamp",
  "from_utc_timestamp",
  "toutctimestamp",
  "to_utc_timestamp",
  // Misc
  "timezoneof",
  "timezoneoffset",
  "servertimezone",
  "servertimezone",
  "timeslot",
  "timeslots",
]);

// ============================================================
// STRING FUNCTIONS
// ============================================================
export const ALLOWED_STRING_FUNCTIONS = new Set([
  // Basic
  "length",
  "lengthutf8",
  "char_length",
  "character_length",
  "empty",
  "notempty",
  "leftpad",
  "rightpad",
  "leftpadutf8",
  "rightpadutf8",
  "lower",
  "upper",
  "lowerutf8",
  "upperutf8",
  "initcap",
  "initcaputf8",
  // Substring
  "substring",
  "substringutf8",
  "substringindex",
  "substringindexutf8",
  "mid",
  "substr",
  "left",
  "right",
  "leftutf8",
  "rightutf8",
  "firstline",
  // Trimming
  "trim",
  "trimboth",
  "trimleft",
  "trimright",
  "ltrim",
  "rtrim",
  // Concatenation
  "concat",
  "concatassumeinjective",
  "concatwithseparator",
  "concatwithseparatorassumeinjective",
  // Search/position
  "position",
  "positionutf8",
  "positioncaseinsensitive",
  "positioncaseinsensitiveutf8",
  "locate",
  "multiposition",
  "multisearchfirstposition",
  "multisearchfirstpositioncaseinsensitive",
  "multisearchfirstpositionutf8",
  "multisearchfirstpositioncaseinsensitiveutf8",
  "multisearchfirstindex",
  "multisearchfirstindexcaseinsensitive",
  "multisearchfirstindexutf8",
  "multisearchfirstindexcaseinsensitiveutf8",
  "multisearchany",
  "multisearchanycaseinsensitive",
  "multisearchanyutf8",
  "multisearchanycaseinsensitiveutf8",
  "multimatchany",
  "multimatchanyindex",
  "multimatchallindices",
  "multifuzzymatchy",
  "multifuzzymatchanyindex",
  "multifuzzymatchallindices",
  // Replace
  "replace",
  "replaceall",
  "replaceone",
  "replaceregexpall",
  "replaceregexpone",
  "translate",
  "translateutf8",
  "regexpreplace",
  // Splitting
  "splitbychar",
  "splitbystring",
  "splitbyregexp",
  "splitbynongalpha",
  "splitbywhitespace",
  "arraystringconcat",
  "alphatokens",
  "tokens",
  "ngrams",
  "ngramsutf8",
  // Comparison
  "startswith",
  "endswith",
  "startswithcaseinsensitive",
  "endswithcaseinsensitive",
  "startswithutf8",
  "endswithutf8",
  "startswithcaseinsensitiveutf8",
  "endswithcaseinsensitiveutf8",
  "like",
  "notlike",
  "ilike",
  "notilike",
  "match",
  "comparesubstrings",
  // String distance/similarity
  "editdistance",
  "editdistanceutf8",
  "levenshteindistance",
  "dameraulevenshtein distance",
  "jarosimilarity",
  "jarowinklersimilarity",
  "bytehammingdistance",
  "stringjaccardindex",
  "stringjaccardindexutf8",
  // Misc
  "reverse",
  "reverseutf8",
  "repeat",
  "space",
  "ascii",
  "char",
  "format",
  "basename",
  "normalizequery",
  "normalizequerykeepnames",
  "normalizedqueryhash",
  "normalizedqueryhashnorm",
  "isvalidutf8",
  "isvalidascii",
  "tovalidutf8",
  "normalizeutf8nfc",
  "normalizeutf8nfd",
  "normalizeutf8nfkc",
  "normalizeutf8nfkd",
  "idnaencode",
  "idnadecode",
  "punycodeencode",
  "punycodedecode",
  "soundex",
  "regexpextract",
  "extract",
  "appendtrailingcharifabsent",
  "conv",
  "sparsegrams",
  "sparsegramsutf8",
  "sparsegramshashes",
  "sparsegramshashesutf8",
  "decodehtmlcomponent",
  "decodexmlcomponent",
  "encodexmlcomponent",
  "extracttextfromhtml",
  "stringbytesentropy",
  "stringbytesuniq",
  // Encoding
  "base64encode",
  "base64decode",
  "trybase64decode",
  "base64urlencode",
  "base64urldecode",
  "trybase64urldecode",
  "base32encode",
  "base32decode",
  "trybase32decode",
  "base58encode",
  "base58decode",
  "trybase58decode",
  "hex",
  "unhex",
  "bin",
  "unbin",
  // CRC/Hash (safe string operations)
  "crc32",
  "crc32ieee",
  "crc64",
]);

// ============================================================
// ARRAY FUNCTIONS
// ============================================================
export const ALLOWED_ARRAY_FUNCTIONS = new Set([
  "array",
  "emptyarraytosingle",
  "range",
  "arrayelement",
  "arrayelementornull",
  "arrayjoin",
  "arrayconcat",
  "arraypushback",
  "arraypushfront",
  "arraypopback",
  "arraypopfront",
  "arrayslice",
  "arrayresize",
  "arrayreverse",
  "arraysort",
  "arrayreversesort",
  "arraypartialsort",
  "arraypartialreversesort",
  "arrayshuffle",
  "arraypartialshuffle",
  "arrayuniq",
  "arraydistinct",
  "arraycompact",
  "arrayenumerate",
  "arrayenumerateuniq",
  "arrayenumeratedense",
  "arrayenumerateuniqranked",
  "arrayenumeratedenseranked",
  "arrayfilter",
  "arraymap",
  "arraytransform",
  "arrayfill",
  "arrayreversefill",
  "arraysplit",
  "arrayreversesplit",
  "arrayexists",
  "arrayall",
  "arrayfirst",
  "arraylast",
  "arrayfirstindex",
  "arraylastindex",
  "arrayfirstornull",
  "arraylastornull",
  "arraycount",
  "arraysum",
  "arrayavg",
  "arraymin",
  "arraymax",
  "arrayproduct",
  "arraycumsum",
  "arraycumsumnonnegative",
  "arraydifference",
  "arrayfold",
  "arrayreduce",
  "arrayreduceinranges",
  "has",
  "hasall",
  "hasany",
  "hassubstr",
  "indexof",
  "countequal",
  "arrayintersect",
  "arrayexcept",
  "arrayunion",
  "arrayjaccardindex",
  "arrayflatten",
  "flatten",
  "arrayremove",
  "array_remove",
  "arraywithconstant",
  "arrayaucpr",
  "arrayprauc",
  "arrayrocauc",
  "arrayauc",
  "arraynormalizedgini",
  "arrayrandomsample",
  "arraylevenshtein distance",
  "arraylevenshtein distanceweighted",
  "arraydotproduct",
  "arrayshingles",
]);

// ============================================================
// CONDITIONAL FUNCTIONS
// ============================================================
export const ALLOWED_CONDITIONAL_FUNCTIONS = new Set([
  "if",
  "multiif",
  "nullif",
  "coalesce",
  "ifnull",
  "nullifzero",
  "zeroifnull",
  "assumenotnull",
  "tonullable",
  "isnull",
  "isnotnull",
  "isnan",
  "isinfinite",
  "isfinite",
  "greatest",
  "least",
  "transform",
]);

// ============================================================
// TYPE CONVERSION FUNCTIONS
// ============================================================
export const ALLOWED_TYPE_FUNCTIONS = new Set([
  // Integer conversions
  "toint8",
  "toint16",
  "toint32",
  "toint64",
  "toint128",
  "toint256",
  "touint8",
  "touint16",
  "touint32",
  "touint64",
  "touint128",
  "touint256",
  // Float conversions
  "tofloat32",
  "tofloat64",
  // Decimal conversions
  "todecimal32",
  "todecimal64",
  "todecimal128",
  "todecimal256",
  // String conversions
  "tostring",
  "tofixedstring",
  // Other types
  "touuid",
  "toipv4",
  "toipv6",
  // Cast
  "cast",
  "accuratecast",
  "accuratecastornull",
  "accuratecastorzero",
  // OrNull variants
  "toint8ornull",
  "toint16ornull",
  "toint32ornull",
  "toint64ornull",
  "toint128ornull",
  "toint256ornull",
  "touint8ornull",
  "touint16ornull",
  "touint32ornull",
  "touint64ornull",
  "touint128ornull",
  "touint256ornull",
  "tofloat32ornull",
  "tofloat64ornull",
  "todecimal32ornull",
  "todecimal64ornull",
  "todecimal128ornull",
  "todecimal256ornull",
  "todateornull",
  "todatetimeornull",
  "todatetime64ornull",
  "touuidornull",
  // OrZero variants
  "toint8orzero",
  "toint16orzero",
  "toint32orzero",
  "toint64orzero",
  "toint128orzero",
  "toint256orzero",
  "touint8orzero",
  "touint16orzero",
  "touint32orzero",
  "touint64orzero",
  "touint128orzero",
  "touint256orzero",
  "tofloat32orzero",
  "tofloat64orzero",
  "todecimal32orzero",
  "todecimal64orzero",
  "todecimal128orzero",
  "todecimal256orzero",
  "todateorzero",
  "todatetimeorzero",
  "todatetime64orzero",
  // Type info
  "totypename",
  "totypenamed",
  "tocolumntypename",
  // Reinterpret
  "reinterpretasint8",
  "reinterpretasint16",
  "reinterpretasint32",
  "reinterpretasint64",
  "reinterpretasint128",
  "reinterpretasint256",
  "reinterpretasuint8",
  "reinterpretasuint16",
  "reinterpretasuint32",
  "reinterpretasuint64",
  "reinterpretasuint128",
  "reinterpretasuint256",
  "reinterpretasfloat32",
  "reinterpretasfloat64",
  "reinterpretasstring",
  "reinterpretasuuid",
  "reinterpretasdate",
  "reinterpretasdatetime",
  "reinterpret",
]);

// ============================================================
// MATH FUNCTIONS
// ============================================================
export const ALLOWED_MATH_FUNCTIONS = new Set([
  // Rounding
  "abs",
  "round",
  "roundbankers",
  "rounddown",
  "roundup",
  "roundtoexp2",
  "floor",
  "ceil",
  "ceiling",
  "trunc",
  "truncate",
  // Exponential/logarithmic
  "sqrt",
  "cbrt",
  "pow",
  "power",
  "exp",
  "exp2",
  "exp10",
  "log",
  "log2",
  "log10",
  "ln",
  "log1p",
  // Trigonometric
  "sin",
  "cos",
  "tan",
  "asin",
  "acos",
  "atan",
  "atan2",
  // Hyperbolic
  "sinh",
  "cosh",
  "tanh",
  "asinh",
  "acosh",
  "atanh",
  // Misc math
  "hypot",
  "degrees",
  "radians",
  "sign",
  "mod",
  "moduloorzero",
  "positivemodulo",
  "negate",
  // Arithmetic (for completeness)
  "plus",
  "minus",
  "multiply",
  "divide",
  "intdiv",
  "intdivorzero",
  // Constants
  "pi",
  "e",
  // Number theory
  "gcd",
  "lcm",
  // Factorials and combinations
  "factorial",
  // Error function
  "erf",
  "erfc",
  // Gamma
  "lgamma",
  "tgamma",
  // Bit operations (safe math)
  "bitand",
  "bitor",
  "bitxor",
  "bitnot",
  "bitshiftleft",
  "bitshiftright",
  "bitrotateleft",
  "bitrotateright",
  "bittest",
  "bitcount",
  "bithammingdistance",
]);

// ============================================================
// JSON FUNCTIONS
// ============================================================
export const ALLOWED_JSON_FUNCTIONS = new Set([
  // JSONExtract family
  "jsonextract",
  "jsonextractstring",
  "jsonextractint",
  "jsonextractuint",
  "jsonextractfloat",
  "jsonextractbool",
  "jsonextractarrayraw",
  "jsonextractraw",
  "jsonextractkeys",
  "jsonextractkeysandvalues",
  "jsonextractkeysandvaluesraw",
  // Case insensitive variants
  "jsonextractcaseinsensitive",
  "jsonextractstringcaseinsensitive",
  "jsonextractintcaseinsensitive",
  "jsonextractuintcaseinsensitive",
  "jsonextractfloatcaseinsensitive",
  "jsonextractboolcaseinsensitive",
  "jsonextractarrayrawcaseinsensitive",
  "jsonextractrawcaseinsensitive",
  "jsonextractkeyscaseinsensitive",
  "jsonextractkeysandvaluescaseinsensitive",
  "jsonextractkeysandvaluesrawcaseinsensitive",
  // Simple JSON
  "simplejsonextractstring",
  "simplejsonextractint",
  "simplejsonextractuint",
  "simplejsonextractfloat",
  "simplejsonextractbool",
  "simplejsonextractraw",
  "simplejsonhas",
  // Visitor param aliases
  "visitparamextractstring",
  "visitparamextractint",
  "visitparamextractuint",
  "visitparamextractfloat",
  "visitparamextractbool",
  "visitparamextractraw",
  "visitparamhas",
  // Utility
  "jsonhas",
  "jsonlength",
  "jsontype",
  "jsonarraylength",
  "isvalidjson",
  "json_value",
  "json_query",
  "json_exists",
  "tojsonstring",
  // Path functions
  "jsonallpaths",
  "jsonallpathswithtypes",
  "jsondynamicpaths",
  "jsondynamicpathswithtypes",
  "jsonshareddatapaths",
  "jsonshareddatapathswithtypes",
  "jsonmergepatch",
  // Dynamic type functions
  "dynamicelement",
  "dynamictype",
  "isdynamicelementinshareddata",
]);

// ============================================================
// UUID FUNCTIONS
// ============================================================
export const ALLOWED_UUID_FUNCTIONS = new Set([
  "generateuuidv4",
  "generateuuidv7",
  "empty",
  "notempty",
  "touuid",
  "touuidornull",
  "uuidstringtonum",
  "uuidnumtostring",
  "serveruuid",
]);

// ============================================================
// IP ADDRESS FUNCTIONS
// ============================================================
export const ALLOWED_IP_FUNCTIONS = new Set([
  "ipv4numtostring",
  "ipv4stringtonum",
  "ipv4stringtonumornull",
  "ipv4numtostringclassc",
  "ipv6numtostring",
  "ipv6stringtonum",
  "ipv6stringtonumornull",
  "ipv4toi pv6",
  "cutipv6",
  "ipv4cidrtorange",
  "ipv6cidrtorange",
  "toipv4",
  "toipv4ornull",
  "toipv6",
  "toipv6ornull",
  "isipv4string",
  "isipv6string",
  "isipaddressinrange",
]);

// ============================================================
// HASH FUNCTIONS (Safe)
// ============================================================
export const ALLOWED_HASH_FUNCTIONS = new Set([
  "halfmd5",
  "md5",
  "sipHash64",
  "siphash128",
  "siphash128reference",
  "cityhash64",
  "intHash32",
  "intHash64",
  "farmfingerprint64",
  "farmhash64",
  "metrohash64",
  "murmurHash2_32",
  "murmurHash2_64",
  "murmurHash3_32",
  "murmurHash3_64",
  "murmurHash3_128",
  "xxhash32",
  "xxhash64",
  "xxh3",
  "ngramSimHash",
  "ngramSimHashCaseInsensitive",
  "ngramSimHashUTF8",
  "ngramSimHashCaseInsensitiveUTF8",
  "wordShingleSimHash",
  "wordShingleSimHashCaseInsensitive",
  "wordShingleSimHashUTF8",
  "wordShingleSimHashCaseInsensitiveUTF8",
  "ngramMinHash",
  "ngramMinHashCaseInsensitive",
  "ngramMinHashUTF8",
  "ngramMinHashCaseInsensitiveUTF8",
  "ngramMinHashArg",
  "ngramMinHashArgCaseInsensitive",
  "ngramMinHashArgUTF8",
  "ngramMinHashArgCaseInsensitiveUTF8",
  "wordShingleMinHash",
  "wordShingleMinHashCaseInsensitive",
  "wordShingleMinHashUTF8",
  "wordShingleMinHashCaseInsensitiveUTF8",
  "wordShingleMinHashArg",
  "wordShingleMinHashArgCaseInsensitive",
  "wordShingleMinHashArgUTF8",
  "wordShingleMinHashArgCaseInsensitiveUTF8",
]);

// ============================================================
// WINDOW FUNCTIONS
// ============================================================
export const ALLOWED_WINDOW_FUNCTIONS = new Set([
  "row_number",
  "rank",
  "dense_rank",
  "ntile",
  "lead",
  "lag",
  "first_value",
  "last_value",
  "nth_value",
  "percent_rank",
  "cume_dist",
]);

// ============================================================
// OPERATORS (Binary/Comparison)
// ============================================================
export const ALLOWED_OPERATORS = new Set([
  // Comparison
  "=",
  "==",
  "!=",
  "<>",
  "<",
  ">",
  "<=",
  ">=",
  // Arithmetic
  "+",
  "-",
  "*",
  "/",
  "%",
  "div",
  "mod",
  // Logical
  "and",
  "or",
  "not",
  "xor",
  // Set
  "in",
  "not in",
  "global in",
  "global not in",
  // Pattern matching
  "like",
  "not like",
  "ilike",
  "not ilike",
  "regexp",
  "not regexp",
  "rlike",
  "not rlike",
  // Range
  "between",
  "not between",
  // Null checks
  "is",
  "is not",
  // String concat
  "||",
]);

// ============================================================
// BLOCKED FUNCTIONS (Dangerous - Security Risk)
// ============================================================
export const BLOCKED_FUNCTIONS = new Set([
  // Settings access - CRITICAL
  "getsetting",
  "setsetting",
  "currentsetting",
  "getcurrentsetting",
  // File/Network access - CRITICAL
  "file",
  "url",
  "s3",
  "s3cluster",
  "hdfs",
  "hdfscluster",
  "azureblobstorage",
  "azureblobstoragecluster",
  // Database connections - CRITICAL
  "mysql",
  "postgresql",
  "odbc",
  "jdbc",
  "sqlite",
  "mongodb",
  "redis",
  "hive",
  "iceberg",
  "deltalake",
  // Remote execution - CRITICAL
  "remote",
  "remotesecure",
  "cluster",
  "clusterallreplicas",
  "dictionary",
  "dictionaries",
  // Input/Output - CRITICAL
  "input",
  "format",
  "rawblob",
  // Resource exhaustion
  "sleep",
  "sleepeachrow",
  // System manipulation
  "throwif",
  "system",
  "kill",
  "detach",
  "attach",
  "optimize",
  "check",
  // DDL-like
  "create",
  "drop",
  "alter",
  "truncate",
  "rename",
  "exchange",
  // Potentially dangerous
  "generateulidrandom",
  "generatesnowflakeid",
  "filesystemavailable",
  "filesystemcapacity",
  "filesystemfree",
]);

/**
 * Combine all allowed function sets for easy lookup
 */
export function isAllowedFunction(name: string): boolean {
  const lowerName = name.toLowerCase();

  // First check blocked list
  if (BLOCKED_FUNCTIONS.has(lowerName)) {
    return false;
  }

  // Then check allowed lists
  return (
    ALLOWED_AGGREGATE_FUNCTIONS.has(lowerName) ||
    ALLOWED_DATE_FUNCTIONS.has(lowerName) ||
    ALLOWED_STRING_FUNCTIONS.has(lowerName) ||
    ALLOWED_ARRAY_FUNCTIONS.has(lowerName) ||
    ALLOWED_CONDITIONAL_FUNCTIONS.has(lowerName) ||
    ALLOWED_TYPE_FUNCTIONS.has(lowerName) ||
    ALLOWED_MATH_FUNCTIONS.has(lowerName) ||
    ALLOWED_JSON_FUNCTIONS.has(lowerName) ||
    ALLOWED_UUID_FUNCTIONS.has(lowerName) ||
    ALLOWED_IP_FUNCTIONS.has(lowerName) ||
    ALLOWED_HASH_FUNCTIONS.has(lowerName) ||
    ALLOWED_WINDOW_FUNCTIONS.has(lowerName)
  );
}

/**
 * Check if an operator is allowed
 */
export function isAllowedOperator(op: string): boolean {
  return ALLOWED_OPERATORS.has(op.toLowerCase());
}

/**
 * Check if a function is explicitly blocked
 */
export function isBlockedFunction(name: string): boolean {
  return BLOCKED_FUNCTIONS.has(name.toLowerCase());
}
