blank_issues_enabled: true
contact_links:
  - name: Schedule Demo
    url: https://cal.com/team/helicone/helicone-discovery
    about: Chat with one of the founders of Helicone. We'd love to learn more about your company and it's LLM use-case.
  - name: Discord
    url: https://discord.com/invite/bNd3NwpwZY
    about: Join 1000+ Helicone community members! 
