# This docker file must be built using the context of it's parent directory
# docker build -t valhalla .. -f dockerfile

# Use an official Node.js runtime as the base image
# Updated to Node 22 to support @peculiar/x509@1.14.2 dependency requirements
FROM --platform=linux/amd64 node:22



#yarn workspace jawn serve
ENV PORT=8585
