# This docker file must be built using the context of it's parent directory
# docker build -t valhalla .. -f dockerfile

# Use an official Node.js runtime as the base image
FROM --platform=linux/amd64 node:20



#yarn workspace jawn serve
ENV PORT=8585
