# This docker file must be built using the context of it's parent directory
# docker build -t valhalla .. -f dockerfile

# Use an official Node.js runtime as the base image
FROM --platform=linux/amd64 node:20

# Set the working directory inside the container
WORKDIR /usr/src/app

COPY . .
RUN yarn install

# Build the TypeScript code
RUN npx lerna run build

RUN yarn install