# This docker file must be built using the context of it's parent directory
# docker build -t valhalla .. -f dockerfile

# Use an official Node.js runtime as the base image
FROM --platform=linux/amd64 node:20

WORKDIR /usr/src/app/valhalla/jawn

COPY ./valhalla/jawn/package.json ./valhalla/jawn/yarn.lock ./

RUN yarn install

WORKDIR /usr/src/app/shared
COPY ./shared .

WORKDIR /usr/src/app/valhalla/jawn
COPY ./valhalla/jawn .

RUN find /usr/src/app/valhalla/jawn -name ".env.*" -exec rm {} \;

#yarn workspace jawn serve
ENV PORT=8585

RUN yarn build

ENV DLQ_WORKER_COUNT=0
ENV NORMAL_WORKER_COUNT=1

CMD [ "yarn", "serve" ]