{
 "title": "Fly App Dashboard",
 "description": "Basic metrics for your app on Fly.io",
 "tags": [ "fly" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "source", "query": "prometheus" },
   { "name": "region", "query": { "query": "label_values(region)" } },
   {
    "name": "host",
    "query": {
     "query": "label_values({region=~\"^$region$\"}, host)"
    }
   },
   { "name": "app", "query": { "query": "label_values(app)" } }
  ]
 },
 "panels": [
  {
   "title": "Machines",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Data Transfer",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(fly_instance_net_sent_bytes{device=\"eth0\",app=~\"^$app$\",region=~\"^$region$\",host=~\"^$host$\"}[$__rate_interval]))",
       "legendFormat": "sent"
      },
      {
       "expr": "sum(rate(fly_instance_net_recv_bytes{device=\"eth0\",app=~\"^$app$\",region=~\"^$region$\",host=~\"^$host$\"}[$__rate_interval]))",
       "legendFormat": "recv"
      }
     ]
    },
    {
     "title": "Load Average",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
     "targets": [
      {
       "expr": "max(max_over_time(fly_instance_load_average{minutes=\"1\",app=~\"^$app$\",region=~\"^$region$\",host=~\"^$host$\"}[$__rate_interval]))",
       "legendFormat": "1m"
      },
      {
       "expr": "max(max_over_time(fly_instance_load_average{minutes=\"5\",app=~\"^$app$\",region=~\"^$region$\",host=~\"^$host$\"}[$__rate_interval]))",
       "legendFormat": "5m"
      },
      {
       "expr": "max(max_over_time(fly_instance_load_average{minutes=\"15\",app=~\"^$app$\",region=~\"^$region$\",host=~\"^$host$\"}[$__rate_interval]))",
       "legendFormat": "15m"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(fly_instance_memory_mem_total{app=~\"^$app$\",region=~\"^$region$\",host=~\"^$host$\"})",
       "legendFormat": "total"
      },
      {
       "expr": "avg(fly_instance_memory_mem_total{app=~\"^$app$\",region=~\"^$region$\",host=~\"^$host$\"}) - avg(fly_instance_memory_mem_free{app=~\"^$app$\",region=~\"^$region$\",host=~\"^$host$\"})",
       "legendFormat": "used"
      }
     ]
    },
    {
     "title": "CPU Time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(irate(fly_instance_cpu{mode=\"system\",app=~\"^$app$\",region=~\"^$region$\",host=~\"^$host$\"}[$__rate_interval])) * 100",
       "legendFormat": "busy"
      },
      {
       "expr": "sum(irate(fly_instance_cpu{mode=\"user\",app=~\"^$app$\",region=~\"^$region$\",host=~\"^$host$\"}[$__rate_interval])) * 100",
       "legendFormat": "user"
      },
      {
       "expr": "sum(irate(fly_instance_cpu{mode=\"iowait\",app=~\"^$app$\",region=~\"^$region$\",host=~\"^$host$\"}[$__rate_interval])) * 100",
       "legendFormat": "iowait"
      },
      {
       "expr": "sum(irate(fly_instance_cpu{mode=~\".*irq\",app=~\"^$app$\",region=~\"^$region$\",host=~\"^$host$\"}[$__rate_interval])) * 100",
       "legendFormat": "irqs"
      },
      {
       "expr": "sum(irate(fly_instance_cpu{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',app=~\"^$app$\",region=~\"^$region$\",host=~\"^$host$\"}[$__rate_interval])) * 100",
       "legendFormat": "other"
      },
      {
       "expr": "sum(irate(fly_instance_cpu{mode=\"idle\",app=~\"^$app$\",region=~\"^$region$\",host=~\"^$host$\"}[$__rate_interval])) * 100",
       "legendFormat": "idle"
      }
     ]
    }
   ]
  },
  {
   "title": "TCP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Edge connections per second",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum(rate(fly_edge_tcp_connects_count{app=~\"^$app$\",region=~\"^$region$\",host=~\"^$host$\"}[$__rate_interval]))",
       "legendFormat": "connections"
      }
     ]
    },
    {
     "title": "App connections per second",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "sum(rate(fly_app_tcp_connects_count{app=~\"^$app$\",region=~\"^$region$\",host=~\"^$host$\"}[$__rate_interval]))",
       "legendFormat": "connections"
      }
     ]
    },
    {
     "title": "Edge disconnections per second",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "sum(rate(fly_edge_tcp_disconnects_count{app=~\"^$app$\",region=~\"^$region$\",host=~\"^$host$\"}[$__rate_interval]))",
       "legendFormat": "disconnections"
      }
     ]
    },
    {
     "title": "App disconnections per second",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
     "targets": [
      {
       "expr": "sum(rate(fly_app_tcp_disconnects_count{app=~\"^$app$\",region=~\"^$region$\",host=~\"^$host$\"}[$__rate_interval]))",
       "legendFormat": "disconnections"
      }
     ]
    }
   ]
  },
  {
   "title": "TLS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Handshake times (bucketed)",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sum(increase(fly_edge_tls_handshake_time_seconds_bucket{app=~\"^$app$\",region=~\"^$region$\",host=~\"^$host$\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Handshakes per second",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
     "targets": [
      {
       "expr": "sum(rate(fly_edge_tls_handshake_time_seconds_count{app=~\"^$app$\",region=~\"^$region$\", host=~\"^$host$\"}[$__rate_interval]))",
       "legendFormat": "handshakes per second"
      }
     ]
    },
    {
     "title": "Handshake queue times (bucketed)",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
     "targets": [
      {
       "expr": "sum(increase(fly_edge_tls_queue_time_seconds_bucket{app=~\"^$app$\",region=~\"^$region$\",host=~\"^$host$\"}[$__interval])) by (le) > 0",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Handshake errors (increase)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sum(increase(fly_edge_tls_handshake_errors{app=~\"^$app$\",region=~\"^$region$\",host=~\"^$host$\"})) by (servername) > 0",
       "legendFormat": "{{servername}}"
      }
     ]
    },
    {
     "title": "SNI limit reached",
     "type": "timeseries",
     "description": "Servers have a limit on how many TLS handshakes they will process concurrently per servername indicator. When this limit is reached, we queue handshakes up to a point. This chart shows how often the limit was reached during an interval.",
     "gridPos": { "h": 6, "w": 7, "x": 10, "y": 10 },
     "targets": [
      {
       "expr": "sum(increase(fly_edge_tls_sni_limit_reached_count{app=~\"^$app$\",region=~\"^$region$\",host=~\"^$host$\"})) by (servername) > 0",
       "legendFormat": "{{servername}}"
      }
     ]
    },
    {
     "title": "IP limit reached",
     "type": "timeseries",
     "description": "Servers have a limit on how many TLS handshakes they will process concurrently per IP block. When this limit is reached, we queue handshakes up to a point. This chart shows how often the limit was reached during an interval.",
     "gridPos": { "h": 6, "w": 7, "x": 17, "y": 10 },
     "targets": [
      {
       "expr": "sum(increase(fly_edge_tls_ip_limit_reached_count{app=~\"^$app$\",region=~\"^$region$\",host=~\"^$host$\"})) by (ip) > 0",
       "legendFormat": "{{ip}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Edge Responses Per Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "sum(rate(fly_edge_http_responses_count{app=~\"^$app$\",region=~\"^$region$\",host=~\"^$host$\"})[$__rate_interval]) by (status)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Edge Response Times",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "sum(increase(fly_edge_http_response_time_seconds_bucket{app=~\"^$app$\",region=~\"^$region$\",host=~\"^$host$\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "App Response Times",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
     "targets": [
      {
       "expr": "sum(increase(fly_app_http_response_time_seconds_bucket{app=~\"^$app$\",region=~\"^$region$\",host=~\"^$host$\"}[$__interval])) by (le) > 0",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  }
 ]
}