openapi: 3.0.0
info:
  title: Helicone JAWN Service
  description: API for the Helicone JAWN service, providing functionalities related to requests and responses.
  termsOfService: https://www.helicone.ai/terms
  contact:
    email: engineering@helicone.ai
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: http://localhost:8585
    description: Development server
  - url: https://jawn.helicone.ai
    description: Production server

paths:
  /v1/request:
    post:
      tags:
        - request
      summary: Insert a new request and its response
      description: Adds a new entry to the 'request' and 'response' tables.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RequestResponseInsert"
      responses:
        "201":
          description: Successfully inserted the new request and response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  requestId:
                    type: string
                    format: uuid
                    description: The unique ID of the newly inserted request.
                  responseId:
                    type: string
                    format: uuid
                    description: The unique ID of the associated response.
                  message:
                    type: string
                    example: Request and Response successfully inserted.
        "400":
          description: Invalid input.
        "500":
          description: Internal server error.
      security:
        - authorization: []

  /healthcheck-db:
    get:
      tags:
        - healthcheck
      summary: Check the status of the database
      description: Checks the status of the database.
      responses:
        "200":
          description: Database is up and running.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Database is up and running.
        "500":
          description: Internal server error.
  /healthcheck:
    get:
      tags:
        - healthcheck
      summary: Check the status of the service
      description: Checks the status of the service.
      responses:
        "200":
          description: Service is up and running.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Service is up and running.
        "500":
          description: Internal server error

components:
  schemas:
    RequestResponseInsert:
      type: object
      properties:
        request:
          type: object
          nullable: false
          properties:
            # Request fields
            body:
              type: object
              description: JSON object containing the request body.
            request_id:
              type: string
              format: uuid
              nullable: true
              description: The unique ID of the request.
            url_href:
              type: string
              description: The URL associated with the request.
              nullable: false
            provider:
              type: string
              description: The provider associated with the request.
              nullable: false
            user_id:
              type: string
              nullable: true
              description: The user ID associated with the request.
            properties:
              type: object
              nullable: true
              description: JSON object containing additional properties.
            helicone_api_key_id:
              type: integer
              format: int64
              nullable: true
              description: The API key ID for Helicone.
            helicone_org_id:
              type: string
              format: uuid
              nullable: true
              description: The organization ID for Helicone.
            helicone_proxy_key_id:
              type: string
              format: uuid
              nullable: true
              description: The proxy key ID for Helicone.
          required:
            - url_href
            - provider
        # Response fields
        response:
          type: object
          properties:
            response_id:
              type: string
              format: uuid
              nullable: true
              description: The unique ID of the response.
            delay_ms:
              type: integer
              nullable: true
              description: The delay in milliseconds.
            http_status:
              type: integer
              format: int16
              nullable: true
              description: The status code.
            completion_tokens:
              type: integer
              nullable: true
              description: Number of tokens used for completion.
            model:
              type: string
              nullable: true
              description: The model used for generating the response.
            prompt_tokens:
              type: integer
              nullable: true
              description: Number of tokens used in the prompt.
            body:
              type: object
              nullable: true
              description: JSON object containing the response body.
          required:
            - body
            - http_status
      required:
        - request
        - response

  securitySchemes:
    authorization:
      type: apiKey
      name: authorization
      in: header
