import type { Endpoint } from "../../../types";

export const endpoints = {
  "gpt-4o:openai": {
    modelId: "gpt-4o",
    provider: "openai",
    baseModelId: "gpt-4o",
    pricing: {
      prompt: 2.5,
      completion: 10,
      cacheRead: 1.25,
    },
    contextLength: 128000,
    maxCompletionTokens: 16384,
    supportedParameters: [
      "tools",
      "tool_choice",
      "seed",
      "max_tokens",
      "response_format",
      "temperature",
      "top_p",
      "stop",
      "frequency_penalty",
      "presence_penalty",
    ],
    ptbEnabled: true,
  },
  "gpt-4o:extended:openai": {
    modelId: "gpt-4o:extended",
    provider: "openai",
    baseModelId: "gpt-4o-2024-08-06",
    pricing: {
      prompt: 2.5,
      completion: 10,
      cacheRead: 1.25,
    },
    contextLength: 128000,
    maxCompletionTokens: 64000,
    supportedParameters: [
      "tools",
      "tool_choice",
      "seed",
      "max_tokens",
      "response_format",
      "temperature",
      "top_p",
      "stop",
      "frequency_penalty",
      "presence_penalty",
    ],
    ptbEnabled: true,
  },
  "gpt-4o-mini:openai": {
    modelId: "gpt-4o-mini",
    provider: "openai",
    baseModelId: "gpt-4o-mini",
    pricing: {
      prompt: 0.15,
      completion: 0.6,
      cacheRead: 0.075,
    },
    contextLength: 128000,
    maxCompletionTokens: 16384,
    supportedParameters: [
      "tools",
      "tool_choice",
      "seed",
      "max_tokens",
      "response_format",
      "temperature",
      "top_p",
      "stop",
      "frequency_penalty",
      "presence_penalty",
    ],
    ptbEnabled: true,
  },
  "chatgpt-4o-latest:openai": {
    modelId: "chatgpt-4o-latest",
    provider: "openai",
    baseModelId: "chatgpt-4o-latest",
    pricing: {
      prompt: 5,
      completion: 20,
      cacheRead: 2.5,
    },
    contextLength: 128000,
    maxCompletionTokens: 16384,
    supportedParameters: [
      "tools",
      "tool_choice",
      "seed",
      "max_tokens",
      "response_format",
      "temperature",
      "top_p",
      "stop",
      "frequency_penalty",
      "presence_penalty",
    ],
    ptbEnabled: true,
  },
  "gpt-4o-mini-search-preview:openai": {
    modelId: "gpt-4o-mini-search-preview",
    provider: "openai",
    baseModelId: "gpt-4o-mini-search-preview",
    pricing: {
      prompt: 0.15,
      completion: 0.6,
    },
    contextLength: 128000,
    maxCompletionTokens: 16384,
    supportedParameters: ["max_tokens", "response_format"],
    ptbEnabled: true,
  },
  "gpt-4o-search-preview:openai": {
    modelId: "gpt-4o-search-preview",
    provider: "openai",
    baseModelId: "gpt-4o-search-preview",
    pricing: {
      prompt: 2.5,
      completion: 10,
    },
    contextLength: 128000,
    maxCompletionTokens: 16384,
    supportedParameters: ["max_tokens", "response_format"],
    ptbEnabled: true,
  },
} satisfies Record<string, Endpoint>;

export type EndpointId = keyof typeof endpoints;