/**
 *
 * DO NOT EDIT THIS FILE UNLESS IT IS IN /costs
 */

import { ModelRow } from "../../interfaces/Cost";

export const costs: ModelRow[] = [
  {
    model: {
      operator: "equals",
      value: "claude-instant-1",
    },
    cost: {
      prompt_token: 0.00000163,
      completion_token: 0.0000551,
    },
    max_window_size: 100000,
  },
  {
    model: {
      operator: "equals",
      value: "claude-v1",
    },
    cost: {
      prompt_token: 0.000008,
      completion_token: 0.000024,
    },
    max_window_size: 100000,
  },
  {
    model: {
      operator: "equals",
      value: "claude-2",
    },
    cost: {
      prompt_token: 0.000008,
      completion_token: 0.000024,
    },
    max_window_size: 100000,
  },
  {
    model: {
      operator: "equals",
      value: "claude-instant-1.2",
    },
    cost: {
      prompt_token: 0.00000163,
      completion_token: 0.00000551,
    },
    max_window_size: 100000,
  },
  {
    model: {
      operator: "equals",
      value: "claude-2.0",
    },
    cost: {
      prompt_token: 0.00001102,
      completion_token: 0.00003268,
    },
    max_window_size: 100000,
  },
  {
    model: {
      operator: "equals",
      value: "claude-3-opus-20240229",
    },
    cost: {
      prompt_token: 0.000015,
      completion_token: 0.000075,
    },
    showInPlayground: true,
    max_window_size: 200000,
  },
  {
    model: {
      operator: "equals",
      value: "claude-3-sonnet-20240229",
    },
    cost: {
      prompt_token: 0.000003,
      completion_token: 0.000015,
    },
    showInPlayground: true,
    max_window_size: 200000,
  },
  {
    model: {
      operator: "equals",
      value: "claude-3-5-sonnet-20240620",
    },
    cost: {
      prompt_token: 0.000003,
      completion_token: 0.000015,
    },
    showInPlayground: true,
    max_window_size: 200000,
  },
  {
    model: {
      operator: "equals",
      value: "claude-3-haiku-20240307",
    },
    cost: {
      prompt_token: 0.00000025,
      completion_token: 0.00000125,
    },
    showInPlayground: true,
    max_window_size: 200000,
  },
];
