receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true
  otlphttp:
    endpoint: http://loki:3100/otlp
    tls:
      insecure: true
  otlphttp/prom:
    endpoint: http://prometheus:9090/api/v1/otlp
    tls:
      insecure: true

extensions:
  health_check:

processors:
  batch:


service:
  extensions:
    - health_check
  pipelines:
    traces:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - otlp
    metrics:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - otlphttp/prom
    logs:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - otlphttp
