/**
 *
 * DO NOT EDIT THIS FILE UNLESS IT IS IN /costs
 */

import { ModelRow } from "../../interfaces/Cost";

export const costs: ModelRow[] = [
  {
    model: {
      operator: "includes",
      value: "llama",
    },
    cost: {
      prompt_token: 3e-7,
      completion_token: 3e-7,
    },
    max_window_size: 4096,
  },
  {
    model: {
      operator: "includes",
      value: "mistral",
    },
    cost: {
      prompt_token: 3e-7,
      completion_token: 3e-7,
    },
    max_window_size: 32768,
  },
];
