/**
 *
 * DO NOT EDIT THIS FILE UNLESS IT IS IN /costs
 */

import { ModelDetailsMap, ModelRow } from "../../interfaces/Cost";

export const costs: ModelRow[] = [
  {
    model: {
      operator: "includes",
      value: "gemini-pro",
    },
    cost: {
      prompt_token: 0.000000125,
      completion_token: 0.000000375,
    },
  },
  {
    model: {
      operator: "equals",
      value: "gemini-1.0-pro-vision-001",
    },
    cost: {
      prompt_token: 0.000000125,
      completion_token: 0.000000375,
    },
  },
  {
    model: {
      operator: "equals",
      value: "gemini-1.0-pro",
    },
    cost: {
      prompt_token: 0.000000125,
      completion_token: 0.000000375,
    },
  },
  {
    model: {
      operator: "includes",
      value: "gemini-1.5-flash",
    },
    cost: {
      prompt_token: 0.00000035,
      completion_token: 0.00000105,
    },
  },
  {
    model: {
      operator: "equals",
      value: "gemini-flash-1.5-8b",
    },
    cost: {
      prompt_token: 3.75e-8,
      completion_token: 1.5e-7,
    },
  },
  {
    model: {
      operator: "includes",
      value: "gemini-1.5-pro",
    },
    cost: {
      prompt_token: 0.0000035,
      completion_token: 0.0000105,
    },
  },
  {
    model: {
      operator: "includes",
      value: "gemini-2.0-flash",
    },
    cost: {
      prompt_token: 0.0000001,
      completion_token: 0.0000004,
    },
  },
  {
    model: {
      operator: "includes",
      value: "claude-3-opus",
    },
    cost: {
      prompt_token: 0.000015,
      completion_token: 0.000075,
    },
  },
  {
    model: {
      operator: "includes",
      value: "claude-3-5-haiku",
    },
    cost: {
      prompt_token: 0.0000008,
      completion_token: 0.000004,
    },
  },
  {
    model: {
      operator: "includes",
      value: "claude-3-5-sonnet",
    },
    cost: {
      prompt_token: 0.000003,
      completion_token: 0.000015,
    },
  },
  {
    model: {
      operator: "includes",
      value: "claude-3-7-sonnet",
    },
    cost: {
      prompt_token: 0.000003,
      completion_token: 0.000015,
    },
  },
  {
    model: {
      operator: "equals",
      value: "gemini-2.5-pro-exp-03-25",
    },
    cost: {
      prompt_token: 0,
      completion_token: 0,
    },
  },
  {
    model: {
      operator: "includes",
      value: "gemini-2.0-flash",
    },
    cost: {
      prompt_token: 0.0000001,
      completion_token: 0.0000004,
    },
  },
  {
    model: {
      operator: "includes",
      value: "gemini-2.0-flash-lite",
    },
    cost: {
      prompt_token: 0.000000075,
      completion_token: 0.0000003,
    },
  },
  {
    model: {
      operator: "includes",
      value: "gemini-2.5-pro-preview",
    },
    cost: {
      prompt_token: 0.00000125,
      completion_token: 0.00001,
    },
  },
  {
    model: {
      operator: "includes",
      value: "gemini-2.5-flash-preview",
    },
    cost: {
      prompt_token: 0.00000015,
      completion_token: 0.0000006,
    },
  },
];

export const modelDetails: ModelDetailsMap = {
  "gemini-1.0-pro": {
    matches: ["gemini-1.0-pro", "gemini-pro", "gemini-1.0-pro-vision-001"],
    searchTerms: ["gemini 1.0", "gemini pro", "google gemini"],
    info: {
      maxTokens: 32768,
      releaseDate: "2023-12-06",
      description:
        "Google's first-generation advanced multimodal model that can understand text, code, and images. It provides strong reasoning capabilities and follows instructions effectively.",
      tradeOffs: [
        "Lower cost compared to Gemini 1.5",
        "Shorter context window than newer models",
        "Strong balance of performance and efficiency",
      ],
      benchmarks: {
        mmlu: 0.796,
        hellaswag: 0.871,
        gsm8k: 0.843,
      },
      capabilities: [
        "Text understanding and generation",
        "Code understanding and generation",
        "Image understanding (vision-001 variant)",
        "Reasoning across content types",
        "Instruction following",
      ],
      strengths: [
        "Cost-effective for many applications",
        "Well-balanced performance profile",
        "Strong reasoning capabilities",
        "Effective code generation",
      ],
      weaknesses: [
        "Limited context window compared to newer models",
        "Less sophisticated than Gemini 1.5 series",
        "Occasional inaccuracies with complex reasoning",
      ],
      recommendations: [
        "General purpose applications",
        "Standard chatbots and assistants",
        "Content generation and summarization",
        "Code development assistance",
        "Cost-sensitive deployments",
      ],
    },
  },
  "gemini-1.5-pro": {
    matches: [
      "gemini-1.5-pro",
      "gemini-1.5-pro-latest",
      "gemini-1.5-pro-experimental",
    ],
    searchTerms: ["gemini 1.5", "gemini 1.5 pro", "google gemini 1.5"],
    info: {
      maxTokens: 1000000,
      releaseDate: "2024-02-15",
      description:
        "Google's most capable multimodal model with an extremely long context window of up to 1 million tokens. It excels at complex reasoning, long-form content processing, and multimodal understanding.",
      tradeOffs: [
        "Higher cost than Gemini 1.0 and Flash variants",
        "Greater latency for complex tasks",
        "Exceptional context length capabilities",
      ],
      benchmarks: {
        mmlu: 0.868,
        hellaswag: 0.885,
        gsm8k: 0.915,
        bbh: 0.716,
      },
      capabilities: [
        "Million-token context processing",
        "Advanced multimodal reasoning",
        "Complex document analysis",
        "Code generation and analysis",
        "Multi-step reasoning chains",
        "Long-form content generation",
      ],
      strengths: [
        "Industry-leading context length",
        "Strong performance on reasoning tasks",
        "High-quality text and code generation",
        "Excellent at following complex instructions",
        "Strong multimodal capabilities",
      ],
      weaknesses: [
        "Higher cost per token than Flash variant",
        "Processing time increases with context length",
        "Resource-intensive for production deployments",
      ],
      recommendations: [
        "Long document processing and analysis",
        "Complex reasoning applications",
        "Advanced AI assistants",
        "Enterprise-grade solutions",
        "Research applications requiring long context",
      ],
    },
  },
  "gemini-1.5-flash": {
    matches: [
      "gemini-1.5-flash",
      "gemini-1.5-flash-latest",
      "gemini-flash-1.5-8b",
    ],
    searchTerms: ["gemini 1.5 flash", "gemini flash", "google flash"],
    info: {
      maxTokens: 1000000,
      releaseDate: "2024-02-15",
      description:
        "A faster, more cost-effective variant of Gemini 1.5 that maintains strong capabilities while optimizing for performance and cost efficiency. Suitable for production deployments requiring high throughput.",
      tradeOffs: [
        "Lower cost than Gemini 1.5 Pro",
        "Slightly reduced capabilities compared to Pro",
        "Faster inference times",
      ],
      benchmarks: {
        mmlu: 0.747,
        hellaswag: 0.871,
        gsm8k: 0.818,
      },
      capabilities: [
        "Million-token context processing",
        "Efficient content generation",
        "Code understanding and generation",
        "Multimodal reasoning",
        "High-throughput processing",
      ],
      strengths: [
        "Cost-effective for production use",
        "Maintains long context capabilities",
        "Faster response times",
        "Excellent performance/cost ratio",
      ],
      weaknesses: [
        "Slightly lower reasoning capabilities than Pro",
        "Less sophisticated with very complex tasks",
        "May require more explicit instructions",
      ],
      recommendations: [
        "High-volume production applications",
        "Cost-sensitive deployments",
        "Applications requiring fast response times",
        "Scalable AI solutions",
        "General-purpose assistants",
      ],
    },
  },
  "gemini-2.0-flash": {
    matches: [
      "gemini-2.0-flash",
      "gemini-2.0-flash-latest",
      "gemini-2.0-flash-thinking",
    ],
    searchTerms: ["gemini 2.0", "gemini 2.0 flash", "google 2.0"],
    info: {
      maxTokens: 1000000,
      releaseDate: "2024-10-17",
      description:
        "The newest generation of Google's Gemini models, featuring improved reasoning, instruction following, and factual accuracy, with the Flash variant optimized for cost-efficiency and performance.",
      tradeOffs: [
        "Balanced for performance and cost",
        "Improved capabilities over 1.5 series",
        "Enhanced reasoning through thinking capabilities",
      ],
      benchmarks: {
        mmlu: 0.821,
        hellaswag: 0.902,
        gsm8k: 0.925,
      },
      capabilities: [
        "Enhanced reasoning through thinking",
        "Improved factual accuracy",
        "Better instruction following",
        "Advanced code generation",
        "Long context processing",
      ],
      strengths: [
        "Latest architecture with improved performance",
        "Strong balance of cost and capability",
        "Enhanced factual accuracy",
        "Better handling of nuanced instructions",
      ],
      weaknesses: [
        "Newer model with less production testing",
        "May have undiscovered limitations",
        "Higher cost than 1.0 series",
      ],
      recommendations: [
        "Applications requiring improved reasoning",
        "Projects where factual accuracy is critical",
        "General-purpose assistants and agents",
        "Coding and development assistance",
      ],
    },
  },
  "gemini-2.0-flash-lite": {
    matches: ["gemini-2.0-flash-lite", "gemini-2.0-flash-lite-001"],
    searchTerms: ["gemini 2.0 lite", "gemini flash lite", "google flash lite"],
    info: {
      maxTokens: 1000000,
      releaseDate: "2024-10-25",
      description:
        "A lighter, more cost-effective version of Gemini 2.0 Flash, designed for applications requiring high efficiency while maintaining good performance. Ideal for high-volume, cost-sensitive deployments.",
      tradeOffs: [
        "Lowest cost in the 2.0 series",
        "Optimized for efficiency over capability",
        "Good balance for routine tasks and general assistance",
      ],
      benchmarks: {
        mmlu: 0.792,
        hellaswag: 0.885,
        gsm8k: 0.842,
      },
      capabilities: [
        "Efficient content generation",
        "Good general knowledge",
        "Basic reasoning capabilities",
        "Code understanding and generation",
        "Long context processing",
      ],
      strengths: [
        "Most cost-effective model in 2.0 series",
        "Fast response times",
        "Excellent for high-volume applications",
        "Good general-purpose performance",
      ],
      weaknesses: [
        "Less sophisticated with complex reasoning",
        "More limited creative capabilities",
        "May require more explicit instructions",
      ],
      recommendations: [
        "High-volume production applications",
        "Cost-sensitive deployments",
        "Customer service and support bots",
        "Content moderation",
        "Simple Q&A systems",
      ],
    },
  },
  "gemini-2.5-pro": {
    matches: ["gemini-2.5-pro-exp-03-25", "gemini-2.5-pro"],
    searchTerms: ["gemini 2.5", "gemini 2.5 pro", "google 2.5"],
    info: {
      maxTokens: 1000000,
      releaseDate: "2024-07-19",
      description:
        "Google's most advanced 'thinking model' with enhanced reasoning capabilities. Currently in experimental phase, it leads on complex reasoning, code generation, and multimodal tasks.",
      tradeOffs: [
        "Experimental model in development",
        "Currently free during testing phase",
        "Cutting-edge features with potential AI agents integration",
      ],
      benchmarks: {
        mmlu: 0.88,
        hellaswag: 0.935,
        gsm8k: 0.95,
      },
      capabilities: [
        "Advanced reasoning through thinking capabilities",
        "Superior instruction following",
        "Enhanced code generation (63.8% on SWE-Bench Verified)",
        "Improved multimodal understanding",
        "Long context processing",
        "Complex task handling",
      ],
      strengths: [
        "Top performance on LMArena human preference leaderboard",
        "Strong performance on Humanity's Last Exam (18.8%)",
        "High-quality outputs across domains",
        "Better understanding of complex instructions",
        "Improved coding capabilities",
      ],
      weaknesses: [
        "Experimental status with potential instability",
        "May change behavior during development",
        "Currently limited availability in select products",
      ],
      recommendations: [
        "Research and experimentation",
        "Testing advanced capabilities",
        "Complex reasoning tasks",
        "Code generation and editing",
        "Multimodal applications",
      ],
    },
  },
};

export const googleProvider = {
  costs: costs,
  modelDetails: modelDetails,
};
