/**
 *
 * DO NOT EDIT THIS FILE UNLESS IT IS IN /costs
 */

import { ModelRow } from "../../interfaces/Cost";

export const costs: ModelRow[] = [
  {
    model: {
      operator: "equals",
      value: "google/gemini-pro",
    },
    cost: {
      prompt_token: 0.000000125,
      completion_token: 0.000000375,
    },
  },
];
