/**
 *
 * DO NOT EDIT THIS FILE UNLESS IT IS IN /costs
 */

import { ModelRow } from "../../interfaces/Cost";

export const costs: ModelRow[] = [
  {
    model: {
      operator: "equals",
      value: "grok-beta",
    },
    cost: {
      prompt_token: 0.000005,
      completion_token: 0.000015,
    },
  },
  {
    model: {
      operator: "equals",
      value: "grok-vision-beta",
    },
    cost: {
      prompt_token: 0.000005,
      completion_token: 0.000015,
    },
  },
  {
    model: {
      operator: "equals",
      value: "grok-2-1212",
    },
    cost: {
      prompt_token: 0.000002,
      completion_token: 0.00001,
    },
  },
  {
    model: {
      operator: "equals",
      value: "grok-2-vision-1212",
    },
    cost: {
      prompt_token: 0.000002,
      completion_token: 0.00001,
    },
  },
  {
    model: {
      operator: "equals",
      value: "grok-3",
    },
    cost: {
      prompt_token: 0.000003,
      completion_token: 0.000015,
    },
  },
  {
    model: {
      operator: "equals",
      value: "grok-3-fast",
    },
    cost: {
      prompt_token: 0.000003,
      completion_token: 0.000025,
    },
  },
  {
    model: {
      operator: "equals",
      value: "grok-3-mini",
    },
    cost: {
      prompt_token: 0.0000003,
      completion_token: 0.0000005,
    },
  },
  {
    model: {
      operator: "equals",
      value: "grok-3-mini-fast",
    },
    cost: {
      prompt_token: 0.0000006,
      completion_token: 0.000004,
    },
  },
];
