FROM mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm

RUN npm install -g @anthropic-ai/claude-code

RUN mkdir -p /tmp && curl -fsSL https://get.docker.com -o /tmp/get-docker.sh && sudo sh /tmp/get-docker.sh


