/**
 *
 * DO NOT EDIT THIS FILE UNLESS IT IS IN /costs
 */

import { ModelRow } from "../../interfaces/Cost";

export const costs: ModelRow[] = [
  {
    model: {
      operator: "equals",
      value: "MiniMaxAI/MiniMax-M2.7",
    },
    cost: {
      prompt_token: 0.0000003,
      completion_token: 0.0000003,
    },
  },
  {
    model: {
      operator: "equals",
      value: "moonshotai/Kimi-K2.6",
    },
    cost: {
      prompt_token: 0.00000035,
      completion_token: 0.00000035,
    },
  },
  {
    model: {
      operator: "equals",
      value: "deepseek-ai/DeepSeek-V4-Flash-0731",
    },
    cost: {
      prompt_token: 0.00000025,
      completion_token: 0.00000025,
    },
  },
];
