export const providersNames = [
  "OPENAI",
  "ANTHROPIC",
  "AZURE",
  "LOCAL",
  "HELICONE",
  "AMDBARTEK",
  "ANYSCALE",
  "CLOUDFLARE",
  "2YFV",
  "TOGETHER",
  "LEMONFOX",
  "FIREWORKS",
  "PERPLEXITY",
  "GOOGLE",
  "OPENROUTER",
  "WISDOMINANUTSHELL",
  "GROQ",
  "COHERE",
  "MISTRAL",
  "DEEPINFRA",
  "QSTASH",
  "FIRECRAWL",
  "AWS",
  "DEEPSEEK",
  "X",
  "AVIAN",
  "NEBIUS",
  "NOVITA",
] as const;

export type ProviderName = (typeof providersNames)[number];
