create table "public"."evaluator_experiments" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "experiment" uuid not null,
    "evaluator" uuid not null
);

CREATE UNIQUE INDEX evaluator_experiments_experiment_evaluator_key ON public.evaluator_experiments (experiment, evaluator);

alter table "public"."evaluator_experiments" add constraint "evaluator_experiments_experiment_evaluator_key" UNIQUE using index "evaluator_experiments_experiment_evaluator_key";

alter table "public"."evaluator_experiments" enable row level security;

CREATE UNIQUE INDEX "evaluator_experiments_pkey" ON public."evaluator_experiments" USING btree (id);

alter table "public"."evaluator_experiments" add constraint "evaluator_experiments_pkey" PRIMARY KEY using index "evaluator_experiments_pkey";

alter table "public"."evaluator_experiments" add constraint "public_evaluator_experiments_evaluator_fkey" FOREIGN KEY (evaluator) REFERENCES evaluator(id) not valid;

alter table "public"."evaluator_experiments" validate constraint "public_evaluator_experiments_evaluator_fkey";

alter table "public"."evaluator_experiments" add constraint "public_evaluator_experiments_experiment_fkey" FOREIGN KEY (experiment) REFERENCES experiment_v2(id) not valid;

alter table "public"."evaluator_experiments" validate constraint "public_evaluator_experiments_experiment_fkey";

revoke all on table "public"."evaluator_experiments" from anon;
revoke all on table "public"."evaluator_experiments" from authenticated;

