/**
 *
 * DO NOT EDIT THIS FILE UNLESS IT IS IN /costs
 */

import { ModelRow } from "../../interfaces/Cost";

export const costs: ModelRow[] = [
  {
    model: {
      operator: "equals",
      value: "google/gemini-2.5-pro-preview-03-25",
    },
    cost: {
      prompt_token: 1.25e-6,
      completion_token: 1e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "thudm/glm-z1-32b:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "thudm/glm-4-32b:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "google/gemini-2.5-flash-preview",
    },
    cost: {
      prompt_token: 1.5e-7,
      completion_token: 6e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "google/gemini-2.5-flash-preview:thinking",
    },
    cost: {
      prompt_token: 1.5e-7,
      completion_token: 3.5e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/o4-mini-high",
    },
    cost: {
      prompt_token: 1.1e-6,
      completion_token: 4.4e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/o3",
    },
    cost: {
      prompt_token: 1e-5,
      completion_token: 4e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/o4-mini",
    },
    cost: {
      prompt_token: 1.1e-6,
      completion_token: 4.4e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "shisa-ai/shisa-v2-llama3.3-70b:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen2.5-coder-7b-instruct",
    },
    cost: {
      prompt_token: 2e-7,
      completion_token: 2e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-4.1",
    },
    cost: {
      prompt_token: 2e-6,
      completion_token: 8e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-4.1-mini",
    },
    cost: {
      prompt_token: 4e-7,
      completion_token: 1.6e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-4.1-nano",
    },
    cost: {
      prompt_token: 1e-7,
      completion_token: 4e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "eleutherai/llemma_7b",
    },
    cost: {
      prompt_token: 8e-7,
      completion_token: 1.2e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "alfredpros/codellama-7b-instruct-solidity",
    },
    cost: {
      prompt_token: 8e-7,
      completion_token: 1.2e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "arliai/qwq-32b-arliai-rpr-v1:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "agentica-org/deepcoder-14b-preview:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "moonshotai/kimi-vl-a3b-thinking:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "x-ai/grok-3-mini-beta",
    },
    cost: {
      prompt_token: 3e-7,
      completion_token: 5e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "x-ai/grok-3-beta",
    },
    cost: {
      prompt_token: 3e-6,
      completion_token: 1.5e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "nvidia/llama-3.1-nemotron-nano-8b-v1:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "nvidia/llama-3.3-nemotron-super-49b-v1:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "nvidia/llama-3.1-nemotron-ultra-253b-v1:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "meta-llama/llama-4-maverick:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "meta-llama/llama-4-maverick",
    },
    cost: {
      prompt_token: 1.7e-7,
      completion_token: 8.5e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "meta-llama/llama-4-scout:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "meta-llama/llama-4-scout",
    },
    cost: {
      prompt_token: 8e-8,
      completion_token: 3e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "all-hands/openhands-lm-32b-v0.1",
    },
    cost: {
      prompt_token: 2.6e-6,
      completion_token: 3.4e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistral/ministral-8b",
    },
    cost: {
      prompt_token: 1e-7,
      completion_token: 1e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "deepseek/deepseek-v3-base:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "scb10x/llama3.1-typhoon2-8b-instruct",
    },
    cost: {
      prompt_token: 1.8e-7,
      completion_token: 1.8e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "scb10x/llama3.1-typhoon2-70b-instruct",
    },
    cost: {
      prompt_token: 8.8e-7,
      completion_token: 8.8e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "allenai/molmo-7b-d:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "bytedance-research/ui-tars-72b:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen2.5-vl-3b-instruct:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "google/gemini-2.5-pro-exp-03-25:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen2.5-vl-32b-instruct:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen2.5-vl-32b-instruct",
    },
    cost: {
      prompt_token: 9e-7,
      completion_token: 9e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "deepseek/deepseek-chat-v3-0324:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "deepseek/deepseek-chat-v3-0324",
    },
    cost: {
      prompt_token: 2.7e-7,
      completion_token: 1.1e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "featherless/qwerky-72b:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/o1-pro",
    },
    cost: {
      prompt_token: 0.00015,
      completion_token: 0.0006,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/mistral-small-3.1-24b-instruct:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/mistral-small-3.1-24b-instruct",
    },
    cost: {
      prompt_token: 1e-7,
      completion_token: 3e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "open-r1/olympiccoder-7b:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "open-r1/olympiccoder-32b:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "steelskull/l3.3-electra-r1-70b",
    },
    cost: {
      prompt_token: 7e-7,
      completion_token: 9.5e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "google/gemma-3-1b-it:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "google/gemma-3-4b-it:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "google/gemma-3-4b-it",
    },
    cost: {
      prompt_token: 2e-8,
      completion_token: 4e-8,
    },
  },
  {
    model: {
      operator: "equals",
      value: "ai21/jamba-1.6-large",
    },
    cost: {
      prompt_token: 2e-6,
      completion_token: 8e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "ai21/jamba-1.6-mini",
    },
    cost: {
      prompt_token: 2e-7,
      completion_token: 4e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "google/gemma-3-12b-it:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "google/gemma-3-12b-it",
    },
    cost: {
      prompt_token: 5e-8,
      completion_token: 1e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "cohere/command-a",
    },
    cost: {
      prompt_token: 2.5e-6,
      completion_token: 1e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-4o-mini-search-preview",
    },
    cost: {
      prompt_token: 1.5e-7,
      completion_token: 6e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-4o-search-preview",
    },
    cost: {
      prompt_token: 2.5e-6,
      completion_token: 1e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "rekaai/reka-flash-3:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "google/gemma-3-27b-it:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "google/gemma-3-27b-it",
    },
    cost: {
      prompt_token: 1e-7,
      completion_token: 2e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "thedrummer/anubis-pro-105b-v1",
    },
    cost: {
      prompt_token: 8e-7,
      completion_token: 1e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "latitudegames/wayfarer-large-70b-llama-3.3",
    },
    cost: {
      prompt_token: 8e-7,
      completion_token: 9e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "thedrummer/skyfall-36b-v2",
    },
    cost: {
      prompt_token: 5e-7,
      completion_token: 8e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "microsoft/phi-4-multimodal-instruct",
    },
    cost: {
      prompt_token: 5e-8,
      completion_token: 1e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "perplexity/sonar-reasoning-pro",
    },
    cost: {
      prompt_token: 2e-6,
      completion_token: 8e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "perplexity/sonar-pro",
    },
    cost: {
      prompt_token: 3e-6,
      completion_token: 1.5e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "perplexity/sonar-deep-research",
    },
    cost: {
      prompt_token: 2e-6,
      completion_token: 8e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "deepseek/deepseek-r1-zero:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwq-32b:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwq-32b",
    },
    cost: {
      prompt_token: 1.5e-7,
      completion_token: 2e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "moonshotai/moonlight-16b-a3b-instruct:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "nousresearch/deephermes-3-llama-3-8b-preview:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-4.5-preview",
    },
    cost: {
      prompt_token: 7.5e-5,
      completion_token: 0.00015,
    },
  },
  {
    model: {
      operator: "equals",
      value: "google/gemini-2.0-flash-lite-001",
    },
    cost: {
      prompt_token: 7.5e-8,
      completion_token: 3e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "anthropic/claude-3.7-sonnet",
    },
    cost: {
      prompt_token: 3e-6,
      completion_token: 1.5e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "anthropic/claude-3.7-sonnet:thinking",
    },
    cost: {
      prompt_token: 3e-6,
      completion_token: 1.5e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "anthropic/claude-3.7-sonnet:beta",
    },
    cost: {
      prompt_token: 3e-6,
      completion_token: 1.5e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "perplexity/r1-1776",
    },
    cost: {
      prompt_token: 2e-6,
      completion_token: 8e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/mistral-saba",
    },
    cost: {
      prompt_token: 2e-7,
      completion_token: 6e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "cognitivecomputations/dolphin3.0-r1-mistral-24b:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "cognitivecomputations/dolphin3.0-mistral-24b:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "meta-llama/llama-guard-3-8b",
    },
    cost: {
      prompt_token: 1e-7,
      completion_token: 1e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/o3-mini-high",
    },
    cost: {
      prompt_token: 1.1e-6,
      completion_token: 4.4e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "deepseek/deepseek-r1-distill-llama-8b",
    },
    cost: {
      prompt_token: 4e-8,
      completion_token: 4e-8,
    },
  },
  {
    model: {
      operator: "equals",
      value: "google/gemini-2.0-flash-001",
    },
    cost: {
      prompt_token: 1e-7,
      completion_token: 4e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen-vl-plus",
    },
    cost: {
      prompt_token: 2.1e-7,
      completion_token: 6.3e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "aion-labs/aion-1.0",
    },
    cost: {
      prompt_token: 4e-6,
      completion_token: 8e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "aion-labs/aion-1.0-mini",
    },
    cost: {
      prompt_token: 7e-7,
      completion_token: 1.4e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "aion-labs/aion-rp-llama-3.1-8b",
    },
    cost: {
      prompt_token: 2e-7,
      completion_token: 2e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen-vl-max",
    },
    cost: {
      prompt_token: 8e-7,
      completion_token: 3.2e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen-turbo",
    },
    cost: {
      prompt_token: 5e-8,
      completion_token: 2e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen2.5-vl-72b-instruct:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen2.5-vl-72b-instruct",
    },
    cost: {
      prompt_token: 7e-7,
      completion_token: 7e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen-plus",
    },
    cost: {
      prompt_token: 4e-7,
      completion_token: 1.2e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen-max",
    },
    cost: {
      prompt_token: 1.6e-6,
      completion_token: 6.4e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/o3-mini",
    },
    cost: {
      prompt_token: 1.1e-6,
      completion_token: 4.4e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "deepseek/deepseek-r1-distill-qwen-1.5b",
    },
    cost: {
      prompt_token: 1.8e-7,
      completion_token: 1.8e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/mistral-small-24b-instruct-2501:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/mistral-small-24b-instruct-2501",
    },
    cost: {
      prompt_token: 7e-8,
      completion_token: 1.4e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "deepseek/deepseek-r1-distill-qwen-32b:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "deepseek/deepseek-r1-distill-qwen-32b",
    },
    cost: {
      prompt_token: 1.2e-7,
      completion_token: 1.8e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "deepseek/deepseek-r1-distill-qwen-14b:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "deepseek/deepseek-r1-distill-qwen-14b",
    },
    cost: {
      prompt_token: 1.5e-7,
      completion_token: 1.5e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "perplexity/sonar-reasoning",
    },
    cost: {
      prompt_token: 1e-6,
      completion_token: 5e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "perplexity/sonar",
    },
    cost: {
      prompt_token: 1e-6,
      completion_token: 1e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "liquid/lfm-7b",
    },
    cost: {
      prompt_token: 1e-8,
      completion_token: 1e-8,
    },
  },
  {
    model: {
      operator: "equals",
      value: "liquid/lfm-3b",
    },
    cost: {
      prompt_token: 2e-8,
      completion_token: 2e-8,
    },
  },
  {
    model: {
      operator: "equals",
      value: "deepseek/deepseek-r1-distill-llama-70b:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "deepseek/deepseek-r1-distill-llama-70b",
    },
    cost: {
      prompt_token: 1e-7,
      completion_token: 4e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "google/gemini-2.0-flash-thinking-exp:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "deepseek/deepseek-r1:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "deepseek/deepseek-r1",
    },
    cost: {
      prompt_token: 5e-7,
      completion_token: 3e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "sophosympatheia/rogue-rose-103b-v0.2:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "minimax/minimax-01",
    },
    cost: {
      prompt_token: 2e-7,
      completion_token: 1.1e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/codestral-2501",
    },
    cost: {
      prompt_token: 3e-7,
      completion_token: 9e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "microsoft/phi-4",
    },
    cost: {
      prompt_token: 7e-8,
      completion_token: 1.4e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "deepseek/deepseek-chat:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "deepseek/deepseek-chat",
    },
    cost: {
      prompt_token: 3.8e-7,
      completion_token: 8.9e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "google/gemini-2.0-flash-thinking-exp-1219:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "sao10k/l3.3-euryale-70b",
    },
    cost: {
      prompt_token: 7e-7,
      completion_token: 8e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/o1",
    },
    cost: {
      prompt_token: 1.5e-5,
      completion_token: 6e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "eva-unit-01/eva-llama-3.33-70b",
    },
    cost: {
      prompt_token: 4e-6,
      completion_token: 6e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "x-ai/grok-2-vision-1212",
    },
    cost: {
      prompt_token: 2e-6,
      completion_token: 1e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "x-ai/grok-2-1212",
    },
    cost: {
      prompt_token: 2e-6,
      completion_token: 1e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "cohere/command-r7b-12-2024",
    },
    cost: {
      prompt_token: 3.75e-8,
      completion_token: 1.5e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "google/gemini-2.0-flash-exp:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "meta-llama/llama-3.3-70b-instruct:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "meta-llama/llama-3.3-70b-instruct",
    },
    cost: {
      prompt_token: 1e-7,
      completion_token: 2.5e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "amazon/nova-lite-v1",
    },
    cost: {
      prompt_token: 6e-8,
      completion_token: 2.4e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "amazon/nova-micro-v1",
    },
    cost: {
      prompt_token: 3.5e-8,
      completion_token: 1.4e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "amazon/nova-pro-v1",
    },
    cost: {
      prompt_token: 8e-7,
      completion_token: 3.2e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwq-32b-preview:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwq-32b-preview",
    },
    cost: {
      prompt_token: 2e-7,
      completion_token: 2e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "google/learnlm-1.5-pro-experimental:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "eva-unit-01/eva-qwen-2.5-72b",
    },
    cost: {
      prompt_token: 9e-7,
      completion_token: 1.2e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-4o-2024-11-20",
    },
    cost: {
      prompt_token: 2.5e-6,
      completion_token: 1e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/mistral-large-2411",
    },
    cost: {
      prompt_token: 2e-6,
      completion_token: 6e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/mistral-large-2407",
    },
    cost: {
      prompt_token: 2e-6,
      completion_token: 6e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/pixtral-large-2411",
    },
    cost: {
      prompt_token: 2e-6,
      completion_token: 6e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "x-ai/grok-vision-beta",
    },
    cost: {
      prompt_token: 5e-6,
      completion_token: 1.5e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "infermatic/mn-inferor-12b",
    },
    cost: {
      prompt_token: 8e-7,
      completion_token: 1.2e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen-2.5-coder-32b-instruct:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen-2.5-coder-32b-instruct",
    },
    cost: {
      prompt_token: 7e-8,
      completion_token: 1.5e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "raifle/sorcererlm-8x22b",
    },
    cost: {
      prompt_token: 4.5e-6,
      completion_token: 4.5e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "eva-unit-01/eva-qwen-2.5-32b",
    },
    cost: {
      prompt_token: 2.6e-6,
      completion_token: 3.4e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "thedrummer/unslopnemo-12b",
    },
    cost: {
      prompt_token: 5e-7,
      completion_token: 5e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "anthropic/claude-3.5-haiku:beta",
    },
    cost: {
      prompt_token: 8e-7,
      completion_token: 4e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "anthropic/claude-3.5-haiku",
    },
    cost: {
      prompt_token: 8e-7,
      completion_token: 4e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "anthropic/claude-3.5-haiku-20241022:beta",
    },
    cost: {
      prompt_token: 8e-7,
      completion_token: 4e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "anthropic/claude-3.5-haiku-20241022",
    },
    cost: {
      prompt_token: 8e-7,
      completion_token: 4e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "neversleep/llama-3.1-lumimaid-70b",
    },
    cost: {
      prompt_token: 1.5e-6,
      completion_token: 2.25e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "anthracite-org/magnum-v4-72b",
    },
    cost: {
      prompt_token: 1.5e-6,
      completion_token: 2.25e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "anthropic/claude-3.5-sonnet:beta",
    },
    cost: {
      prompt_token: 3e-6,
      completion_token: 1.5e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "anthropic/claude-3.5-sonnet",
    },
    cost: {
      prompt_token: 3e-6,
      completion_token: 1.5e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "x-ai/grok-beta",
    },
    cost: {
      prompt_token: 5e-6,
      completion_token: 1.5e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/ministral-8b",
    },
    cost: {
      prompt_token: 1e-7,
      completion_token: 1e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/ministral-3b",
    },
    cost: {
      prompt_token: 4e-8,
      completion_token: 4e-8,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen-2.5-7b-instruct:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen-2.5-7b-instruct",
    },
    cost: {
      prompt_token: 5e-8,
      completion_token: 1e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "nvidia/llama-3.1-nemotron-70b-instruct:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "nvidia/llama-3.1-nemotron-70b-instruct",
    },
    cost: {
      prompt_token: 1.2e-7,
      completion_token: 3e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "inflection/inflection-3-productivity",
    },
    cost: {
      prompt_token: 2.5e-6,
      completion_token: 1e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "inflection/inflection-3-pi",
    },
    cost: {
      prompt_token: 2.5e-6,
      completion_token: 1e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "google/gemini-flash-1.5-8b",
    },
    cost: {
      prompt_token: 3.75e-8,
      completion_token: 1.5e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "thedrummer/rocinante-12b",
    },
    cost: {
      prompt_token: 2.5e-7,
      completion_token: 5e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "anthracite-org/magnum-v2-72b",
    },
    cost: {
      prompt_token: 3e-6,
      completion_token: 3e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "liquid/lfm-40b",
    },
    cost: {
      prompt_token: 1.5e-7,
      completion_token: 1.5e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "meta-llama/llama-3.2-3b-instruct:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "meta-llama/llama-3.2-3b-instruct",
    },
    cost: {
      prompt_token: 1.5e-8,
      completion_token: 2.5e-8,
    },
  },
  {
    model: {
      operator: "equals",
      value: "meta-llama/llama-3.2-1b-instruct:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "meta-llama/llama-3.2-1b-instruct",
    },
    cost: {
      prompt_token: 1e-8,
      completion_token: 1e-8,
    },
  },
  {
    model: {
      operator: "equals",
      value: "meta-llama/llama-3.2-90b-vision-instruct",
    },
    cost: {
      prompt_token: 9e-7,
      completion_token: 9e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "meta-llama/llama-3.2-11b-vision-instruct:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "meta-llama/llama-3.2-11b-vision-instruct",
    },
    cost: {
      prompt_token: 4.9e-8,
      completion_token: 4.9e-8,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen-2.5-72b-instruct:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen-2.5-72b-instruct",
    },
    cost: {
      prompt_token: 1.2e-7,
      completion_token: 3.9e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen-2.5-vl-72b-instruct",
    },
    cost: {
      prompt_token: 6e-7,
      completion_token: 6e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "neversleep/llama-3.1-lumimaid-8b",
    },
    cost: {
      prompt_token: 9.375e-8,
      completion_token: 7.5e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/o1-preview",
    },
    cost: {
      prompt_token: 1.5e-5,
      completion_token: 6e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/o1-preview-2024-09-12",
    },
    cost: {
      prompt_token: 1.5e-5,
      completion_token: 6e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/o1-mini",
    },
    cost: {
      prompt_token: 1.1e-6,
      completion_token: 4.4e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/o1-mini-2024-09-12",
    },
    cost: {
      prompt_token: 1.1e-6,
      completion_token: 4.4e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/pixtral-12b",
    },
    cost: {
      prompt_token: 1e-7,
      completion_token: 1e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "cohere/command-r-plus-08-2024",
    },
    cost: {
      prompt_token: 2.5e-6,
      completion_token: 1e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "cohere/command-r-08-2024",
    },
    cost: {
      prompt_token: 1.5e-7,
      completion_token: 6e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen-2.5-vl-7b-instruct:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen-2.5-vl-7b-instruct",
    },
    cost: {
      prompt_token: 2e-7,
      completion_token: 2e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "sao10k/l3.1-euryale-70b",
    },
    cost: {
      prompt_token: 7e-7,
      completion_token: 8e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "google/gemini-flash-1.5-8b-exp",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "ai21/jamba-1-5-mini",
    },
    cost: {
      prompt_token: 2e-7,
      completion_token: 4e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "ai21/jamba-1-5-large",
    },
    cost: {
      prompt_token: 2e-6,
      completion_token: 8e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "microsoft/phi-3.5-mini-128k-instruct",
    },
    cost: {
      prompt_token: 1e-7,
      completion_token: 1e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "nousresearch/hermes-3-llama-3.1-70b",
    },
    cost: {
      prompt_token: 1.2e-7,
      completion_token: 3e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "nousresearch/hermes-3-llama-3.1-405b",
    },
    cost: {
      prompt_token: 8e-7,
      completion_token: 8e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/chatgpt-4o-latest",
    },
    cost: {
      prompt_token: 5e-6,
      completion_token: 1.5e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "sao10k/l3-lunaris-8b",
    },
    cost: {
      prompt_token: 2e-8,
      completion_token: 5e-8,
    },
  },
  {
    model: {
      operator: "equals",
      value: "aetherwiing/mn-starcannon-12b",
    },
    cost: {
      prompt_token: 8e-7,
      completion_token: 1.2e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-4o-2024-08-06",
    },
    cost: {
      prompt_token: 2.5e-6,
      completion_token: 1e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "meta-llama/llama-3.1-405b:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "meta-llama/llama-3.1-405b",
    },
    cost: {
      prompt_token: 2e-6,
      completion_token: 2e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "nothingiisreal/mn-celeste-12b",
    },
    cost: {
      prompt_token: 8e-7,
      completion_token: 1.2e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "perplexity/llama-3.1-sonar-small-128k-online",
    },
    cost: {
      prompt_token: 2e-7,
      completion_token: 2e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "perplexity/llama-3.1-sonar-large-128k-online",
    },
    cost: {
      prompt_token: 1e-6,
      completion_token: 1e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "meta-llama/llama-3.1-8b-instruct:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "meta-llama/llama-3.1-8b-instruct",
    },
    cost: {
      prompt_token: 2e-8,
      completion_token: 3e-8,
    },
  },
  {
    model: {
      operator: "equals",
      value: "meta-llama/llama-3.1-405b-instruct",
    },
    cost: {
      prompt_token: 8e-7,
      completion_token: 8e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "meta-llama/llama-3.1-70b-instruct",
    },
    cost: {
      prompt_token: 1.19e-7,
      completion_token: 3.9e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/codestral-mamba",
    },
    cost: {
      prompt_token: 2.5e-7,
      completion_token: 2.5e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/mistral-nemo:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/mistral-nemo",
    },
    cost: {
      prompt_token: 3.5e-8,
      completion_token: 8e-8,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-4o-mini",
    },
    cost: {
      prompt_token: 1.5e-7,
      completion_token: 6e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-4o-mini-2024-07-18",
    },
    cost: {
      prompt_token: 1.5e-7,
      completion_token: 6e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "google/gemma-2-27b-it",
    },
    cost: {
      prompt_token: 8e-7,
      completion_token: 8e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "alpindale/magnum-72b",
    },
    cost: {
      prompt_token: 1.5e-6,
      completion_token: 2.25e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "google/gemma-2-9b-it:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "google/gemma-2-9b-it",
    },
    cost: {
      prompt_token: 7e-8,
      completion_token: 7e-8,
    },
  },
  {
    model: {
      operator: "equals",
      value: "01-ai/yi-large",
    },
    cost: {
      prompt_token: 3e-6,
      completion_token: 3e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "ai21/jamba-instruct",
    },
    cost: {
      prompt_token: 5e-7,
      completion_token: 7e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "anthropic/claude-3.5-sonnet-20240620:beta",
    },
    cost: {
      prompt_token: 3e-6,
      completion_token: 1.5e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "anthropic/claude-3.5-sonnet-20240620",
    },
    cost: {
      prompt_token: 3e-6,
      completion_token: 1.5e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "sao10k/l3-euryale-70b",
    },
    cost: {
      prompt_token: 1.48e-6,
      completion_token: 1.48e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "cognitivecomputations/dolphin-mixtral-8x22b",
    },
    cost: {
      prompt_token: 9e-7,
      completion_token: 9e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen-2-72b-instruct",
    },
    cost: {
      prompt_token: 9e-7,
      completion_token: 9e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/mistral-7b-instruct:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/mistral-7b-instruct",
    },
    cost: {
      prompt_token: 2.9e-8,
      completion_token: 5.9e-8,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/mistral-7b-instruct-v0.3",
    },
    cost: {
      prompt_token: 2.9e-8,
      completion_token: 5.9e-8,
    },
  },
  {
    model: {
      operator: "equals",
      value: "nousresearch/hermes-2-pro-llama-3-8b",
    },
    cost: {
      prompt_token: 2.5e-8,
      completion_token: 4e-8,
    },
  },
  {
    model: {
      operator: "equals",
      value: "microsoft/phi-3-mini-128k-instruct",
    },
    cost: {
      prompt_token: 1e-7,
      completion_token: 1e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "microsoft/phi-3-medium-128k-instruct",
    },
    cost: {
      prompt_token: 1e-6,
      completion_token: 1e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "neversleep/llama-3-lumimaid-70b",
    },
    cost: {
      prompt_token: 3.375e-6,
      completion_token: 4.5e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "google/gemini-flash-1.5",
    },
    cost: {
      prompt_token: 7.5e-8,
      completion_token: 3e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-4o",
    },
    cost: {
      prompt_token: 2.5e-6,
      completion_token: 1e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-4o:extended",
    },
    cost: {
      prompt_token: 6e-6,
      completion_token: 1.8e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-4o-2024-05-13",
    },
    cost: {
      prompt_token: 5e-6,
      completion_token: 1.5e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "meta-llama/llama-guard-2-8b",
    },
    cost: {
      prompt_token: 2e-7,
      completion_token: 2e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "neversleep/llama-3-lumimaid-8b:extended",
    },
    cost: {
      prompt_token: 9.375e-8,
      completion_token: 7.5e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "neversleep/llama-3-lumimaid-8b",
    },
    cost: {
      prompt_token: 9.375e-8,
      completion_token: 7.5e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "sao10k/fimbulvetr-11b-v2",
    },
    cost: {
      prompt_token: 8e-7,
      completion_token: 1.2e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "meta-llama/llama-3-8b-instruct",
    },
    cost: {
      prompt_token: 3e-8,
      completion_token: 6e-8,
    },
  },
  {
    model: {
      operator: "equals",
      value: "meta-llama/llama-3-70b-instruct",
    },
    cost: {
      prompt_token: 3e-7,
      completion_token: 4e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/mixtral-8x22b-instruct",
    },
    cost: {
      prompt_token: 9e-7,
      completion_token: 9e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "microsoft/wizardlm-2-8x22b",
    },
    cost: {
      prompt_token: 5e-7,
      completion_token: 5e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "microsoft/wizardlm-2-7b",
    },
    cost: {
      prompt_token: 7e-8,
      completion_token: 7e-8,
    },
  },
  {
    model: {
      operator: "equals",
      value: "google/gemini-pro-1.5",
    },
    cost: {
      prompt_token: 1.25e-6,
      completion_token: 5e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-4-turbo",
    },
    cost: {
      prompt_token: 1e-5,
      completion_token: 3e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "cohere/command-r-plus",
    },
    cost: {
      prompt_token: 3e-6,
      completion_token: 1.5e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "cohere/command-r-plus-04-2024",
    },
    cost: {
      prompt_token: 3e-6,
      completion_token: 1.5e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "sophosympatheia/midnight-rose-70b",
    },
    cost: {
      prompt_token: 8e-7,
      completion_token: 8e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "cohere/command",
    },
    cost: {
      prompt_token: 1e-6,
      completion_token: 2e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "cohere/command-r",
    },
    cost: {
      prompt_token: 5e-7,
      completion_token: 1.5e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "anthropic/claude-3-haiku:beta",
    },
    cost: {
      prompt_token: 2.5e-7,
      completion_token: 1.25e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "anthropic/claude-3-haiku",
    },
    cost: {
      prompt_token: 2.5e-7,
      completion_token: 1.25e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "anthropic/claude-3-opus:beta",
    },
    cost: {
      prompt_token: 1.5e-5,
      completion_token: 7.5e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "anthropic/claude-3-opus",
    },
    cost: {
      prompt_token: 1.5e-5,
      completion_token: 7.5e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "anthropic/claude-3-sonnet:beta",
    },
    cost: {
      prompt_token: 3e-6,
      completion_token: 1.5e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "anthropic/claude-3-sonnet",
    },
    cost: {
      prompt_token: 3e-6,
      completion_token: 1.5e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "cohere/command-r-03-2024",
    },
    cost: {
      prompt_token: 5e-7,
      completion_token: 1.5e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/mistral-large",
    },
    cost: {
      prompt_token: 2e-6,
      completion_token: 6e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-3.5-turbo-0613",
    },
    cost: {
      prompt_token: 1e-6,
      completion_token: 2e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-4-turbo-preview",
    },
    cost: {
      prompt_token: 1e-5,
      completion_token: 3e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "nousresearch/nous-hermes-2-mixtral-8x7b-dpo",
    },
    cost: {
      prompt_token: 6e-7,
      completion_token: 6e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/mistral-medium",
    },
    cost: {
      prompt_token: 2.75e-6,
      completion_token: 8.1e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/mistral-small",
    },
    cost: {
      prompt_token: 2e-7,
      completion_token: 6e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/mistral-tiny",
    },
    cost: {
      prompt_token: 2.5e-7,
      completion_token: 2.5e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/mistral-7b-instruct-v0.2",
    },
    cost: {
      prompt_token: 2e-7,
      completion_token: 2e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "cognitivecomputations/dolphin-mixtral-8x7b",
    },
    cost: {
      prompt_token: 5e-7,
      completion_token: 5e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "google/gemini-pro-vision",
    },
    cost: {
      prompt_token: 5e-7,
      completion_token: 1.5e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "google/gemini-pro",
    },
    cost: {
      prompt_token: 5e-7,
      completion_token: 1.5e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/mixtral-8x7b-instruct",
    },
    cost: {
      prompt_token: 2.4e-7,
      completion_token: 2.4e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openchat/openchat-7b",
    },
    cost: {
      prompt_token: 7e-8,
      completion_token: 7e-8,
    },
  },
  {
    model: {
      operator: "equals",
      value: "neversleep/noromaid-20b",
    },
    cost: {
      prompt_token: 7.5e-7,
      completion_token: 1.5e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "anthropic/claude-2.1:beta",
    },
    cost: {
      prompt_token: 8e-6,
      completion_token: 2.4e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "anthropic/claude-2.1",
    },
    cost: {
      prompt_token: 8e-6,
      completion_token: 2.4e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "anthropic/claude-2:beta",
    },
    cost: {
      prompt_token: 8e-6,
      completion_token: 2.4e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "anthropic/claude-2",
    },
    cost: {
      prompt_token: 8e-6,
      completion_token: 2.4e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "undi95/toppy-m-7b",
    },
    cost: {
      prompt_token: 7e-8,
      completion_token: 7e-8,
    },
  },
  {
    model: {
      operator: "equals",
      value: "alpindale/goliath-120b",
    },
    cost: {
      prompt_token: 6.5625e-6,
      completion_token: 9.375e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openrouter/auto",
    },
    cost: {
      prompt_token: -1.0,
      completion_token: -1.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-3.5-turbo-1106",
    },
    cost: {
      prompt_token: 1e-6,
      completion_token: 2e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-4-1106-preview",
    },
    cost: {
      prompt_token: 1e-5,
      completion_token: 3e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "google/palm-2-chat-bison-32k",
    },
    cost: {
      prompt_token: 1e-6,
      completion_token: 2e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "google/palm-2-codechat-bison-32k",
    },
    cost: {
      prompt_token: 1e-6,
      completion_token: 2e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "jondurbin/airoboros-l2-70b",
    },
    cost: {
      prompt_token: 5e-7,
      completion_token: 5e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "xwin-lm/xwin-lm-70b",
    },
    cost: {
      prompt_token: 3.75e-6,
      completion_token: 3.75e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-3.5-turbo-instruct",
    },
    cost: {
      prompt_token: 1.5e-6,
      completion_token: 2e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/mistral-7b-instruct-v0.1",
    },
    cost: {
      prompt_token: 2e-7,
      completion_token: 2e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "pygmalionai/mythalion-13b",
    },
    cost: {
      prompt_token: 5.625e-7,
      completion_token: 1.125e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-3.5-turbo-16k",
    },
    cost: {
      prompt_token: 3e-6,
      completion_token: 4e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-4-32k",
    },
    cost: {
      prompt_token: 6e-5,
      completion_token: 0.00012,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-4-32k-0314",
    },
    cost: {
      prompt_token: 6e-5,
      completion_token: 0.00012,
    },
  },
  {
    model: {
      operator: "equals",
      value: "nousresearch/nous-hermes-llama2-13b",
    },
    cost: {
      prompt_token: 1.8e-7,
      completion_token: 1.8e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mancer/weaver",
    },
    cost: {
      prompt_token: 1.125e-6,
      completion_token: 1.125e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "huggingfaceh4/zephyr-7b-beta:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "anthropic/claude-2.0:beta",
    },
    cost: {
      prompt_token: 8e-6,
      completion_token: 2.4e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "anthropic/claude-2.0",
    },
    cost: {
      prompt_token: 8e-6,
      completion_token: 2.4e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "undi95/remm-slerp-l2-13b",
    },
    cost: {
      prompt_token: 5.625e-7,
      completion_token: 1.125e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "google/palm-2-chat-bison",
    },
    cost: {
      prompt_token: 1e-6,
      completion_token: 2e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "google/palm-2-codechat-bison",
    },
    cost: {
      prompt_token: 1e-6,
      completion_token: 2e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "gryphe/mythomax-l2-13b",
    },
    cost: {
      prompt_token: 6.5e-8,
      completion_token: 6.5e-8,
    },
  },
  {
    model: {
      operator: "equals",
      value: "meta-llama/llama-2-13b-chat",
    },
    cost: {
      prompt_token: 2.2e-7,
      completion_token: 2.2e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "meta-llama/llama-2-70b-chat",
    },
    cost: {
      prompt_token: 9e-7,
      completion_token: 9e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-3.5-turbo",
    },
    cost: {
      prompt_token: 5e-7,
      completion_token: 1.5e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-3.5-turbo-0125",
    },
    cost: {
      prompt_token: 5e-7,
      completion_token: 1.5e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-4",
    },
    cost: {
      prompt_token: 3e-5,
      completion_token: 6e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-4-0314",
    },
    cost: {
      prompt_token: 3e-5,
      completion_token: 6e-5,
    },
  },
];
