import { ProviderName } from "../../../providers";
import type { ModelProviderConfig } from "../../../types";
import { Gemini25ModelName } from "./models";

export const endpoints = {
  "gemini-2.5-flash-lite:google": {
    providerModelId: "gemini-2.5-flash-lite",
    provider: "google",
    pricing: {
      prompt: 0.0000001,
      completion: 0.0000004,
      request: 0,
      image: 0,
      audio: 0,
      web_search: 0,
      internal_reasoning: 0,
      cacheRead: 0.000000025,
      cacheWrite: 0.0000001833,
    },
    contextLength: 1048576,
    maxCompletionTokens: 65535,
    supportedParameters: [
      "include_reasoning",
      "max_tokens",
      "reasoning",
      "response_format",
      "seed",
      "stop",
      "structured_outputs",
      "temperature",
      "tool_choice",
      "tools",
      "top_p",
    ],
    ptbEnabled: false,
    endpointConfigs: {
      "*": {},
    },
  },
  "gemini-2.5-flash-lite-preview:google": {
    providerModelId: "gemini-2.5-flash-lite-preview",
    provider: "google",
    pricing: {
      prompt: 0.0000001,
      completion: 0.0000004,
      request: 0,
      image: 0,
      audio: 0,
      web_search: 0,
      internal_reasoning: 0,
      cacheRead: 0.000000025,
      cacheWrite: 0.0000001833,
    },
    contextLength: 1048576,
    maxCompletionTokens: 65535,
    supportedParameters: [
      "include_reasoning",
      "max_tokens",
      "reasoning",
      "response_format",
      "seed",
      "stop",
      "structured_outputs",
      "temperature",
      "tool_choice",
      "tools",
      "top_p",
    ],
    ptbEnabled: false,
    endpointConfigs: {
      "*": {},
    },
  },
  "gemini-2.5-flash:google": {
    providerModelId: "gemini-2.5-flash",
    provider: "google",
    pricing: {
      prompt: 0.0000003,
      completion: 0.0000025,
      request: 0,
      image: 0.001238,
      audio: 0,
      web_search: 0,
      internal_reasoning: 0,
      cacheRead: 0.000000075,
      cacheWrite: 0.0000003833,
    },
    contextLength: 1048576,
    maxCompletionTokens: 65535,
    supportedParameters: [
      "include_reasoning",
      "max_tokens",
      "reasoning",
      "response_format",
      "seed",
      "stop",
      "structured_outputs",
      "temperature",
      "tool_choice",
      "tools",
      "top_p",
    ],
    ptbEnabled: false,
    endpointConfigs: {
      "*": {},
    },
  },
  "gemini-2.5-pro:google": {
    providerModelId: "gemini-2.5-pro",
    provider: "google",
    pricing: {
      prompt: 0.00000125,
      completion: 0.00001,
      request: 0,
      image: 0.00516,
      audio: 0,
      web_search: 0,
      internal_reasoning: 0,
      cacheRead: 0.00000031,
      cacheWrite: 0.000001625,
    },
    contextLength: 1048576,
    maxCompletionTokens: 65536,
    supportedParameters: [
      "include_reasoning",
      "max_tokens",
      "reasoning",
      "response_format",
      "seed",
      "stop",
      "structured_outputs",
      "temperature",
      "tool_choice",
      "tools",
      "top_p",
    ],
    ptbEnabled: false,
    endpointConfigs: {
      "*": {},
    },
  },
  "gemini-2.5-pro-preview:google": {
    providerModelId: "gemini-2.5-pro-preview",
    provider: "google",
    pricing: {
      prompt: 0.00000125,
      completion: 0.00001,
      request: 0,
      image: 0.00516,
      audio: 0,
      web_search: 0,
      internal_reasoning: 0,
      cacheRead: 0.00000031,
      cacheWrite: 0.000001625,
    },
    contextLength: 1048576,
    maxCompletionTokens: 65536,
    supportedParameters: [
      "include_reasoning",
      "max_tokens",
      "reasoning",
      "response_format",
      "seed",
      "stop",
      "structured_outputs",
      "temperature",
      "tool_choice",
      "tools",
      "top_p",
    ],
    ptbEnabled: false,
    endpointConfigs: {
      "*": {},
    },
  },
  "gemini-2.5-pro-exp:google": {
    providerModelId: "gemini-2.5-pro-exp-03-25",
    provider: "google",
    pricing: {
      prompt: 0,
      completion: 0,
      request: 0,
      image: 0,
      audio: 0,
      web_search: 0,
      internal_reasoning: 0,
    },
    contextLength: 1048576,
    maxCompletionTokens: 65535,
    supportedParameters: [
      "max_tokens",
      "response_format",
      "seed",
      "stop",
      "structured_outputs",
      "temperature",
      "tool_choice",
      "tools",
      "top_p",
    ],
    ptbEnabled: false,
    endpointConfigs: {
      "*": {},
    },
  },
} satisfies Partial<
  Record<`${Gemini25ModelName}:${ProviderName}`, ModelProviderConfig>
>;
