/**
 *
 * DO NOT EDIT THIS FILE UNLESS IT IS IN /costs
 */

import { ModelRow } from "../../interfaces/Cost";

export const costs: ModelRow[] = [
  {
    model: {
      operator: "equals",
      value: "deepseek-chat",
    },
    cost: {
      prompt_token: 0.000000014,
      completion_token: 0.000000028,
    },
  },
];
