import { ModelProviderName } from "../../../providers";
import type { ModelProviderConfig } from "../../../types";
import { LlamaModelName } from "./models";

export const endpoints = {
  "llama-4-scout:groq": {
    providerModelId: "meta-llama/Llama-4-Scout-17B-16E-Instruct",
    provider: "groq",
    author: "meta-llama",
    pricing: [
      {
        threshold: 0,
        input: 0.00000011,
        output: 0.00000034,
        request: 0.0,
        image: 0.0,
        audio: 0.0,
        web_search: 0.0,
      },
    ],
    contextLength: 131_072,
    maxCompletionTokens: 8_192,
    supportedParameters: [
      "max_tokens",
      "repetition_penalty",
      "response_format",
      "structured_outputs",
      "temperature",
      "tool_choice",
      "tools",
      "top_k",
      "top_p",
    ],
    ptbEnabled: true,
    endpointConfigs: {
      "*": {},
    },
  },
  "llama-4-maverick:groq": {
    providerModelId: "meta-llama/Llama-4-Maverick-17B-128E-Instruct",
    provider: "groq",
    author: "meta-llama",
    pricing: [
      {
        threshold: 0,
        input: 0.0000002,
        output: 0.0000006,
        request: 0.0,
        image: 0.0,
        audio: 0.0,
        web_search: 0.0,
      },
    ],
    contextLength: 131_072,
    maxCompletionTokens: 8_192,
    supportedParameters: [
      "max_tokens",
      "repetition_penalty",
      "response_format",
      "structured_outputs",
      "temperature",
      "tool_choice",
      "tools",
      "top_k",
      "top_p",
    ],
    ptbEnabled: true,
    endpointConfigs: {
      "*": {},
    },
  },
  "llama-guard-4:groq": {
    providerModelId: "meta-llama/Llama-Guard-4-12B",
    provider: "groq",
    author: "meta-llama",
    pricing: [
      {
        threshold: 0,
        input: 0.0000002,
        output: 0.0000006,
        request: 0.0,
        image: 0.0,
        audio: 0.0,
        web_search: 0.0,
      },
    ],
    contextLength: 131_072,
    maxCompletionTokens: 1_024,
    supportedParameters: [
      "frequency_penalty",
      "logit_bias",
      "max_tokens",
      "min_p",
      "presence_penalty",
      "repetition_penalty",
      "response_format",
      "seed",
      "stop",
      "temperature",
      "top_k",
      "top_p",
    ],
    ptbEnabled: true,
    endpointConfigs: {
      "*": {},
    },
  },
  "llama-3.3-70b-instruct:groq": {
    providerModelId: "llama-3.3-70b-versatile",
    provider: "groq",
    author: "meta-llama",
    pricing: [
      {
        threshold: 0,
        input: 0.00000059,
        output: 0.00000079,
        request: 0.0,
        image: 0.0,
        audio: 0.0,
        web_search: 0.0,
      },
    ],
    contextLength: 131_072,
    maxCompletionTokens: 32_678,
    supportedParameters: [
      "frequency_penalty",
      "logit_bias",
      "max_tokens",
      "min_p",
      "presence_penalty",
      "repetition_penalty",
      "stop",
      "temperature",
      "tool_choice",
      "tools",
      "top_k",
      "top_p",
    ],
    ptbEnabled: true,
    endpointConfigs: {
      "*": {},
    },
  },
  "llama-3.1-8b-instant:groq": {
    providerModelId: "llama-3.1-8b-instant",
    provider: "groq",
    author: "meta-llama",
    pricing: [
      {
        threshold: 0,
        input: 0.00000005,
        output: 0.00000008,
        request: 0.0,
        image: 0.0,
        audio: 0.0,
        web_search: 0.0,
      },
    ],
    contextLength: 131_072,
    maxCompletionTokens: 32_678,
    supportedParameters: [
      "frequency_penalty",
      "logit_bias",
      "max_tokens",
      "min_p",
      "presence_penalty",
      "repetition_penalty",
      "stop",
      "temperature",
      "tool_choice",
      "tools",
      "top_k",
      "top_p",
    ],
    ptbEnabled: true,
    endpointConfigs: {
      "*": {},
    },
  },
  "llama-prompt-guard-2-86m:groq": {
    providerModelId: "meta-llama/llama-prompt-guard-2-86m",
    provider: "groq",
    author: "meta-llama",
    pricing: [
      {
        threshold: 0,
        input: 0.00000001,
        output: 0.00000001,
        request: 0.0,
        image: 0.0,
        audio: 0.0,
        web_search: 0.0,
      },
    ],
    contextLength: 512,
    maxCompletionTokens: 2,
    supportedParameters: [
      "max_tokens",
      "temperature",
      "top_p",
    ],
    ptbEnabled: true,
    endpointConfigs: {
      "*": {},
    },
  },
  "llama-prompt-guard-2-22m:groq": {
    providerModelId: "meta-llama/llama-prompt-guard-2-22m",
    provider: "groq",
    author: "meta-llama",
    pricing: [
      {
        threshold: 0,
        input: 0.00000001,
        output: 0.00000001,
        request: 0.0,
        image: 0.0,
        audio: 0.0,
        web_search: 0.0,
      },
    ],
    contextLength: 512,
    maxCompletionTokens: 2,
    supportedParameters: [
      "max_tokens",
      "temperature",
      "top_p",
    ],
    ptbEnabled: true,
    endpointConfigs: {
      "*": {},
    },
  },
} satisfies Partial<
  Record<`${LlamaModelName}:${ModelProviderName}`, ModelProviderConfig>
>;
