import { ModelProviderName } from "../../../providers";
import type { ModelProviderConfig } from "../../../types";
import { LlamaModelName } from "./models";

export const endpoints = {
  "meta-llama/llama-4-scout-17b-16e-instruct:groq": {
    providerModelId: "meta-llama/Llama-4-Scout-17B-16E-Instruct",
    provider: "groq",
    author: "meta-llama",
    pricing: [
      {
        threshold: 0,
        input: 0.00000011,
        output: 0.00000034,
        request: 0.0,
        image: 0.0,
        audio: 0.0,
        web_search: 0.0,
      },
    ],
    contextLength: 131_072,
    maxCompletionTokens: 8_192,
    supportedParameters: [
      "max_tokens",
      "repetition_penalty",
      "response_format",
      "structured_outputs",
      "temperature",
      "tool_choice",
      "tools",
      "top_k",
      "top_p"
    ],
    ptbEnabled: true,
    endpointConfigs: {
      "*": {},
    },
  },
  "meta-llama/Llama-4-Maverick-17B-128E-Instruct:groq": {
    providerModelId: "meta-llama/Llama-4-Maverick-17B-128E-Instruct",
    provider: "groq",
    author: "meta-llama",
    pricing: [
      {
        threshold: 0,
        input: 0.0000002,
        output: 0.0000006,
        request: 0.0,
        image: 0.0,
        audio: 0.0,
        web_search: 0.0,
      },
    ],
    contextLength: 131_072,
    maxCompletionTokens: 8_192,
    supportedParameters: [
      "max_tokens",
      "repetition_penalty",
      "response_format",
      "structured_outputs",
      "temperature",
      "tool_choice",
      "tools",
      "top_k",
      "top_p"
    ],
    ptbEnabled: true,
    endpointConfigs: {
      "*": {},
    },
  },
  "meta-llama/Llama-Guard-4-12B:groq": {
    providerModelId: "meta-llama/Llama-Guard-4-12B",
    provider: "groq",
    author: "meta-llama",
    pricing: [
      {
        threshold: 0,
        input: 0.0000002,
        output: 0.0000006,
        request: 0.0,
        image: 0.0,
        audio: 0.0,
        web_search: 0.0,
      },
    ],
    contextLength: 131_072,
    maxCompletionTokens: 1_024,
    supportedParameters: [
      "frequency_penalty",
      "logit_bias",
      "max_tokens",
      "min_p",
      "presence_penalty",
      "repetition_penalty",
      "response_format",
      "seed",
      "stop",
      "temperature",
      "top_k",
      "top_p"
    ],
    ptbEnabled: true,
    endpointConfigs: {
      "*": {},
    },
  },
  "meta-llama/Llama-3.3-70B-Instruct:groq": {
    providerModelId: "meta-llama/Llama-3.3-70B-Instruct",
    provider: "groq",
    author: "meta-llama",
    pricing: [
      {
        threshold: 0,
        input: 0.00000059,
        output: 0.00000079,
        request: 0.0,
        image: 0.0,
        audio: 0.0,
        web_search: 0.0,
      },
    ],
    contextLength: 131_072,
    maxCompletionTokens: 32_678,
    supportedParameters: [
      "frequency_penalty",
      "logit_bias",
      "max_tokens",
      "min_p",
      "presence_penalty",
      "repetition_penalty",
      "stop",
      "temperature",
      "tool_choice",
      "tools",
      "top_k",
      "top_p"
    ],
    ptbEnabled: true,
    endpointConfigs: {
      "*": {},
    },
  },
  "meta-llama/Llama-3.1-8B:groq": {
    providerModelId: "meta-llama/Llama-3.1-8B",
    provider: "groq",
    author: "meta-llama",
    pricing: [
      {
        threshold: 0,
        input: 0.00000005,
        output: 0.00000008,
        request: 0.0,
        image: 0.0,
        audio: 0.0,
        web_search: 0.0,
      },
    ],
    contextLength: 131_072,
    maxCompletionTokens: 32_678,
    supportedParameters: [
      "frequency_penalty",
      "logit_bias",
      "max_tokens",
      "min_p",
      "presence_penalty",
      "repetition_penalty",
      "stop",
      "temperature",
      "tool_choice",
      "tools",
      "top_k",
      "top_p"
    ],
    ptbEnabled: true,
    endpointConfigs: {
      "*": {},
    },
  },
  "meta-llama/Meta-Llama-3-70B-Instruct:groq": {
    providerModelId: "meta-llama/Meta-Llama-3-70B-Instruct",
    provider: "groq",
    author: "meta-llama",
    pricing: [
      {
        threshold: 0,
        input: 0.00000059,
        output: 0.00000079,
        request: 0.0,
        image: 0.0,
        audio: 0.0,
        web_search: 0.0,
      },
    ],
    contextLength: 8_192,
    maxCompletionTokens: 16_384,
    supportedParameters: [
      "frequency_penalty",
      "logit_bias",
      "max_tokens",
      "min_p",
      "presence_penalty",
      "repetition_penalty",
      "stop",
      "temperature",
      "tool_choice",
      "tools",
      "top_k",
      "top_p"
    ],
    ptbEnabled: true,
    endpointConfigs: {
      "*": {},
    },
  },
  "meta-llama/Meta-Llama-3-8B:groq": {
    providerModelId: "meta-llama/Meta-Llama-3-8B",
    provider: "groq",
    author: "meta-llama",
    pricing: [
      {
        threshold: 0,
        input: 0.00000005,
        output: 0.00000008,
        request: 0.0,
        image: 0.0,
        audio: 0.0,
        web_search: 0.0,
      },
    ],
    contextLength: 8_192,
    maxCompletionTokens: 8_192,
    supportedParameters: [
      "frequency_penalty",
      "logit_bias",
      "max_tokens",
      "min_p",
      "presence_penalty",
      "repetition_penalty",
      "response_format",
      "seed",
      "stop",
      "temperature",
      "tool_choice",
      "tools",
      "top_k",
      "top_p"
    ],
    ptbEnabled: true,
    endpointConfigs: {
      "*": {},
    },
  },
  "meta-llama/Llama-Guard-3-8B:groq": {
    providerModelId: "meta-llama/Llama-Guard-3-8B",
    provider: "groq",
    author: "meta-llama",
    pricing: [
      {
        threshold: 0,
        input: 0.0000002,
        output: 0.0000002,
        request: 0.0,
        image: 0.0,
        audio: 0.0,
        web_search: 0.0,
      },
    ],
    contextLength: 8_192,
    maxCompletionTokens: 8_192,
    supportedParameters: [
      "frequency_penalty",
      "logit_bias",
      "logprobs",
      "max_tokens",
      "min_p",
      "presence_penalty",
      "repetition_penalty",
      "response_format",
      "seed",
      "stop",
      "temperature",
      "top_k",
      "top_logprobs",
      "top_p"
    ],
    ptbEnabled: true,
    endpointConfigs: {
      "*": {},
    },
  },
} satisfies Partial<
  Record<`${LlamaModelName}:${ModelProviderName}`, ModelProviderConfig>
>;