/**
 * Xai endpoint configurations
 */

import type { ModelEndpoint } from "../../types";

export const xAiEndpoints: Record<string, ModelEndpoint[]> = {
  "grok-4": [
    {
      name: "xAI | x-ai/grok-4-07-09",
      provider: "xai",
      tag: "xai",
      status: 0,
      pricing: {
        prompt: 3,
        completion: 15,
        cacheRead: 0.75,
        cacheWrite: null,
      },
      contextLength: 256000,
      maxCompletionTokens: null,
      supportedParameters: [
        "tools",
        "tool_choice",
        "reasoning",
        "include_reasoning",
        "max_tokens",
        "temperature",
        "top_p",
        "seed",
        "response_format",
      ],
    },
  ],

  "grok-3-mini": [
    {
      name: "xAI | x-ai/grok-3-mini",
      provider: "xai",
      tag: "xai",
      status: 0,
      pricing: {
        prompt: 0.3,
        completion: 0.5,
        cacheRead: 0.075,
        cacheWrite: null,
      },
      contextLength: 131072,
      maxCompletionTokens: null,
      supportedParameters: [
        "tools",
        "tool_choice",
        "reasoning",
        "include_reasoning",
        "max_tokens",
        "temperature",
        "top_p",
        "seed",
        "response_format",
        "stop",
      ],
    },
    {
      name: "xAI | x-ai/grok-3-mini",
      provider: "xai",
      tag: "xai",
      status: 0,
      pricing: {
        prompt: 0.6,
        completion: 4,
        cacheRead: 0.15,
        cacheWrite: null,
      },
      contextLength: 131072,
      maxCompletionTokens: null,
      supportedParameters: [
        "tools",
        "tool_choice",
        "reasoning",
        "include_reasoning",
        "max_tokens",
        "temperature",
        "top_p",
        "seed",
        "response_format",
        "stop",
      ],
    },
  ],

  "grok-3": [
    {
      name: "xAI | x-ai/grok-3",
      provider: "xai",
      tag: "xai",
      status: 0,
      pricing: {
        prompt: 3,
        completion: 15,
        cacheRead: 0.75,
        cacheWrite: null,
      },
      contextLength: 131072,
      maxCompletionTokens: null,
      supportedParameters: [
        "tools",
        "tool_choice",
        "max_tokens",
        "temperature",
        "top_p",
        "seed",
        "response_format",
        "stop",
        "frequency_penalty",
        "presence_penalty",
      ],
    },
    {
      name: "xAI | x-ai/grok-3",
      provider: "xai",
      tag: "xai/fast",
      status: 0,
      pricing: {
        prompt: 5,
        completion: 25,
        cacheRead: 1.25,
        cacheWrite: null,
      },
      contextLength: 131072,
      maxCompletionTokens: null,
      supportedParameters: [
        "tools",
        "tool_choice",
        "max_tokens",
        "temperature",
        "top_p",
        "seed",
        "response_format",
        "stop",
        "frequency_penalty",
        "presence_penalty",
      ],
    },
  ],

  "grok-3-mini-beta": [
    {
      name: "xAI | x-ai/grok-3-mini",
      provider: "xai",
      tag: "xai",
      status: 0,
      pricing: {
        prompt: 0.3,
        completion: 0.5,
        cacheRead: 0.075,
        cacheWrite: null,
      },
      contextLength: 131072,
      maxCompletionTokens: null,
      supportedParameters: [
        "tools",
        "tool_choice",
        "reasoning",
        "include_reasoning",
        "max_tokens",
        "temperature",
        "top_p",
        "seed",
        "response_format",
        "stop",
      ],
    },
    {
      name: "xAI | x-ai/grok-3-mini",
      provider: "xai",
      tag: "xai",
      status: 0,
      pricing: {
        prompt: 0.6,
        completion: 4,
        cacheRead: 0.15,
        cacheWrite: null,
      },
      contextLength: 131072,
      maxCompletionTokens: null,
      supportedParameters: [
        "tools",
        "tool_choice",
        "reasoning",
        "include_reasoning",
        "max_tokens",
        "temperature",
        "top_p",
        "seed",
        "response_format",
        "stop",
      ],
    },
  ],

  "grok-3-beta": [
    {
      name: "xAI | x-ai/grok-3",
      provider: "xai",
      tag: "xai",
      status: 0,
      pricing: {
        prompt: 3,
        completion: 15,
        cacheRead: 0.75,
        cacheWrite: null,
      },
      contextLength: 131072,
      maxCompletionTokens: null,
      supportedParameters: [
        "tools",
        "tool_choice",
        "max_tokens",
        "temperature",
        "top_p",
        "seed",
        "response_format",
        "stop",
        "frequency_penalty",
        "presence_penalty",
      ],
    },
    {
      name: "xAI | x-ai/grok-3",
      provider: "xai",
      tag: "xai/fast",
      status: 0,
      pricing: {
        prompt: 5,
        completion: 25,
        cacheRead: 1.25,
        cacheWrite: null,
      },
      contextLength: 131072,
      maxCompletionTokens: null,
      supportedParameters: [
        "tools",
        "tool_choice",
        "max_tokens",
        "temperature",
        "top_p",
        "seed",
        "response_format",
        "stop",
        "frequency_penalty",
        "presence_penalty",
      ],
    },
  ],

  "grok-2-vision-1212": [
    {
      name: "xAI | x-ai/grok-2-vision-1212",
      provider: "xai",
      tag: "xai",
      status: 0,
      pricing: {
        prompt: 2,
        completion: 10,
        image: 0.0036,
        cacheRead: null,
        cacheWrite: null,
      },
      contextLength: 32768,
      maxCompletionTokens: null,
      supportedParameters: [
        "max_tokens",
        "temperature",
        "top_p",
        "seed",
        "response_format",
        "stop",
        "frequency_penalty",
        "presence_penalty",
      ],
    },
  ],

  "grok-2-1212": [
    {
      name: "xAI | x-ai/grok-2-1212",
      provider: "xai",
      tag: "xai",
      status: 0,
      pricing: {
        prompt: 2,
        completion: 10,
        cacheRead: null,
        cacheWrite: null,
      },
      contextLength: 131072,
      maxCompletionTokens: null,
      supportedParameters: [
        "tools",
        "tool_choice",
        "max_tokens",
        "temperature",
        "top_p",
        "seed",
        "response_format",
        "stop",
        "frequency_penalty",
        "presence_penalty",
      ],
    },
  ],

  "grok-vision-beta": [
    {
      name: "xAI | x-ai/grok-vision-beta",
      provider: "xai",
      tag: "xai",
      status: 0,
      pricing: {
        prompt: 5,
        completion: 15,
        image: 0.009,
        cacheRead: null,
        cacheWrite: null,
      },
      contextLength: 8192,
      maxCompletionTokens: null,
      supportedParameters: [
        "max_tokens",
        "temperature",
        "top_p",
        "seed",
        "response_format",
        "stop",
        "frequency_penalty",
        "presence_penalty",
      ],
    },
  ],
};

export default xAiEndpoints;
