name: Rust CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use nightly rustfmt
        run: rustup override set nightly && rustup component add --toolchain nightly-x86_64-unknown-linux-gnu rustfmt
      - name: Output rust version for educational purposes
        run: rustup --version
      - name: Format
        run: cargo +nightly fmt --check
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # required for stubr test dependency
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
      - name: Clippy
        run: cargo ci-clippy
  test:
    runs-on: ubuntu-latest
    env:
      HELICONE_API_KEY: "sk-helicone-..."
    services:
      redis:
        image: redis:6.2.6-alpine
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v4
      # required for stubr test dependency
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
      - name: Test
        run: cargo test --tests --all-features
