/**
 * Anthropic endpoint configurations
 */

import type { ModelEndpoint } from "../../types";

export const anthropicEndpoints: Record<string, ModelEndpoint[]> = {
  "claude-opus-4-1": [
    {
      provider: "anthropic",
      providerModelId: "claude-opus-4-1-20250624",
      tag: "anthropic",
      pricing: {
        prompt: 15,
        completion: 75,
        image: 0.024,
        cacheRead: 1.5,
        cacheWrite: 18.75,
      },
      contextLength: 200000,
      maxCompletionTokens: 32000,
      supportedParameters: [
        'max_tokens',
        'temperature',
        'stop',
        'reasoning',
        'include_reasoning',
        'tools',
        'tool_choice',
      ],
    },
  ],
  "claude-opus-4": [
    {
      provider: "anthropic",
      providerModelId: "claude-opus-4-20250514",
      pricing: {
        prompt: 15,
        completion: 75,
        image: 0.024,
        cacheRead: 1.5,
        cacheWrite: 18.75,
      },
      contextLength: 200000,
      maxCompletionTokens: 32000,
      supportedParameters: [
        'max_tokens',
        'temperature',
        'stop',
        'reasoning',
        'include_reasoning',
        'tools',
        'tool_choice',
      ],
    },
    {
      provider: "vertex",
      providerModelId: "claude-opus-4@20250514",
      tag: "vertex",
      pricing: {
        prompt: 15,
        completion: 75,
        image: 0.024,
        cacheRead: 1.5,
        cacheWrite: 18.75,
      },
      contextLength: 200000,
      maxCompletionTokens: 32000,
      supportedParameters: [
        'max_tokens',
        'temperature',
        'stop',
        'reasoning',
        'include_reasoning',
        'tools',
        'tool_choice',
      ],
    },
    {
      provider: "bedrock",
      providerModelId: "us.anthropic.claude-opus-4-20250514-v1:0",
      model: "claude-4-opus-20250522",
      tag: "bedrock",
      pricing: {
        prompt: 15,
        completion: 75,
        image: 0.024,
        cacheRead: 1.5,
        cacheWrite: 18.75,
      },
      contextLength: 200000,
      maxCompletionTokens: 32000,
      supportedParameters: [
        'tools',
        'tool_choice',
        'reasoning',
        'include_reasoning',
        'max_tokens',
        'temperature',
        'top_p',
        'top_k',
        'stop',
      ],
    },
  ],

  // Add more endpoint configurations for other models...
  // I'll add just a few more as examples

  "claude-3.5-sonnet": [
    {
      name: "Anthropic | anthropic/claude-3.5-sonnet",
      provider: "anthropic",
      tag: "anthropic",
      status: 0,
      pricing: {
        prompt: 3,
        completion: 15,
        image: 0.0048,
        cacheRead: 0.3,
        cacheWrite: 3.75,
      },
      contextLength: 200000,
      maxCompletionTokens: 8192,
      supportedParameters: [
        'tools',
        'tool_choice',
        'max_tokens',
        'temperature',
        'top_p',
        'top_k',
        'stop',
      ],
    },
    {
      name: "Amazon Bedrock | anthropic/claude-3.5-sonnet",
      provider: "bedrock",
      tag: "bedrock",
      status: 0,
      pricing: {
        prompt: 3,
        completion: 15,
        image: 0.0048,
        cacheRead: 0.3,
        cacheWrite: 3.75,
      },
      contextLength: 200000,
      maxCompletionTokens: 8192,
      supportedParameters: [
        'tools',
        'tool_choice',
        'max_tokens',
        'temperature',
        'top_p',
        'top_k',
        'stop',
      ],
    },
    {
      name: "Google Vertex | anthropic/claude-3.5-sonnet",
      provider: "vertex",
      tag: "vertex",
      status: 0,
      pricing: {
        prompt: 3,
        completion: 15,
        image: 0.0048,
        cacheRead: 0.3,
        cacheWrite: 3.75,
      },
      contextLength: 200000,
      maxCompletionTokens: 8192,
      supportedParameters: [
        'tools',
        'tool_choice',
        'max_tokens',
        'temperature',
        'top_p',
        'top_k',
        'stop',
      ],
    },
  ],

  "claude-3-haiku": [
    {
      name: "Anthropic | anthropic/claude-3-haiku",
      provider: "anthropic",
      tag: "anthropic",
      status: 0,
      pricing: {
        prompt: 0.25,
        completion: 1.25,
        image: 0.0004,
        cacheRead: 0.03,
        cacheWrite: 0.3,
      },
      contextLength: 200000,
      maxCompletionTokens: 4096,
      supportedParameters: [
        'tools',
        'tool_choice',
        'max_tokens',
        'temperature',
        'top_p',
        'top_k',
        'stop',
      ],
    },
    {
      name: "Google Vertex | anthropic/claude-3-haiku",
      provider: "vertex",
      tag: "vertex",
      status: 0,
      pricing: {
        prompt: 0.25,
        completion: 1.25,
        image: 0.0004,
        cacheRead: 0.03,
        cacheWrite: 0.3,
      },
      contextLength: 200000,
      maxCompletionTokens: 4096,
      supportedParameters: [
        'tools',
        'tool_choice',
        'max_tokens',
        'temperature',
        'top_p',
        'top_k',
        'stop',
      ],
    },
  ],

  "claude-3-opus": [
    {
      name: "Anthropic | anthropic/claude-3-opus",
      provider: "anthropic",
      tag: "anthropic",
      status: 0,
      pricing: {
        prompt: 15,
        completion: 75,
        image: 0.024,
        cacheRead: 1.5,
        cacheWrite: 18.75,
      },
      contextLength: 200000,
      maxCompletionTokens: 4096,
      supportedParameters: [
        'tools',
        'tool_choice',
        'max_tokens',
        'temperature',
        'top_p',
        'top_k',
        'stop',
      ],
    },
    {
      name: "Google Vertex | anthropic/claude-3-opus",
      provider: "vertex",
      tag: "vertex",
      status: 0,
      pricing: {
        prompt: 15,
        completion: 75,
        image: 0.024,
        cacheRead: 1.5,
        cacheWrite: 18.75,
      },
      contextLength: 200000,
      maxCompletionTokens: 4096,
      supportedParameters: [
        'tools',
        'tool_choice',
        'max_tokens',
        'temperature',
        'top_p',
        'top_k',
        'stop',
      ],
    },
  ],

  // TODO: Add remaining model endpoints
};

export default anthropicEndpoints;
