/**
 * Anthropic endpoint definitions (flat structure)
 * Each endpoint is complete and self-contained
 */

import type { Endpoint, EndpointKey } from "../../types";
import { AnthropicModelName } from "./models";

// Endpoints keyed by their ID for O(1) lookup and consistency with models
export const anthropicEndpoints = {
  "claude-opus-4-1:anthropic": {
    modelId: "claude-opus-4-1",
    provider: "anthropic",
    providerModelId: "claude-opus-4-1-20250805",
    pricing: {
      prompt: 15,
      completion: 75,
      image: 0.024,
      cacheRead: 1.5,
      cacheWrite: {
        "5m": 18.75,
        "1h": 30,
        default: 18.75,
      },
    },
    contextLength: 200000,
    maxCompletionTokens: 32000,
    supportedParameters: [
      "max_tokens",
      "temperature",
      "stop",
      "reasoning",
      "include_reasoning",
      "tools",
      "tool_choice",
    ],
    ptbEnabled: true,
  },

  "claude-opus-4-1:vertex:us-central1": {
    modelId: "claude-opus-4-1",
    provider: "vertex",
    region: "us-central1",
    providerModelId: "claude-opus-4-1@20250805",
    pricing: {
      prompt: 15,
      completion: 75,
      image: 0.024,
      cacheRead: 1.5,
      cacheWrite: {
        "5m": 18.75,
        "1h": 30,
        default: 18.75,
      },
    },
    contextLength: 200000,
    maxCompletionTokens: 32000,
    supportedParameters: [
      "max_tokens",
      "temperature",
      "stop",
      "reasoning",
      "include_reasoning",
      "tools",
      "tool_choice",
    ],
    ptbEnabled: false,
  },

  "claude-opus-4-1:bedrock:us-west-2": {
    modelId: "claude-opus-4-1",
    provider: "bedrock",
    region: "us-west-2",
    providerModelId: "us.anthropic.claude-opus-4-1-20250805-v1:0",
    pricing: {
      prompt: 15,
      completion: 75,
      image: 0.024,
      cacheRead: 1.5,
      cacheWrite: {
        "5m": 18.75,
        "1h": 30,
        default: 18.75,
      },
    },
    contextLength: 200000,
    maxCompletionTokens: 32000,
    supportedParameters: [
      "tools",
      "tool_choice",
      "reasoning",
      "include_reasoning",
      "max_tokens",
      "temperature",
      "top_p",
      "top_k",
      "stop",
    ],
    ptbEnabled: true,
  },

  "claude-opus-4-1:bedrock:ap-southeast-1": {
    modelId: "claude-opus-4-1",
    provider: "bedrock",
    region: "ap-southeast-1",
    providerModelId: "ap.anthropic.claude-opus-4-1-20250805-v1:0",
    pricing: {
      prompt: 16.5,
      completion: 82.5,
      image: 0.026,
      cacheRead: 1.65,
      cacheWrite: {
        "5m": 20.6,
        "1h": 33,
        default: 20.6,
      },
    },
    contextLength: 200000,
    maxCompletionTokens: 32000,
    supportedParameters: [
      "tools",
      "tool_choice",
      "reasoning",
      "include_reasoning",
      "max_tokens",
      "temperature",
      "top_p",
      "top_k",
      "stop",
    ],
    ptbEnabled: false,
  },

  "claude-3.5-sonnet:anthropic": {
    modelId: "claude-3.5-sonnet",
    provider: "anthropic",
    providerModelId: "claude-3-5-sonnet-20241022",
    pricing: {
      prompt: 3,
      completion: 15,
      image: 0.0048,
      cacheRead: 0.3,
      cacheWrite: {
        "5m": 3.75,
        "1h": 6,
        default: 3.75,
      },
    },
    contextLength: 200000,
    maxCompletionTokens: 8192,
    supportedParameters: [
      "tools",
      "tool_choice",
      "max_tokens",
      "temperature",
      "top_p",
      "top_k",
      "stop",
    ],
    ptbEnabled: true,
  },

  "claude-3.5-sonnet:bedrock:us-west-2": {
    modelId: "claude-3.5-sonnet",
    provider: "bedrock",
    region: "us-west-2",
    providerModelId: "us.anthropic.claude-3-5-sonnet-20241022-v2:0",
    pricing: {
      prompt: 3,
      completion: 15,
      image: 0.0048,
      cacheRead: 0.3,
      cacheWrite: {
        "5m": 3.75,
        "1h": 6,
        default: 3.75,
      },
    },
    contextLength: 200000,
    maxCompletionTokens: 8192,
    supportedParameters: [
      "tools",
      "tool_choice",
      "max_tokens",
      "temperature",
      "top_p",
      "top_k",
      "stop",
    ],
    ptbEnabled: true,
  },

  "claude-3.5-sonnet:bedrock:eu-west-1": {
    modelId: "claude-3.5-sonnet",
    provider: "bedrock",
    region: "eu-west-1",
    providerModelId: "eu.anthropic.claude-3-5-sonnet-20241022-v2:0",
    pricing: {
      prompt: 3.3,
      completion: 16.5,
      image: 0.0053,
      cacheRead: 0.33,
      cacheWrite: {
        "5m": 4.13,
        "1h": 6.6,
        default: 4.13,
      },
    },
    contextLength: 200000,
    maxCompletionTokens: 8192,
    supportedParameters: [
      "tools",
      "tool_choice",
      "max_tokens",
      "temperature",
      "top_p",
      "top_k",
      "stop",
    ],
    ptbEnabled: false,
  },

  "claude-3.5-sonnet:vertex:us-central1": {
    modelId: "claude-3.5-sonnet",
    provider: "vertex",
    region: "us-central1",
    providerModelId: "claude-3-5-sonnet-v2@20241022",
    pricing: {
      prompt: 3,
      completion: 15,
      image: 0.0048,
      cacheRead: 0.3,
      cacheWrite: {
        "5m": 3.75,
        "1h": 6,
        default: 3.75,
      },
    },
    contextLength: 200000,
    maxCompletionTokens: 8192,
    supportedParameters: [
      "tools",
      "tool_choice",
      "max_tokens",
      "temperature",
      "top_p",
      "top_k",
      "stop",
    ],
    ptbEnabled: false,
  },

  "claude-3.5-haiku:anthropic": {
    modelId: "claude-3.5-haiku",
    provider: "anthropic",
    providerModelId: "claude-3-5-haiku-20241022",
    pricing: {
      prompt: 0.8,
      completion: 4,
      image: 0.0048,
      cacheRead: 0.08,
      cacheWrite: {
        "5m": 1,
        "1h": 1.6,
        default: 1,
      },
    },
    contextLength: 200000,
    maxCompletionTokens: 8192,
    supportedParameters: [
      "tools",
      "tool_choice",
      "max_tokens",
      "temperature",
      "top_p",
      "top_k",
      "stop",
    ],
    ptbEnabled: true,
  },

  "claude-3.5-haiku:vertex:us-central1": {
    modelId: "claude-3.5-haiku",
    provider: "vertex",
    region: "us-central1",
    providerModelId: "claude-3-5-haiku@20241022",
    pricing: {
      prompt: 0.8,
      completion: 4,
      image: 0.0048,
      cacheRead: 0.08,
      cacheWrite: {
        "5m": 1,
        "1h": 1.6,
        default: 1,
      },
    },
    contextLength: 200000,
    maxCompletionTokens: 8192,
    supportedParameters: [
      "tools",
      "tool_choice",
      "max_tokens",
      "temperature",
      "top_p",
      "top_k",
      "stop",
    ],
    ptbEnabled: false,
  },

  "claude-3.5-haiku:bedrock:us-west-2": {
    modelId: "claude-3.5-haiku",
    provider: "bedrock",
    region: "us-west-2",
    providerModelId: "us.anthropic.claude-3-5-haiku-20241022-v1:0",
    pricing: {
      prompt: 0.8,
      completion: 4,
      image: 0.0048,
      cacheRead: 0.08,
      cacheWrite: {
        "5m": 1,
        "1h": 1.6,
        default: 1,
      },
    },
    contextLength: 200000,
    maxCompletionTokens: 8192,
    supportedParameters: [
      "tools",
      "tool_choice",
      "max_tokens",
      "temperature",
      "top_p",
      "top_k",
      "stop",
    ],
    ptbEnabled: true,
  },
} satisfies Record<EndpointKey<AnthropicModelName>, Endpoint>;

export type AnthropicEndpointId = keyof typeof anthropicEndpoints;
