/**
 * Anthropic endpoint configurations
 */

import type { ModelEndpointMap } from "../../types";
import type { AnthropicModelName } from "./models";

export const anthropicEndpoints = {
  "claude-opus-4-1": {
    anthropic: {
      providerModelId: "claude-opus-4-1-20250805",
      pricing: {
        prompt: 15,
        completion: 75,
        image: 0.024,
        cacheRead: 1.5,
        cacheWrite: {
          "5m": 18.75,
          "1h": 30,
          default: 18.75,
        },
      },
      contextLength: 200000,
      maxCompletionTokens: 32000,
      supportedParameters: [
        "max_tokens",
        "temperature",
        "stop",
        "reasoning",
        "include_reasoning",
        "tools",
        "tool_choice",
      ],
    },
    vertex: {
      providerModelId: "claude-opus-4-1@20250805",
      pricing: {
        prompt: 15,
        completion: 75,
        image: 0.024,
        cacheRead: 1.5,
        cacheWrite: {
          "5m": 18.75,
          "1h": 30,
          default: 18.75,
        },
      },
      contextLength: 200000,
      maxCompletionTokens: 32000,
      supportedParameters: [
        "max_tokens",
        "temperature",
        "stop",
        "reasoning",
        "include_reasoning",
        "tools",
        "tool_choice",
      ],
    },
    bedrock: {
      providerModelId: "us.anthropic.claude-opus-4-1-20250805-v1:0",
      supportsDynamicRegion: true,
      baseModelId: "anthropic.claude-opus-4-1-20250805-v1:0",
      pricing: {
        prompt: 15,
        completion: 75,
        image: 0.024,
        cacheRead: 1.5,
        cacheWrite: {
          "5m": 18.75,
          "1h": 30,
          default: 18.75,
        },
      },
      contextLength: 200000,
      maxCompletionTokens: 32000,
      supportedParameters: [
        "tools",
        "tool_choice",
        "reasoning",
        "include_reasoning",
        "max_tokens",
        "temperature",
        "top_p",
        "top_k",
        "stop",
      ],
    },
  },
  "claude-opus-4": {
    anthropic: {
      providerModelId: "claude-opus-4-20250514",
      pricing: {
        prompt: 15,
        completion: 75,
        image: 0.024,
        cacheRead: 1.5,
        cacheWrite: {
          "5m": 18.75,
          "1h": 30,
          default: 18.75,
        },
      },
      contextLength: 200000,
      maxCompletionTokens: 32000,
      supportedParameters: [
        "max_tokens",
        "temperature",
        "stop",
        "reasoning",
        "include_reasoning",
        "tools",
        "tool_choice",
      ],
    },
    vertex: {
      providerModelId: "claude-opus-4@20250514",
      pricing: {
        prompt: 15,
        completion: 75,
        image: 0.024,
        cacheRead: 1.5,
        cacheWrite: {
          "5m": 18.75,
          "1h": 30,
          default: 18.75,
        },
      },
      contextLength: 200000,
      maxCompletionTokens: 32000,
      supportedParameters: [
        "max_tokens",
        "temperature",
        "stop",
        "reasoning",
        "include_reasoning",
        "tools",
        "tool_choice",
      ],
    },
    bedrock: {
      providerModelId: "us.anthropic.claude-opus-4-20250514-v1:0",
      model: "claude-4-opus-20250522",
      supportsDynamicRegion: true,
      baseModelId: "anthropic.claude-opus-4-20250514-v1:0",
      pricing: {
        prompt: 15,
        completion: 75,
        image: 0.024,
        cacheRead: 1.5,
        cacheWrite: {
          "5m": 18.75,
          "1h": 30,
          default: 18.75,
        },
      },
      contextLength: 200000,
      maxCompletionTokens: 32000,
      supportedParameters: [
        "tools",
        "tool_choice",
        "reasoning",
        "include_reasoning",
        "max_tokens",
        "temperature",
        "top_p",
        "top_k",
        "stop",
      ],
    },
  },
  "claude-sonnet-4": {
    anthropic: {
      providerModelId: "claude-sonnet-4-20250514",
      pricing: {
        prompt: 5,
        completion: 25,
        image: 0.008,
        cacheRead: 0.5,
        cacheWrite: {
          "5m": 3.75,
          "1h": 6,
          default: 3.75,
        },
      },
      contextLength: 200000,
      maxCompletionTokens: 64000,
      supportedParameters: [
        "max_tokens",
        "temperature",
        "stop",
        "reasoning",
        "include_reasoning",
        "tools",
        "tool_choice",
      ],
    },
    vertex: {
      providerModelId: "claude-sonnet-4@20250514",
      pricing: {
        prompt: 5,
        completion: 25,
        image: 0.008,
        cacheRead: 0.5,
        cacheWrite: {
          "5m": 3.75,
          "1h": 6,
          default: 3.75,
        },
      },
      contextLength: 200000,
      maxCompletionTokens: 64000,
      supportedParameters: [
        "max_tokens",
        "temperature",
        "stop",
        "reasoning",
        "include_reasoning",
        "tools",
        "tool_choice",
      ],
    },
    bedrock: {
      providerModelId: "us.anthropic.claude-sonnet-4-20250514-v1:0",
      supportsDynamicRegion: true,
      baseModelId: "anthropic.claude-sonnet-4-20250514-v1:0",
      pricing: {
        prompt: 5,
        completion: 25,
        image: 0.008,
        cacheRead: 0.5,
        cacheWrite: {
          "5m": 3.75,
          "1h": 6,
          default: 3.75,
        },
      },
      contextLength: 200000,
      maxCompletionTokens: 64000,
      supportedParameters: [
        "tools",
        "tool_choice",
        "reasoning",
        "include_reasoning",
        "max_tokens",
        "temperature",
        "top_p",
        "top_k",
        "stop",
      ],
    },
  },
  "claude-3.7-sonnet": {
    anthropic: {
      providerModelId: "claude-3-7-sonnet-20250219",
      pricing: {
        prompt: 3,
        completion: 15,
        image: 0.0048,
        cacheRead: 0.3,
        cacheWrite: {
          "5m": 3.75,
          "1h": 6,
          default: 3.75,
        },
      },
      contextLength: 200000,
      maxCompletionTokens: 64000,
      supportedParameters: [
        "max_tokens",
        "temperature",
        "stop",
        "reasoning",
        "include_reasoning",
        "tools",
        "tool_choice",
      ],
    },
    vertex: {
      providerModelId: "claude-3-7-sonnet@20250219",
      pricing: {
        prompt: 3,
        completion: 15,
        image: 0.0048,
        cacheRead: 0.3,
        cacheWrite: {
          "5m": 3.75,
          "1h": 6,
          default: 3.75,
        },
      },
      contextLength: 200000,
      maxCompletionTokens: 64000,
      supportedParameters: [
        "max_tokens",
        "temperature",
        "stop",
        "reasoning",
        "include_reasoning",
        "tools",
        "tool_choice",
      ],
    },
    bedrock: {
      providerModelId: "us.anthropic.claude-3-7-sonnet-20250219-v1:0",
      supportsDynamicRegion: true,
      baseModelId: "anthropic.claude-3-7-sonnet-20250219-v1:0",
      pricing: {
        prompt: 3,
        completion: 15,
        image: 0.0048,
        cacheRead: 0.3,
        cacheWrite: {
          "5m": 3.75,
          "1h": 6,
          default: 3.75,
        },
      },
      contextLength: 200000,
      maxCompletionTokens: 64000,
      supportedParameters: [
        "tools",
        "tool_choice",
        "reasoning",
        "include_reasoning",
        "max_tokens",
        "temperature",
        "top_p",
        "top_k",
        "stop",
      ],
    },
  },
  "claude-3.5-sonnet": {
    anthropic: {
      name: "Anthropic | anthropic/claude-3.5-sonnet",
      providerModelId: "claude-3-5-sonnet-20241022",
      pricing: {
        prompt: 3,
        completion: 15,
        image: 0.0048,
        cacheRead: 0.3,
        cacheWrite: {
          "5m": 3.75,
          "1h": 6,
          default: 3.75,
        },
      },
      contextLength: 200000,
      maxCompletionTokens: 8192,
      supportedParameters: [
        "tools",
        "tool_choice",
        "max_tokens",
        "temperature",
        "top_p",
        "top_k",
        "stop",
      ],
    },
    bedrock: {
      name: "Amazon Bedrock | anthropic/claude-3.5-sonnet",
      providerModelId: "us.anthropic.claude-3-5-sonnet-20241022-v2:0",
      supportsDynamicRegion: true,
      baseModelId: "anthropic.claude-3-5-sonnet-20241022-v2:0",
      pricing: {
        prompt: 3,
        completion: 15,
        image: 0.0048,
        cacheRead: 0.3,
        cacheWrite: {
          "5m": 3.75,
          "1h": 6,
          default: 3.75,
        },
      },
      contextLength: 200000,
      maxCompletionTokens: 8192,
      supportedParameters: [
        "tools",
        "tool_choice",
        "max_tokens",
        "temperature",
        "top_p",
        "top_k",
        "stop",
      ],
    },
    vertex: {
      name: "Google Vertex | anthropic/claude-3.5-sonnet",
      providerModelId: "claude-3-5-sonnet-v2@20241022",
      pricing: {
        prompt: 3,
        completion: 15,
        image: 0.0048,
        cacheRead: 0.3,
        cacheWrite: {
          "5m": 3.75,
          "1h": 6,
          default: 3.75,
        },
      },
      contextLength: 200000,
      maxCompletionTokens: 8192,
      supportedParameters: [
        "tools",
        "tool_choice",
        "max_tokens",
        "temperature",
        "top_p",
        "top_k",
        "stop",
      ],
    },
  },
  "claude-3.5-haiku": {
    anthropic: {
      providerModelId: "claude-3-5-haiku-20241022",
      pricing: {
        prompt: 0.8,
        completion: 4,
        image: 0.0048,
        cacheRead: 0.08,
        cacheWrite: {
          "5m": 1,
          "1h": 1.6,
          default: 1,
        },
      },
      contextLength: 200000,
      maxCompletionTokens: 8192,
      supportedParameters: [
        "tools",
        "tool_choice",
        "max_tokens",
        "temperature",
        "top_p",
        "top_k",
        "stop",
      ],
    },
    vertex: {
      providerModelId: "claude-3-5-haiku@20241022",
      pricing: {
        prompt: 0.8,
        completion: 4,
        image: 0.0048,
        cacheRead: 0.08,
        cacheWrite: {
          "5m": 1,
          "1h": 1.6,
          default: 1,
        },
      },
      contextLength: 200000,
      maxCompletionTokens: 8192,
      supportedParameters: [
        "tools",
        "tool_choice",
        "max_tokens",
        "temperature",
        "top_p",
        "top_k",
        "stop",
      ],
    },
    bedrock: {
      providerModelId: "us.anthropic.claude-3-5-haiku-20241022-v1:0",
      supportsDynamicRegion: true,
      baseModelId: "anthropic.claude-3-5-haiku-20241022-v1:0",
      pricing: {
        prompt: 0.8,
        completion: 4,
        image: 0.0048,
        cacheRead: 0.08,
        cacheWrite: {
          "5m": 1,
          "1h": 1.6,
          default: 1,
        },
      },
      contextLength: 200000,
      maxCompletionTokens: 8192,
      supportedParameters: [
        "tools",
        "tool_choice",
        "max_tokens",
        "temperature",
        "top_p",
        "top_k",
        "stop",
      ],
    },
  },
  "claude-3-haiku": {
    anthropic: {
      name: "Anthropic | anthropic/claude-3-haiku",
      providerModelId: "claude-3-haiku-20240307",
      pricing: {
        prompt: 0.25,
        completion: 1.25,
        image: 0.0004,
        cacheRead: 0.03,
        cacheWrite: {
          "5m": 0.3,
          "1h": 0.5,
          default: 0.3,
        },
      },
      contextLength: 200000,
      maxCompletionTokens: 4096,
      supportedParameters: [
        "tools",
        "tool_choice",
        "max_tokens",
        "temperature",
        "top_p",
        "top_k",
        "stop",
      ],
    },
    vertex: {
      name: "Google Vertex | anthropic/claude-3-haiku",
      providerModelId: "claude-3-haiku@20240307",
      pricing: {
        prompt: 0.25,
        completion: 1.25,
        image: 0.0004,
        cacheRead: 0.03,
        cacheWrite: {
          "5m": 0.3,
          "1h": 0.5,
          default: 0.3,
        },
      },
      contextLength: 200000,
      maxCompletionTokens: 4096,
      supportedParameters: [
        "tools",
        "tool_choice",
        "max_tokens",
        "temperature",
        "top_p",
        "top_k",
        "stop",
      ],
    },
    bedrock: {
      name: "Amazon Bedrock | anthropic/claude-3-haiku",
      providerModelId: "us.anthropic.claude-3-haiku-20240307-v1:0",
      supportsDynamicRegion: true,
      baseModelId: "anthropic.claude-3-haiku-20240307-v1:0",
      pricing: {
        prompt: 0.25,
        completion: 1.25,
        image: 0.0004,
        cacheRead: 0.03,
        cacheWrite: {
          "5m": 0.3,
          "1h": 0.5,
          default: 0.3,
        },
      },
      contextLength: 200000,
      maxCompletionTokens: 4096,
      supportedParameters: [
        "tools",
        "tool_choice",
        "max_tokens",
        "temperature",
        "top_p",
        "top_k",
        "stop",
      ],
    },
  },
  "claude-3-opus": {
    anthropic: {
      name: "Anthropic | anthropic/claude-3-opus",
      providerModelId: "claude-3-opus-20240229",
      pricing: {
        prompt: 15,
        completion: 75,
        image: 0.024,
        cacheRead: 1.5,
        cacheWrite: {
          "5m": 18.75,
          "1h": 30,
          default: 18.75,
        },
      },
      contextLength: 200000,
      maxCompletionTokens: 4096,
      supportedParameters: [
        "tools",
        "tool_choice",
        "max_tokens",
        "temperature",
        "top_p",
        "top_k",
        "stop",
      ],
    },
    vertex: {
      name: "Google Vertex | anthropic/claude-3-opus",
      providerModelId: "claude-3-opus@20240229",
      pricing: {
        prompt: 15,
        completion: 75,
        image: 0.024,
        cacheRead: 1.5,
        cacheWrite: {
          "5m": 18.75,
          "1h": 30,
          default: 18.75,
        },
      },
      contextLength: 200000,
      maxCompletionTokens: 4096,
      supportedParameters: [
        "tools",
        "tool_choice",
        "max_tokens",
        "temperature",
        "top_p",
        "top_k",
        "stop",
      ],
    },
    bedrock: {
      name: "Amazon Bedrock | anthropic/claude-3-opus",
      providerModelId: "us.anthropic.claude-3-opus-20240229-v1:0",
      supportsDynamicRegion: true,
      baseModelId: "anthropic.claude-3-opus-20240229-v1:0",
      pricing: {
        prompt: 15,
        completion: 75,
        image: 0.024,
        cacheRead: 1.5,
        cacheWrite: {
          "5m": 18.75,
          "1h": 30,
          default: 18.75,
        },
      },
      contextLength: 200000,
      maxCompletionTokens: 4096,
      supportedParameters: [
        "tools",
        "tool_choice",
        "max_tokens",
        "temperature",
        "top_p",
        "top_k",
        "stop",
      ],
    },
  },
} satisfies Record<AnthropicModelName, ModelEndpointMap>;

export default anthropicEndpoints;
