INSERT INTO default.request_response_rmt_v2 (
        response_id,
        response_created_at,
        latency,
        status,
        completion_tokens,
        completion_audio_tokens,
        prompt_tokens,
        prompt_cache_write_tokens,
        prompt_cache_read_tokens,
        prompt_audio_tokens,
        model,
        request_id,
        request_created_at,
        user_id,
        organization_id,
        proxy_key_id,
        threat,
        time_to_first_token,
        provider,
        target_url,
        country_code,
        properties,
        scores,
        request_body,
        response_body,
        assets,
        updated_at,
        is_deleted,
        session_name,
        session_id,
        session_path
    )
SELECT response_id,
    response_created_at,
    latency,
    status,
    completion_tokens,
    completion_audio_tokens,
    prompt_tokens,
    prompt_cache_write_tokens,
    prompt_cache_read_tokens,
    prompt_audio_tokens,
    model,
    request_id,
    request_created_at,
    user_id,
    organization_id,
    proxy_key_id,
    threat,
    time_to_first_token,
    provider,
    target_url,
    country_code,
    properties,
    scores,
    request_body,
    response_body,
    assets,
    updated_at,
    false AS is_deleted,
    -- default for soft deletion
    ifNull(properties ['Helicone-Session-Name'], '') AS session_name,
    ifNull(properties ['Helicone-Session-ID'], '') AS session_id,
    ifNull(properties ['Helicone-Session-Path'], '') AS session_path
FROM default.request_response_rmt
WHERE request_created_at < '2025-04-14 00:00:00'