auth_enabled: false

limits_config:
  allow_structured_metadata: true
  # global setting of 7 days
  retention_period: 168h
  # TODO: set a lower retention setting for specific streams if needed
  # retention_stream:

common:
  instance_addr: 127.0.0.1
  path_prefix: /var/lib/loki
  storage:
    filesystem:
      chunks_directory: /var/lib/loki/chunks
      rules_directory: /var/lib/loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 50

schema_config:
  configs:
    - from: 2020-05-15
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

analytics:
  reporting_enabled: false

compactor:
  # 4 days
  apply_retention_interval: '96h'
  working_directory: /var/lib/loki/retention
  delete_request_store: filesystem
  compaction_interval: '1h'
  retention_enabled: true
