/**
 *
 * DO NOT EDIT THIS FILE UNLESS IT IS IN /costs
 */

import { ModelRow } from "../../interfaces/Cost";

export const costs: ModelRow[] = [
  {
    model: {
      operator: "equals",
      value: "llama3.1-8b",
    },
    cost: {
      prompt_token: 0.0000001, // $0.10/1M tokens
      completion_token: 0.0000001, // $0.10/1M tokens
    },
  },
  {
    model: {
      operator: "equals",
      value: "gpt-oss-120b",
    },
    cost: {
      prompt_token: 0.00000035, // $0.35/1M tokens
      completion_token: 0.00000075, // $0.75/1M tokens
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen-3-235b-a22b-instruct-2507",
    },
    cost: {
      prompt_token: 0.0000006, // $0.60/1M tokens
      completion_token: 0.0000012, // $1.20/1M tokens
    },
  },
  {
    model: {
      operator: "equals",
      value: "zai-glm-4.7",
    },
    cost: {
      prompt_token: 0.00000225, // $2.25/1M tokens
      completion_token: 0.00000275, // $2.75/1M tokens
    },
  },
];
