/**
 *
 * DO NOT EDIT THIS FILE UNLESS IT IS IN /costs
 */

import { ModelRow } from "../../interfaces/Cost";

export const costs: ModelRow[] = [
  {
    model: {
      operator: "startsWith",
      value: "ft:gpt-3.5-turbo-",
    },
    cost: {
      prompt_token: 0.000003,
      completion_token: 0.000006,
    },
  },
];
