ALTER TABLE
    public.provider_keys
ADD
    COLUMN created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();

ALTER TABLE
    public.helicone_proxy_keys
ADD
    COLUMN created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();

DROP TABLE IF EXISTS feedback CASCADE;

DROP TABLE IF EXISTS feedback_metrics CASCADE;

CREATE TABLE public.feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    response_id UUID NOT NULL REFERENCES public.response(id),
    is_thumbs_up BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_feedback_response ON public.feedback(response_id);