create table "public"."user_feedback" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "feedback" text not null,
    "organization_id" uuid not null,
    "tag" text not null
);


alter table "public"."user_feedback" enable row level security;

CREATE UNIQUE INDEX user_feedback_pkey ON public.user_feedback USING btree (id);

alter table "public"."user_feedback" add constraint "user_feedback_pkey" PRIMARY KEY using index "user_feedback_pkey";

alter table "public"."user_feedback" add constraint "user_feedback_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES organization(id) not valid;

alter table "public"."user_feedback" validate constraint "user_feedback_organization_id_fkey";

grant insert on table "public"."user_feedback" to "authenticated";

create policy "Enable inserts for anyone"
on "public"."user_feedback"
as permissive
for insert
to public
with check (true);



