-- Create feature_waitlist table for tracking users waiting for specific features
CREATE TABLE IF NOT EXISTS public.feature_waitlist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    email VARCHAR(255) NOT NULL,
    feature VARCHAR(100) NOT NULL,
    organization_id UUID NULL -- Optional organization ID
);
-- Create primary key
CREATE UNIQUE INDEX feature_waitlist_pkey ON public.feature_waitlist USING btree (id);
ALTER TABLE public.feature_waitlist
ADD CONSTRAINT feature_waitlist_pkey PRIMARY KEY USING INDEX feature_waitlist_pkey;
-- Create unique index on email + feature to prevent duplicates
CREATE UNIQUE INDEX feature_waitlist_email_feature_key ON public.feature_waitlist USING btree (email, feature);
ALTER TABLE public.feature_waitlist
ADD CONSTRAINT feature_waitlist_email_feature_key UNIQUE USING INDEX feature_waitlist_email_feature_key;
REVOKE ALL ON TABLE public.feature_waitlist
FROM PUBLIC;
REVOKE ALL ON TABLE public.feature_waitlist
FROM authenticated;
REVOKE ALL ON TABLE public.feature_waitlist
FROM service_role;