create table "public"."gateway_configs" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "organization_id" uuid not null,
    "config_yaml" text not null,
    "key_id" bigint,
    "type" character varying not null default 'cloud'::character varying
);

alter table "public"."gateway_configs" enable row level security;

revoke all on table "public"."gateway_configs" from anon, authenticated, public;

CREATE UNIQUE INDEX gateway_configs_pkey ON public.gateway_configs USING btree (id);

alter table "public"."gateway_configs" add constraint "gateway_configs_pkey" PRIMARY KEY using index "gateway_configs_pkey";

alter table "public"."gateway_configs" add constraint "public_gateway_configs_key_id_fkey" FOREIGN KEY (key_id) REFERENCES helicone_api_keys(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."gateway_configs" validate constraint "public_gateway_configs_key_id_fkey";

alter table "public"."gateway_configs" add constraint "public_gateway_configs_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES organization(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."gateway_configs" validate constraint "public_gateway_configs_organization_id_fkey";
