/**
 *
 * DO NOT EDIT THIS FILE UNLESS IT IS IN /costs
 */

import { ModelRow } from "../../interfaces/Cost";

export const costs: ModelRow[] = [
  {
    model: {
      operator: "equals",
      value: "ibm-granite/granite-4.0-h-micro",
    },
    cost: {
      prompt_token: 1.7e-8,
      completion_token: 1.1e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "deepcogito/cogito-v2-preview-llama-405b",
    },
    cost: {
      prompt_token: 3.5e-6,
      completion_token: 3.5e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-5-image-mini",
    },
    cost: {
      prompt_token: 2.5e-6,
      completion_token: 2e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "anthropic/claude-haiku-4.5",
    },
    cost: {
      prompt_token: 1e-6,
      completion_token: 5e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen3-vl-8b-thinking",
    },
    cost: {
      prompt_token: 1.8e-7,
      completion_token: 2.1e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen3-vl-8b-instruct",
    },
    cost: {
      prompt_token: 8e-8,
      completion_token: 5e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-5-image",
    },
    cost: {
      prompt_token: 1e-5,
      completion_token: 1e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "inclusionai/ring-1t",
    },
    cost: {
      prompt_token: 5.7e-7,
      completion_token: 2.28e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "inclusionai/ling-1t",
    },
    cost: {
      prompt_token: 4e-7,
      completion_token: 2e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/o3-deep-research",
    },
    cost: {
      prompt_token: 1e-5,
      completion_token: 4e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/o4-mini-deep-research",
    },
    cost: {
      prompt_token: 2e-6,
      completion_token: 8e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "nvidia/llama-3.3-nemotron-super-49b-v1.5",
    },
    cost: {
      prompt_token: 1e-7,
      completion_token: 4e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "baidu/ernie-4.5-21b-a3b-thinking",
    },
    cost: {
      prompt_token: 7e-8,
      completion_token: 2.8e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "google/gemini-2.5-flash-image",
    },
    cost: {
      prompt_token: 3e-7,
      completion_token: 2.5e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen3-vl-30b-a3b-thinking",
    },
    cost: {
      prompt_token: 2e-7,
      completion_token: 1e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen3-vl-30b-a3b-instruct",
    },
    cost: {
      prompt_token: 2e-7,
      completion_token: 7e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-5-pro",
    },
    cost: {
      prompt_token: 1.5e-5,
      completion_token: 0.00012,
    },
  },
  {
    model: {
      operator: "equals",
      value: "z-ai/glm-4.6",
    },
    cost: {
      prompt_token: 5e-7,
      completion_token: 1.75e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "anthropic/claude-sonnet-4.5",
    },
    cost: {
      prompt_token: 3e-6,
      completion_token: 1.5e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "deepseek/deepseek-v3.2-exp",
    },
    cost: {
      prompt_token: 2.7e-7,
      completion_token: 4e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "thedrummer/cydonia-24b-v4.1",
    },
    cost: {
      prompt_token: 3e-7,
      completion_token: 5e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "relace/relace-apply-3",
    },
    cost: {
      prompt_token: 8.5e-7,
      completion_token: 1.25e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "google/gemini-2.5-flash-preview-09-2025",
    },
    cost: {
      prompt_token: 3e-7,
      completion_token: 2.5e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "google/gemini-2.5-flash-lite-preview-09-2025",
    },
    cost: {
      prompt_token: 1e-7,
      completion_token: 4e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen3-vl-235b-a22b-thinking",
    },
    cost: {
      prompt_token: 3e-7,
      completion_token: 1.2e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen3-vl-235b-a22b-instruct",
    },
    cost: {
      prompt_token: 3e-7,
      completion_token: 1.2e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen3-max",
    },
    cost: {
      prompt_token: 1.2e-6,
      completion_token: 6e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen3-coder-plus",
    },
    cost: {
      prompt_token: 1e-6,
      completion_token: 5e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-5-codex",
    },
    cost: {
      prompt_token: 1.25e-6,
      completion_token: 1e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "deepseek/deepseek-v3.1-terminus",
    },
    cost: {
      prompt_token: 2.3e-7,
      completion_token: 9e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "x-ai/grok-4-fast",
    },
    cost: {
      prompt_token: 2e-7,
      completion_token: 5e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "alibaba/tongyi-deepresearch-30b-a3b:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "alibaba/tongyi-deepresearch-30b-a3b",
    },
    cost: {
      prompt_token: 9e-8,
      completion_token: 4e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen3-coder-flash",
    },
    cost: {
      prompt_token: 3e-7,
      completion_token: 1.5e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "arcee-ai/afm-4.5b",
    },
    cost: {
      prompt_token: 4.8e-8,
      completion_token: 1.5e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "opengvlab/internvl3-78b",
    },
    cost: {
      prompt_token: 7e-8,
      completion_token: 2.6e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen3-next-80b-a3b-thinking",
    },
    cost: {
      prompt_token: 1.4e-7,
      completion_token: 1.2e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen3-next-80b-a3b-instruct",
    },
    cost: {
      prompt_token: 1e-7,
      completion_token: 8e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "meituan/longcat-flash-chat:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "meituan/longcat-flash-chat",
    },
    cost: {
      prompt_token: 1.5e-7,
      completion_token: 7.5e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen-plus-2025-07-28",
    },
    cost: {
      prompt_token: 4e-7,
      completion_token: 1.2e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen-plus-2025-07-28:thinking",
    },
    cost: {
      prompt_token: 4e-7,
      completion_token: 4e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "nvidia/nemotron-nano-9b-v2:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "nvidia/nemotron-nano-9b-v2",
    },
    cost: {
      prompt_token: 4e-8,
      completion_token: 1.6e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "moonshotai/kimi-k2-0905",
    },
    cost: {
      prompt_token: 3.9e-7,
      completion_token: 1.9e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "deepcogito/cogito-v2-preview-llama-70b",
    },
    cost: {
      prompt_token: 8.8e-7,
      completion_token: 8.8e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "deepcogito/cogito-v2-preview-llama-109b-moe",
    },
    cost: {
      prompt_token: 1.8e-7,
      completion_token: 5.9e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "deepcogito/cogito-v2-preview-deepseek-671b",
    },
    cost: {
      prompt_token: 1.25e-6,
      completion_token: 1.25e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "stepfun-ai/step3",
    },
    cost: {
      prompt_token: 5.7e-7,
      completion_token: 1.42e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen3-30b-a3b-thinking-2507",
    },
    cost: {
      prompt_token: 8e-8,
      completion_token: 2.9e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "x-ai/grok-code-fast-1",
    },
    cost: {
      prompt_token: 2e-7,
      completion_token: 1.5e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "nousresearch/hermes-4-70b",
    },
    cost: {
      prompt_token: 1.1e-7,
      completion_token: 3.8e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "nousresearch/hermes-4-405b",
    },
    cost: {
      prompt_token: 3e-7,
      completion_token: 1.2e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "google/gemini-2.5-flash-image-preview",
    },
    cost: {
      prompt_token: 3e-7,
      completion_token: 2.5e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "deepseek/deepseek-chat-v3.1:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "deepseek/deepseek-chat-v3.1",
    },
    cost: {
      prompt_token: 2.7e-7,
      completion_token: 1e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-4o-audio-preview",
    },
    cost: {
      prompt_token: 2.5e-6,
      completion_token: 1e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/mistral-medium-3.1",
    },
    cost: {
      prompt_token: 4e-7,
      completion_token: 2e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "baidu/ernie-4.5-21b-a3b",
    },
    cost: {
      prompt_token: 7e-8,
      completion_token: 2.8e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "baidu/ernie-4.5-vl-28b-a3b",
    },
    cost: {
      prompt_token: 1.4e-7,
      completion_token: 5.6e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "z-ai/glm-4.5v",
    },
    cost: {
      prompt_token: 6e-7,
      completion_token: 1.8e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "ai21/jamba-mini-1.7",
    },
    cost: {
      prompt_token: 2e-7,
      completion_token: 4e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "ai21/jamba-large-1.7",
    },
    cost: {
      prompt_token: 2e-6,
      completion_token: 8e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-5-chat",
    },
    cost: {
      prompt_token: 1.25e-6,
      completion_token: 1e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-5",
    },
    cost: {
      prompt_token: 1.25e-6,
      completion_token: 1e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-5-mini",
    },
    cost: {
      prompt_token: 2.5e-7,
      completion_token: 2e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-5-nano",
    },
    cost: {
      prompt_token: 5e-8,
      completion_token: 4e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-5.1",
    },
    cost: {
      prompt_token: 1.25e-6,
      completion_token: 1e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-5.1-codex",
    },
    cost: {
      prompt_token: 1.25e-6,
      completion_token: 1e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-5.1-codex-mini",
    },
    cost: {
      prompt_token: 2.5e-7,
      completion_token: 2e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-oss-120b",
    },
    cost: {
      prompt_token: 4e-8,
      completion_token: 4e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-oss-20b:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-oss-20b",
    },
    cost: {
      prompt_token: 3e-8,
      completion_token: 1.4e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "anthropic/claude-opus-4.1",
    },
    cost: {
      prompt_token: 1.5e-5,
      completion_token: 7.5e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/codestral-2508",
    },
    cost: {
      prompt_token: 3e-7,
      completion_token: 9e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen3-coder-30b-a3b-instruct",
    },
    cost: {
      prompt_token: 6e-8,
      completion_token: 2.5e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen3-30b-a3b-instruct-2507",
    },
    cost: {
      prompt_token: 8e-8,
      completion_token: 3.3e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "z-ai/glm-4.5",
    },
    cost: {
      prompt_token: 3e-7,
      completion_token: 1.5e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "z-ai/glm-4.5-air:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "z-ai/glm-4.5-air",
    },
    cost: {
      prompt_token: 1.3e-7,
      completion_token: 8.5e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen3-235b-a22b-thinking-2507",
    },
    cost: {
      prompt_token: 1.1e-7,
      completion_token: 6e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "z-ai/glm-4-32b",
    },
    cost: {
      prompt_token: 1e-7,
      completion_token: 1e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen3-coder:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen3-coder",
    },
    cost: {
      prompt_token: 2.2e-7,
      completion_token: 9.5e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "bytedance/ui-tars-1.5-7b",
    },
    cost: {
      prompt_token: 1e-7,
      completion_token: 2e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "google/gemini-2.5-flash-lite",
    },
    cost: {
      prompt_token: 1e-7,
      completion_token: 4e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen3-235b-a22b-2507",
    },
    cost: {
      prompt_token: 8e-8,
      completion_token: 5.5e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "switchpoint/router",
    },
    cost: {
      prompt_token: 8.5e-7,
      completion_token: 3.4e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "moonshotai/kimi-k2:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "moonshotai/kimi-k2",
    },
    cost: {
      prompt_token: 1.4e-7,
      completion_token: 2.49e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "thudm/glm-4.1v-9b-thinking",
    },
    cost: {
      prompt_token: 3.5e-8,
      completion_token: 1.38e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/devstral-medium",
    },
    cost: {
      prompt_token: 4e-7,
      completion_token: 2e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/devstral-small",
    },
    cost: {
      prompt_token: 7e-8,
      completion_token: 2.8e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "cognitivecomputations/dolphin-mistral-24b-venice-edition:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "x-ai/grok-4",
    },
    cost: {
      prompt_token: 3e-6,
      completion_token: 1.5e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "google/gemma-3n-e2b-it:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "tencent/hunyuan-a13b-instruct:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "tencent/hunyuan-a13b-instruct",
    },
    cost: {
      prompt_token: 3e-8,
      completion_token: 3e-8,
    },
  },
  {
    model: {
      operator: "equals",
      value: "tngtech/deepseek-r1t2-chimera:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "tngtech/deepseek-r1t2-chimera",
    },
    cost: {
      prompt_token: 3e-7,
      completion_token: 1.2e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "morph/morph-v3-large",
    },
    cost: {
      prompt_token: 9e-7,
      completion_token: 1.9e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "morph/morph-v3-fast",
    },
    cost: {
      prompt_token: 8e-7,
      completion_token: 1.2e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "baidu/ernie-4.5-vl-424b-a47b",
    },
    cost: {
      prompt_token: 4.2e-7,
      completion_token: 1.25e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "baidu/ernie-4.5-300b-a47b",
    },
    cost: {
      prompt_token: 2.8e-7,
      completion_token: 1.1e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "thedrummer/anubis-70b-v1.1",
    },
    cost: {
      prompt_token: 6.5e-7,
      completion_token: 1e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "inception/mercury",
    },
    cost: {
      prompt_token: 2.5e-7,
      completion_token: 1e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/mistral-small-3.2-24b-instruct:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/mistral-small-3.2-24b-instruct",
    },
    cost: {
      prompt_token: 6e-8,
      completion_token: 1.8e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "minimax/minimax-m1",
    },
    cost: {
      prompt_token: 4e-7,
      completion_token: 2.2e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "google/gemini-2.5-flash-lite-preview-06-17",
    },
    cost: {
      prompt_token: 1e-7,
      completion_token: 4e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "google/gemini-2.5-flash",
    },
    cost: {
      prompt_token: 3e-7,
      completion_token: 2.5e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "google/gemini-2.5-pro",
    },
    cost: {
      prompt_token: 1.25e-6,
      completion_token: 1e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "moonshotai/kimi-dev-72b:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "moonshotai/kimi-dev-72b",
    },
    cost: {
      prompt_token: 2.9e-7,
      completion_token: 1.15e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/o3-pro",
    },
    cost: {
      prompt_token: 2e-5,
      completion_token: 8e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "x-ai/grok-3-mini",
    },
    cost: {
      prompt_token: 3e-7,
      completion_token: 5e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "x-ai/grok-3",
    },
    cost: {
      prompt_token: 3e-6,
      completion_token: 1.5e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/magistral-small-2506",
    },
    cost: {
      prompt_token: 5e-7,
      completion_token: 1.5e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/magistral-medium-2506:thinking",
    },
    cost: {
      prompt_token: 2e-6,
      completion_token: 5e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/magistral-medium-2506",
    },
    cost: {
      prompt_token: 2e-6,
      completion_token: 5e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "google/gemini-2.5-pro-preview",
    },
    cost: {
      prompt_token: 1.25e-6,
      completion_token: 1e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "deepseek/deepseek-r1-0528-qwen3-8b:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "deepseek/deepseek-r1-0528-qwen3-8b",
    },
    cost: {
      prompt_token: 3e-8,
      completion_token: 1.1e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "deepseek/deepseek-r1-0528:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "deepseek/deepseek-r1-0528",
    },
    cost: {
      prompt_token: 4e-7,
      completion_token: 1.75e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "anthropic/claude-opus-4",
    },
    cost: {
      prompt_token: 1.5e-5,
      completion_token: 7.5e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "anthropic/claude-sonnet-4",
    },
    cost: {
      prompt_token: 3e-6,
      completion_token: 1.5e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/devstral-small-2505:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/devstral-small-2505",
    },
    cost: {
      prompt_token: 5e-8,
      completion_token: 2.2e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "google/gemma-3n-e4b-it:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "google/gemma-3n-e4b-it",
    },
    cost: {
      prompt_token: 2e-8,
      completion_token: 4e-8,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/codex-mini",
    },
    cost: {
      prompt_token: 1.5e-6,
      completion_token: 6e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "meta-llama/llama-3.3-8b-instruct:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "nousresearch/deephermes-3-mistral-24b-preview",
    },
    cost: {
      prompt_token: 1.5e-7,
      completion_token: 5.9e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/mistral-medium-3",
    },
    cost: {
      prompt_token: 4e-7,
      completion_token: 2e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "google/gemini-2.5-pro-preview-05-06",
    },
    cost: {
      prompt_token: 1.25e-6,
      completion_token: 1e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "arcee-ai/spotlight",
    },
    cost: {
      prompt_token: 1.8e-7,
      completion_token: 1.8e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "arcee-ai/maestro-reasoning",
    },
    cost: {
      prompt_token: 9e-7,
      completion_token: 3.3e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "arcee-ai/virtuoso-large",
    },
    cost: {
      prompt_token: 7.5e-7,
      completion_token: 1.2e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "arcee-ai/coder-large",
    },
    cost: {
      prompt_token: 5e-7,
      completion_token: 8e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "microsoft/phi-4-reasoning-plus",
    },
    cost: {
      prompt_token: 7e-8,
      completion_token: 3.5e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "inception/mercury-coder",
    },
    cost: {
      prompt_token: 2.5e-7,
      completion_token: 1e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen3-4b:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "deepseek/deepseek-prover-v2",
    },
    cost: {
      prompt_token: 5e-7,
      completion_token: 2.18e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "meta-llama/llama-guard-4-12b",
    },
    cost: {
      prompt_token: 1.8e-7,
      completion_token: 1.8e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen3-30b-a3b:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen3-30b-a3b",
    },
    cost: {
      prompt_token: 6e-8,
      completion_token: 2.2e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen3-8b:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen3-8b",
    },
    cost: {
      prompt_token: 3.5e-8,
      completion_token: 1.38e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen3-14b:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen3-14b",
    },
    cost: {
      prompt_token: 5e-8,
      completion_token: 2.2e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen3-32b",
    },
    cost: {
      prompt_token: 5e-8,
      completion_token: 2e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen3-235b-a22b:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen3-235b-a22b",
    },
    cost: {
      prompt_token: 1.8e-7,
      completion_token: 5.4e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "tngtech/deepseek-r1t-chimera:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "tngtech/deepseek-r1t-chimera",
    },
    cost: {
      prompt_token: 3e-7,
      completion_token: 1.2e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "microsoft/mai-ds-r1:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "microsoft/mai-ds-r1",
    },
    cost: {
      prompt_token: 3e-7,
      completion_token: 1.2e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "thudm/glm-z1-32b",
    },
    cost: {
      prompt_token: 5e-8,
      completion_token: 2.2e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/o4-mini-high",
    },
    cost: {
      prompt_token: 1.1e-6,
      completion_token: 4.4e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/o3",
    },
    cost: {
      prompt_token: 2e-6,
      completion_token: 8e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/o4-mini",
    },
    cost: {
      prompt_token: 1.1e-6,
      completion_token: 4.4e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "shisa-ai/shisa-v2-llama3.3-70b:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "shisa-ai/shisa-v2-llama3.3-70b",
    },
    cost: {
      prompt_token: 5e-8,
      completion_token: 2.2e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen2.5-coder-7b-instruct",
    },
    cost: {
      prompt_token: 3e-8,
      completion_token: 9e-8,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-4.1",
    },
    cost: {
      prompt_token: 2e-6,
      completion_token: 8e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-4.1-mini",
    },
    cost: {
      prompt_token: 4e-7,
      completion_token: 1.6e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-4.1-nano",
    },
    cost: {
      prompt_token: 1e-7,
      completion_token: 4e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "eleutherai/llemma_7b",
    },
    cost: {
      prompt_token: 8e-7,
      completion_token: 1.2e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "alfredpros/codellama-7b-instruct-solidity",
    },
    cost: {
      prompt_token: 8e-7,
      completion_token: 1.2e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "arliai/qwq-32b-arliai-rpr-v1:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "arliai/qwq-32b-arliai-rpr-v1",
    },
    cost: {
      prompt_token: 3e-8,
      completion_token: 1.1e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "agentica-org/deepcoder-14b-preview:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "agentica-org/deepcoder-14b-preview",
    },
    cost: {
      prompt_token: 1.5e-8,
      completion_token: 1.5e-8,
    },
  },
  {
    model: {
      operator: "equals",
      value: "x-ai/grok-3-mini-beta",
    },
    cost: {
      prompt_token: 3e-7,
      completion_token: 5e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "x-ai/grok-3-beta",
    },
    cost: {
      prompt_token: 3e-6,
      completion_token: 1.5e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "nvidia/llama-3.1-nemotron-ultra-253b-v1",
    },
    cost: {
      prompt_token: 6e-7,
      completion_token: 1.8e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "meta-llama/llama-4-maverick:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "meta-llama/llama-4-maverick",
    },
    cost: {
      prompt_token: 1.5e-7,
      completion_token: 6e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "meta-llama/llama-4-scout:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "meta-llama/llama-4-scout",
    },
    cost: {
      prompt_token: 8e-8,
      completion_token: 3e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "allenai/molmo-7b-d",
    },
    cost: {
      prompt_token: 1e-7,
      completion_token: 2e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen2.5-vl-32b-instruct:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen2.5-vl-32b-instruct",
    },
    cost: {
      prompt_token: 5e-8,
      completion_token: 2.2e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "deepseek/deepseek-chat-v3-0324:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "deepseek/deepseek-chat-v3-0324",
    },
    cost: {
      prompt_token: 2.4e-7,
      completion_token: 8.4e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/o1-pro",
    },
    cost: {
      prompt_token: 0.00015,
      completion_token: 0.0006,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/mistral-small-3.1-24b-instruct:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/mistral-small-3.1-24b-instruct",
    },
    cost: {
      prompt_token: 5e-8,
      completion_token: 1e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "allenai/olmo-2-0325-32b-instruct",
    },
    cost: {
      prompt_token: 2e-7,
      completion_token: 3.5e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "google/gemma-3-4b-it:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "google/gemma-3-4b-it",
    },
    cost: {
      prompt_token: 1.703012e-8,
      completion_token: 6.81536e-8,
    },
  },
  {
    model: {
      operator: "equals",
      value: "google/gemma-3-12b-it:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "google/gemma-3-12b-it",
    },
    cost: {
      prompt_token: 3e-8,
      completion_token: 1e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "cohere/command-a",
    },
    cost: {
      prompt_token: 2.5e-6,
      completion_token: 1e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-4o-mini-search-preview",
    },
    cost: {
      prompt_token: 1.5e-7,
      completion_token: 6e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-4o-search-preview",
    },
    cost: {
      prompt_token: 2.5e-6,
      completion_token: 1e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "google/gemma-3-27b-it:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "google/gemma-3-27b-it",
    },
    cost: {
      prompt_token: 9e-8,
      completion_token: 1.6e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "thedrummer/skyfall-36b-v2",
    },
    cost: {
      prompt_token: 8e-8,
      completion_token: 3.3e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "microsoft/phi-4-multimodal-instruct",
    },
    cost: {
      prompt_token: 5e-8,
      completion_token: 1e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "perplexity/sonar-reasoning-pro",
    },
    cost: {
      prompt_token: 2e-6,
      completion_token: 8e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "perplexity/sonar-pro",
    },
    cost: {
      prompt_token: 3e-6,
      completion_token: 1.5e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "perplexity/sonar-deep-research",
    },
    cost: {
      prompt_token: 2e-6,
      completion_token: 8e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwq-32b",
    },
    cost: {
      prompt_token: 1.5e-7,
      completion_token: 4e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "nousresearch/deephermes-3-llama-3-8b-preview:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "nousresearch/deephermes-3-llama-3-8b-preview",
    },
    cost: {
      prompt_token: 3e-8,
      completion_token: 1.1e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "google/gemini-2.0-flash-lite-001",
    },
    cost: {
      prompt_token: 7.5e-8,
      completion_token: 3e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "anthropic/claude-3.7-sonnet",
    },
    cost: {
      prompt_token: 3e-6,
      completion_token: 1.5e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "anthropic/claude-3.7-sonnet:thinking",
    },
    cost: {
      prompt_token: 3e-6,
      completion_token: 1.5e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/mistral-saba",
    },
    cost: {
      prompt_token: 2e-7,
      completion_token: 6e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "cognitivecomputations/dolphin3.0-mistral-24b:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "cognitivecomputations/dolphin3.0-mistral-24b",
    },
    cost: {
      prompt_token: 4e-8,
      completion_token: 1.7e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "meta-llama/llama-guard-3-8b",
    },
    cost: {
      prompt_token: 2e-8,
      completion_token: 6e-8,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/o3-mini-high",
    },
    cost: {
      prompt_token: 1.1e-6,
      completion_token: 4.4e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "google/gemini-2.0-flash-001",
    },
    cost: {
      prompt_token: 1e-7,
      completion_token: 4e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen-vl-plus",
    },
    cost: {
      prompt_token: 2.1e-7,
      completion_token: 6.3e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "aion-labs/aion-1.0",
    },
    cost: {
      prompt_token: 4e-6,
      completion_token: 8e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "aion-labs/aion-1.0-mini",
    },
    cost: {
      prompt_token: 7e-7,
      completion_token: 1.4e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "aion-labs/aion-rp-llama-3.1-8b",
    },
    cost: {
      prompt_token: 2e-7,
      completion_token: 2e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen-vl-max",
    },
    cost: {
      prompt_token: 8e-7,
      completion_token: 3.2e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen-turbo",
    },
    cost: {
      prompt_token: 5e-8,
      completion_token: 2e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen2.5-vl-72b-instruct:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen2.5-vl-72b-instruct",
    },
    cost: {
      prompt_token: 8e-8,
      completion_token: 3.3e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen-plus",
    },
    cost: {
      prompt_token: 4e-7,
      completion_token: 1.2e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen-max",
    },
    cost: {
      prompt_token: 1.6e-6,
      completion_token: 6.4e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/o3-mini",
    },
    cost: {
      prompt_token: 1.1e-6,
      completion_token: 4.4e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/mistral-small-24b-instruct-2501:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/mistral-small-24b-instruct-2501",
    },
    cost: {
      prompt_token: 5e-8,
      completion_token: 8e-8,
    },
  },
  {
    model: {
      operator: "equals",
      value: "deepseek/deepseek-r1-distill-qwen-32b",
    },
    cost: {
      prompt_token: 2.7e-7,
      completion_token: 2.7e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "deepseek/deepseek-r1-distill-qwen-14b",
    },
    cost: {
      prompt_token: 1.5e-7,
      completion_token: 1.5e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "perplexity/sonar-reasoning",
    },
    cost: {
      prompt_token: 1e-6,
      completion_token: 5e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "perplexity/sonar",
    },
    cost: {
      prompt_token: 1e-6,
      completion_token: 1e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "deepseek/deepseek-r1-distill-llama-70b:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "deepseek/deepseek-r1-distill-llama-70b",
    },
    cost: {
      prompt_token: 3e-8,
      completion_token: 1.3e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "deepseek/deepseek-r1:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "deepseek/deepseek-r1",
    },
    cost: {
      prompt_token: 4e-7,
      completion_token: 2e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "minimax/minimax-01",
    },
    cost: {
      prompt_token: 2e-7,
      completion_token: 1.1e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/codestral-2501",
    },
    cost: {
      prompt_token: 3e-7,
      completion_token: 9e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "microsoft/phi-4",
    },
    cost: {
      prompt_token: 6e-8,
      completion_token: 1.4e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "sao10k/l3.1-70b-hanami-x1",
    },
    cost: {
      prompt_token: 3e-6,
      completion_token: 3e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "deepseek/deepseek-chat",
    },
    cost: {
      prompt_token: 3e-7,
      completion_token: 8.5e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "sao10k/l3.3-euryale-70b",
    },
    cost: {
      prompt_token: 6.5e-7,
      completion_token: 7.5e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/o1",
    },
    cost: {
      prompt_token: 1.5e-5,
      completion_token: 6e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "cohere/command-r7b-12-2024",
    },
    cost: {
      prompt_token: 3.75e-8,
      completion_token: 1.5e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "google/gemini-2.0-flash-exp:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "meta-llama/llama-3.3-70b-instruct:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "meta-llama/llama-3.3-70b-instruct",
    },
    cost: {
      prompt_token: 1.3e-7,
      completion_token: 3.8e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "amazon/nova-lite-v1",
    },
    cost: {
      prompt_token: 6e-8,
      completion_token: 2.4e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "amazon/nova-micro-v1",
    },
    cost: {
      prompt_token: 3.5e-8,
      completion_token: 1.4e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "amazon/nova-pro-v1",
    },
    cost: {
      prompt_token: 8e-7,
      completion_token: 3.2e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-4o-2024-11-20",
    },
    cost: {
      prompt_token: 2.5e-6,
      completion_token: 1e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/mistral-large-2411",
    },
    cost: {
      prompt_token: 2e-6,
      completion_token: 6e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/mistral-large-2407",
    },
    cost: {
      prompt_token: 2e-6,
      completion_token: 6e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/pixtral-large-2411",
    },
    cost: {
      prompt_token: 2e-6,
      completion_token: 6e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen-2.5-coder-32b-instruct:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen-2.5-coder-32b-instruct",
    },
    cost: {
      prompt_token: 4e-8,
      completion_token: 1.6e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "raifle/sorcererlm-8x22b",
    },
    cost: {
      prompt_token: 4.5e-6,
      completion_token: 4.5e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "thedrummer/unslopnemo-12b",
    },
    cost: {
      prompt_token: 4e-7,
      completion_token: 4e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "anthropic/claude-3.5-haiku",
    },
    cost: {
      prompt_token: 8e-7,
      completion_token: 4e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "anthropic/claude-3.5-haiku-20241022",
    },
    cost: {
      prompt_token: 8e-7,
      completion_token: 4e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "anthracite-org/magnum-v4-72b",
    },
    cost: {
      prompt_token: 3e-6,
      completion_token: 5e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "anthropic/claude-3.5-sonnet",
    },
    cost: {
      prompt_token: 3e-6,
      completion_token: 1.5e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/ministral-8b",
    },
    cost: {
      prompt_token: 1e-7,
      completion_token: 1e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/ministral-3b",
    },
    cost: {
      prompt_token: 4e-8,
      completion_token: 4e-8,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen-2.5-7b-instruct",
    },
    cost: {
      prompt_token: 4e-8,
      completion_token: 1e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "nvidia/llama-3.1-nemotron-70b-instruct",
    },
    cost: {
      prompt_token: 6e-7,
      completion_token: 6e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "inflection/inflection-3-productivity",
    },
    cost: {
      prompt_token: 2.5e-6,
      completion_token: 1e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "inflection/inflection-3-pi",
    },
    cost: {
      prompt_token: 2.5e-6,
      completion_token: 1e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "anthracite-org/magnum-v2-72b",
    },
    cost: {
      prompt_token: 3e-6,
      completion_token: 3e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "thedrummer/rocinante-12b",
    },
    cost: {
      prompt_token: 1.7e-7,
      completion_token: 4.3e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "meta-llama/llama-3.2-3b-instruct:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "meta-llama/llama-3.2-3b-instruct",
    },
    cost: {
      prompt_token: 2e-8,
      completion_token: 2e-8,
    },
  },
  {
    model: {
      operator: "equals",
      value: "meta-llama/llama-3.2-11b-vision-instruct",
    },
    cost: {
      prompt_token: 4.9e-8,
      completion_token: 4.9e-8,
    },
  },
  {
    model: {
      operator: "equals",
      value: "meta-llama/llama-3.2-90b-vision-instruct",
    },
    cost: {
      prompt_token: 3.5e-7,
      completion_token: 4e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "meta-llama/llama-3.2-1b-instruct",
    },
    cost: {
      prompt_token: 5e-9,
      completion_token: 1e-8,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen-2.5-72b-instruct:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen-2.5-72b-instruct",
    },
    cost: {
      prompt_token: 7e-8,
      completion_token: 2.6e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "neversleep/llama-3.1-lumimaid-8b",
    },
    cost: {
      prompt_token: 9e-8,
      completion_token: 6e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/o1-mini",
    },
    cost: {
      prompt_token: 1.1e-6,
      completion_token: 4.4e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/o1-mini-2024-09-12",
    },
    cost: {
      prompt_token: 1.1e-6,
      completion_token: 4.4e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/pixtral-12b",
    },
    cost: {
      prompt_token: 1e-7,
      completion_token: 1e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "cohere/command-r-plus-08-2024",
    },
    cost: {
      prompt_token: 2.5e-6,
      completion_token: 1e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "cohere/command-r-08-2024",
    },
    cost: {
      prompt_token: 1.5e-7,
      completion_token: 6e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "qwen/qwen-2.5-vl-7b-instruct",
    },
    cost: {
      prompt_token: 2e-7,
      completion_token: 2e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "sao10k/l3.1-euryale-70b",
    },
    cost: {
      prompt_token: 6.5e-7,
      completion_token: 7.5e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "microsoft/phi-3.5-mini-128k-instruct",
    },
    cost: {
      prompt_token: 1e-7,
      completion_token: 1e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "nousresearch/hermes-3-llama-3.1-70b",
    },
    cost: {
      prompt_token: 3e-7,
      completion_token: 3e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "nousresearch/hermes-3-llama-3.1-405b",
    },
    cost: {
      prompt_token: 1e-6,
      completion_token: 1e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/chatgpt-4o-latest",
    },
    cost: {
      prompt_token: 5e-6,
      completion_token: 1.5e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "sao10k/l3-lunaris-8b",
    },
    cost: {
      prompt_token: 4e-8,
      completion_token: 5e-8,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-4o-2024-08-06",
    },
    cost: {
      prompt_token: 2.5e-6,
      completion_token: 1e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "meta-llama/llama-3.1-405b",
    },
    cost: {
      prompt_token: 4e-6,
      completion_token: 4e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "meta-llama/llama-3.1-405b-instruct",
    },
    cost: {
      prompt_token: 8e-7,
      completion_token: 8e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "meta-llama/llama-3.1-8b-instruct",
    },
    cost: {
      prompt_token: 2e-8,
      completion_token: 3e-8,
    },
  },
  {
    model: {
      operator: "equals",
      value: "meta-llama/llama-3.1-70b-instruct",
    },
    cost: {
      prompt_token: 4e-7,
      completion_token: 4e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/mistral-nemo:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/mistral-nemo",
    },
    cost: {
      prompt_token: 2e-8,
      completion_token: 4e-8,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-4o-mini",
    },
    cost: {
      prompt_token: 1.5e-7,
      completion_token: 6e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-4o-mini-2024-07-18",
    },
    cost: {
      prompt_token: 1.5e-7,
      completion_token: 6e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "google/gemma-2-27b-it",
    },
    cost: {
      prompt_token: 6.5e-7,
      completion_token: 6.5e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "google/gemma-2-9b-it:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "google/gemma-2-9b-it",
    },
    cost: {
      prompt_token: 1e-8,
      completion_token: 3e-8,
    },
  },
  {
    model: {
      operator: "equals",
      value: "anthropic/claude-3.5-sonnet-20240620",
    },
    cost: {
      prompt_token: 3e-6,
      completion_token: 1.5e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "sao10k/l3-euryale-70b",
    },
    cost: {
      prompt_token: 1.48e-6,
      completion_token: 1.48e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/mistral-7b-instruct:free",
    },
    cost: {
      prompt_token: 0.0,
      completion_token: 0.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/mistral-7b-instruct",
    },
    cost: {
      prompt_token: 2.8e-8,
      completion_token: 5.4e-8,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/mistral-7b-instruct-v0.3",
    },
    cost: {
      prompt_token: 2.8e-8,
      completion_token: 5.4e-8,
    },
  },
  {
    model: {
      operator: "equals",
      value: "nousresearch/hermes-2-pro-llama-3-8b",
    },
    cost: {
      prompt_token: 2.5e-8,
      completion_token: 8e-8,
    },
  },
  {
    model: {
      operator: "equals",
      value: "microsoft/phi-3-mini-128k-instruct",
    },
    cost: {
      prompt_token: 1e-7,
      completion_token: 1e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "microsoft/phi-3-medium-128k-instruct",
    },
    cost: {
      prompt_token: 1e-6,
      completion_token: 1e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "meta-llama/llama-guard-2-8b",
    },
    cost: {
      prompt_token: 2e-7,
      completion_token: 2e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-4o-2024-05-13",
    },
    cost: {
      prompt_token: 5e-6,
      completion_token: 1.5e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-4o",
    },
    cost: {
      prompt_token: 2.5e-6,
      completion_token: 1e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-4o:extended",
    },
    cost: {
      prompt_token: 6e-6,
      completion_token: 1.8e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "meta-llama/llama-3-8b-instruct",
    },
    cost: {
      prompt_token: 3e-8,
      completion_token: 6e-8,
    },
  },
  {
    model: {
      operator: "equals",
      value: "meta-llama/llama-3-70b-instruct",
    },
    cost: {
      prompt_token: 3e-7,
      completion_token: 4e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/mixtral-8x22b-instruct",
    },
    cost: {
      prompt_token: 2e-6,
      completion_token: 6e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "microsoft/wizardlm-2-8x22b",
    },
    cost: {
      prompt_token: 4.8e-7,
      completion_token: 4.8e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-4-turbo",
    },
    cost: {
      prompt_token: 1e-5,
      completion_token: 3e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "anthropic/claude-3-haiku",
    },
    cost: {
      prompt_token: 2.5e-7,
      completion_token: 1.25e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "anthropic/claude-3-opus",
    },
    cost: {
      prompt_token: 1.5e-5,
      completion_token: 7.5e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/mistral-large",
    },
    cost: {
      prompt_token: 2e-6,
      completion_token: 6e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-3.5-turbo-0613",
    },
    cost: {
      prompt_token: 1e-6,
      completion_token: 2e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-4-turbo-preview",
    },
    cost: {
      prompt_token: 1e-5,
      completion_token: 3e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/mistral-small",
    },
    cost: {
      prompt_token: 2e-7,
      completion_token: 6e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/mistral-tiny",
    },
    cost: {
      prompt_token: 2.5e-7,
      completion_token: 2.5e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/mistral-7b-instruct-v0.2",
    },
    cost: {
      prompt_token: 2e-7,
      completion_token: 2e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/mixtral-8x7b-instruct",
    },
    cost: {
      prompt_token: 5.4e-7,
      completion_token: 5.4e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "neversleep/noromaid-20b",
    },
    cost: {
      prompt_token: 1e-6,
      completion_token: 1.75e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "alpindale/goliath-120b",
    },
    cost: {
      prompt_token: 4e-6,
      completion_token: 5.5e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openrouter/auto",
    },
    cost: {
      prompt_token: -1.0,
      completion_token: -1.0,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-4-1106-preview",
    },
    cost: {
      prompt_token: 1e-5,
      completion_token: 3e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mistralai/mistral-7b-instruct-v0.1",
    },
    cost: {
      prompt_token: 1.1e-7,
      completion_token: 1.9e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-3.5-turbo-instruct",
    },
    cost: {
      prompt_token: 1.5e-6,
      completion_token: 2e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-3.5-turbo-16k",
    },
    cost: {
      prompt_token: 3e-6,
      completion_token: 4e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "mancer/weaver",
    },
    cost: {
      prompt_token: 1.125e-6,
      completion_token: 1.125e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "undi95/remm-slerp-l2-13b",
    },
    cost: {
      prompt_token: 4.5e-7,
      completion_token: 6.5e-7,
    },
  },
  {
    model: {
      operator: "equals",
      value: "gryphe/mythomax-l2-13b",
    },
    cost: {
      prompt_token: 5e-8,
      completion_token: 9e-8,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-3.5-turbo",
    },
    cost: {
      prompt_token: 5e-7,
      completion_token: 1.5e-6,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-4-0314",
    },
    cost: {
      prompt_token: 3e-5,
      completion_token: 6e-5,
    },
  },
  {
    model: {
      operator: "equals",
      value: "openai/gpt-4",
    },
    cost: {
      prompt_token: 3e-5,
      completion_token: 6e-5,
    },
  },
];
