export const hotels = [
  {
    id: "HTL_123456",
    name: "Grand Plaza Hotel",
    rating: 4.8,
    pricePerNight: 299,
    currency: "USD",
    location: {
      address: "123 Main Street",
      neighborhood: "City Center",
      distanceToCenter: "0.5 km",
      coordinates: { lat: 40.7128, lng: -74.006 },
    },
    amenities: [
      "Free WiFi",
      "Rooftop Pool",
      "Spa",
      "Fitness Center",
      "24/7 Room Service",
      "Business Center",
      "Airport Shuttle",
    ],
    rooms: [
      {
        type: "Deluxe King",
        price: 299,
        available: 3,
        maxOccupancy: 2,
        bedType: "1 King Bed",
        sqm: 35,
      },
      {
        type: "Executive Suite",
        price: 499,
        available: 1,
        maxOccupancy: 3,
        bedType: "1 King Bed + Sofa Bed",
        sqm: 55,
      },
    ],
    reviews: {
      average: 4.8,
      count: 1250,
      highlights: ["Excellent location", "Friendly staff", "Clean rooms"],
    },
  },
  {
    id: "HTL_789012",
    name: "Boutique Garden Inn",
    rating: 4.5,
    pricePerNight: 199,
    currency: "USD",
    location: {
      address: "456 Park Avenue",
      neighborhood: "Historic District",
      distanceToCenter: "1.2 km",
      coordinates: { lat: 40.7129, lng: -74.0061 },
    },
    amenities: [
      "Free WiFi",
      "Garden",
      "Breakfast Included",
      "Bike Rental",
      "Concierge Service",
    ],
    rooms: [
      {
        type: "Garden View Queen",
        price: 199,
        available: 5,
        maxOccupancy: 2,
        bedType: "1 Queen Bed",
        sqm: 28,
      },
    ],
    reviews: {
      average: 4.5,
      count: 850,
      highlights: ["Beautiful garden", "Great breakfast", "Quiet location"],
    },
  },
];

export const flights = [
  {
    id: "FL_123456",
    outbound: {
      flightNumber: "UA456",
      airline: "United Airlines",
      departure: { airport: "SFO", time: "10:30" },
      arrival: { airport: "JFK", time: "19:00" },
      duration: "8h 30m",
      stops: 0,
      aircraft: "Boeing 787-9",
    },
    return: {
      flightNumber: "UA457",
      airline: "United Airlines",
      departure: { airport: "JFK", time: "11:30" },
      arrival: { airport: "SFO", time: "14:45" },
      duration: "6h 15m",
      stops: 0,
      aircraft: "Boeing 787-9",
    },
    price: {
      total: 842,
      currency: "USD",
      breakdown: {
        base: 720,
        taxes: 122,
        fees: 0,
      },
    },
    seatsAvailable: 4,
    cabinClass: "Economy",
    features: ["Meal", "WiFi", "Power outlets", "Entertainment"],
  },
  {
    id: "FL_789012",
    outbound: {
      flightNumber: "DL123",
      airline: "Delta Airlines",
      departure: { airport: "SFO", time: "07:15" },
      arrival: { airport: "JFK", time: "16:00" },
      duration: "8h 45m",
      stops: 1,
      stopover: "ORD",
      aircraft: "Airbus A321",
    },
    return: {
      flightNumber: "DL124",
      airline: "Delta Airlines",
      departure: { airport: "JFK", time: "09:00" },
      arrival: { airport: "SFO", time: "12:30" },
      duration: "6h 30m",
      stops: 0,
      aircraft: "Boeing 757-200",
    },
    price: {
      total: 756,
      currency: "USD",
      breakdown: {
        base: 650,
        taxes: 106,
        fees: 0,
      },
    },
    seatsAvailable: 6,
    cabinClass: "Economy",
    features: ["Snack", "WiFi", "Entertainment"],
  },
];
