name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize]
    # Optional: Only run on specific file changes
#     paths:
#   - "src/**/*.ts"
#   - "src/**/*.tsx"
#   - "src/**/*.js"
#   - "src/**/*.jsx"

jobs:
  claude-review:
    # Optional: Filter by PR author
    # if: |
    #   github.event.pull_request.user.login == 'external-contributor' ||
    #   github.event.pull_request.user.login == 'new-developer' ||
    #   github.event.pull_request.author_association == 'FIRST_TIME_CONTRIBUTOR'

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write  # Required for inline comments
      issues: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

          # Optional: Specify model (defaults to Claude Sonnet 4, uncomment for Claude Opus 4.1)
          # model: "claude-opus-4-1-20250805"

          # Direct prompt for automated review (no @claude mention needed)
          direct_prompt: |
            Review this PR and provide constructive feedback focusing on:
            - Critical bugs or security issues
            - Performance improvements and optimizations
            - Code quality and best practices
            - Potential refactoring opportunities
            - Breaking changes or API issues

            For each issue found, provide:
            1. Clear explanation of the problem
            2. Specific suggestions for improvement
            3. Code examples when helpful

            Use inline comments for specific code suggestions and improvements.
            Provide actionable recommendations, not just issue identification.

            Provide a confidence score (0-10):
            - 0-3: Critical issues, do not merge
            - 4-7: Minor issues or improvements suggested, merge with consideration
            - 8-10: Good to merge, minor or no suggestions

            Summary format:
            **Score: X/10** - Brief reason

            **Suggestions Summary:**
            - List key improvement suggestions
            - Highlight any critical fixes needed

          # Enable sticky comments to update existing comments instead of creating new ones
          use_sticky_comment: true

          # Enable inline suggestions for specific code improvements
          review_mode: "inline"

          # Optional: Different prompts for different authors
          # direct_prompt: |
          #   ${{ github.event.pull_request.author_association == 'FIRST_TIME_CONTRIBUTOR' &&
          #   'Welcome! Please review this PR from a first-time contributor. Be encouraging and provide detailed explanations for any suggestions.' ||
          #   'Please provide a thorough code review focusing on our coding standards and best practices.' }}

          # Optional: Add specific tools for running tests or linting
          allowed_tools: "Bash(yarn build),Bash(yarn test),Bash(yarn lint)"

          # Optional: Allow specific bots to trigger this workflow
          allowed_bots: "greptile-apps"

          # Optional: Skip review for certain conditions
          if: |
            !contains(github.event.pull_request.title, '[WIP]')
