name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches:
      - main
      - staging
      - production

  issue_comment:
    types: [created]

jobs:
  claude-review:
    name: claude-review
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
      id-token: write
    if: |
      (github.event_name == 'pull_request' && !contains(github.event.pull_request.title, '[WIP]')) ||
      (github.event_name == 'issue_comment' && github.event.issue.pull_request && contains(github.event.comment.body, '@claude'))
    steps:
      - uses: actions/checkout@v4
      - uses: anthropics/claude-code-action@beta
        with:
          # Required: Claude Code OAuth token
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

          # Optional: Direct prompt to Claude
          direct_prompt: |
            Put long feedback in a collapsible section. (<details>...</details>)
            Please review this pull request and provide feedback on:
            - Code quality and best practices
            - Potential bugs or issues
            - Performance considerations
            - Security concerns

            Be constructive and helpful in your feedback.

            Add a confidence score to the feedback. (0-10) 
              - 0: Do not merge this PR
              - 5: Merge this PR with caution
              - 10: Merge this PR

            [Reason why if low score]


            Add a summary of the feedback. Highlight the most important feedback, like the most important bugs, or the most important performance improvements.

          # Optional: Use a sticky comment for Claude's feedback
          use_sticky_comment: true

          # Optional: Allow specific tools for Claude to use
          allowed_tools: "Bash(yarn build),Bash(yarn test),Bash(yarn lint)"

          # Optional: Allow specific bots to trigger this workflow
          allowed_bots: "greptile-apps,codegen-sh"

          # Optional: Skip review for certain conditions
          if: |
            !contains(github.event.pull_request.title, '[WIP]')

          # Optional: Trigger phrase for comment-based reviews
          trigger_phrase: "@claude"

          # Optional: Trigger on label
          label_trigger: "claude"

          # Optional: Branch prefix for Claude's PRs
          branch_prefix: "claude/"

          # Optional: Mode (tag, comment, or pr)
          mode: "tag"

          # Optional: Use AWS Bedrock for Claude
          use_bedrock: false

          # Optional: Use Google Vertex AI for Claude
          use_vertex: false

          # Optional: Timeout in minutes
          timeout_minutes: 30

          # Optional: Use commit signing for Claude's commits
          use_commit_signing: false

