name: Packages Tests

on:
  push:
    paths:
      - 'packages/**'
      - 'yarn.lock'
      - 'package.json'
      - '.github/workflows/packages-tests.yml'
  pull_request:
    paths:
      - 'packages/**'
      - 'yarn.lock'
      - 'package.json'
      - '.github/workflows/packages-tests.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run packages tests
        uses: ./.github/actions/node-test
        with:
          test-command: npx jest --config packages/jest.config.ts --runInBand


