name: Web Tests

on:
  push:
    paths:
      - 'web/**'
      - 'yarn.lock'
      - 'package.json'
      - '.github/workflows/web-tests.yml'
  pull_request:
    paths:
      - 'web/**'
      - 'yarn.lock'
      - 'package.json'
      - '.github/workflows/web-tests.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run web tests
        uses: ./.github/actions/node-test
        with:
          working-directory: web
          test-command: npx jest --passWithNoTests --runInBand


