name: Worker Build Precheck
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  worker-build-precheck:
    name: Worker Build Precheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: worker/package-lock.json
      - name: Install
        run: |
          cd worker
          npm ci
      - name: Build
        run: |
          cd worker
          npx tsc
