name: Worker Tests

on:
  push:
    paths:
      - 'worker/**'
      - 'yarn.lock'
      - 'package.json'
      - '.github/workflows/worker-tests.yml'
  pull_request:
    paths:
      - 'worker/**'
      - 'yarn.lock'
      - 'package.json'
      - '.github/workflows/worker-tests.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run worker tests
        uses: ./.github/actions/node-test
        with:
          test-command: yarn workspace helicone-worker test:run -- --reporter=dot


