name: Worker Tests

on:
  push:
    branches:
      - "**"  # Run on ALL branches for every push
  pull_request:
    branches:
      - "**"  # Run on ALL branches for PRs
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  worker-tests:
    name: Worker Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Use pre-installed Node 20 (saves 30+ seconds!)
      - name: Use pre-installed Node 20
        run: |
          echo "Using pre-installed Node"
          node --version
          npm --version
      
      # Cache the actual node_modules directory (not just global cache)
      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v4
        with:
          path: |
            worker/node_modules
            packages/node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      
      # Only install if cache miss
      - name: Install dependencies
        if: steps.cache-modules.outputs.cache-hit != 'true'
        working-directory: worker
        run: yarn install --frozen-lockfile --ignore-scripts
      
      # If using native modules, rebuild them (only if cached)
      - name: Rebuild native modules
        if: steps.cache-modules.outputs.cache-hit == 'true'
        working-directory: worker
        run: yarn rebuild || true
      
      - name: Run tests
        working-directory: worker
        run: yarn test
      
      # Optional: Include test summary in PR
      - name: Test Summary
        if: always()
        run: |
          echo "✅ Worker tests completed"